Repository chipsalliance/chisel, pull requests merged in 2019-11, with the labels that each got.

#1224 Improve naming of anonymous/class-in-function Modules
  chiselFrontend/src/main/scala/chisel3/Module.scala
  src/test/scala/chiselTests/Module.scala
Labels: Merge with merge commit, bug, bugfix

#1201 Don't use MuxLookup default for full mapping
  src/main/scala/chisel3/util/Mux.scala
  src/test/scala/chiselTests/MuxSpec.scala
Labels: API Modification, Merge with merge commit

#1252 Fix bidirectional Wire with Analog
  chiselFrontend/src/main/scala/chisel3/experimental/Analog.scala
  src/test/scala/chiselTests/AnalogSpec.scala
Labels: bugfix

#1257 Use macro to materialize CompileOptions in Chisel._ (bp #1253)
  src/main/scala/chisel3/compatibility.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
Labels: Backport

#1256 Fix deprecation warning that leaks into user code
  chiselFrontend/src/main/scala/chisel3/Data.scala
Labels: Please Merge, bugfix
