Repository chipsalliance/chisel, pull requests merged in 2019-12, with the labels that each got.

#1258 Fix asTypeOf for Clock
  chiselFrontend/src/main/scala/chisel3/Clock.scala
  src/test/scala/chiselTests/AsTypeOfTester.scala
Labels: Please Merge, bugfix

#1264 Remove Jenkins CI from .mergify.yml
  .mergify.yml
Labels: Please Merge

#1268 Revert "Compat compile options macro"
  src/main/scala/chisel3/compatibility.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
Labels: Please Merge

#1269 Revert "Use macro to materialize CompileOptions in Chisel._ (bp #1253)"
  src/main/scala/chisel3/compatibility.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
Labels: Please Merge

#1274 Bug fixes to support code for Interval
  chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/IntervalRangeSpec.scala
Labels: bugfix

#1273 Remove unused WriteEmitted phase
  src/main/scala/chisel3/stage/package.scala
Labels: Please Merge

#1277 Band aid until litOption is implemented for Aggregates.
  chiselFrontend/src/main/scala/chisel3/Aggregate.scala
Labels: Please Merge
