Repository chipsalliance/chisel, pull requests merged in 2019-05, with the labels that each got.

#1086 Expand upon ScalaDoc in Driver
  src/main/scala/chisel3/Driver.scala
Labels: code improvement

#1088 PRNG and LFSR Utils
  src/main/scala/chisel3/util/LFSR.scala
  src/main/scala/chisel3/util/random/FibonacciLFSR.scala
  src/main/scala/chisel3/util/random/GaloisLFSR.scala
  src/main/scala/chisel3/util/random/LFSR.scala
  src/main/scala/chisel3/util/random/PRNG.scala
  src/test/scala/chiselTests/InstanceNameSpec.scala
  src/test/scala/chiselTests/LFSR16.scala
  src/test/scala/chiselTests/QueueSpec.scala
  src/test/scala/chiselTests/util/random/LFSRSpec.scala
  src/test/scala/chiselTests/util/random/PRNGSpec.scala
Labels: API Addition, Merge with merge commit

#1091 Fix treatment of Vec of Analog and Vec of Bundle of Analog
  chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala
  chiselFrontend/src/main/scala/chisel3/core/Binding.scala
  chiselFrontend/src/main/scala/chisel3/core/Bits.scala
  chiselFrontend/src/main/scala/chisel3/core/Data.scala
  chiselFrontend/src/main/scala/chisel3/core/RawModule.scala
  chiselFrontend/src/main/scala/chisel3/core/StrongEnum.scala
  src/test/scala/chiselTests/AnalogSpec.scala
Labels: bugfix

#1022 Miscellaneous Scaladoc Cleanup
  build.sbt
  chiselFrontend/src/main/scala/chisel3/core/Annotation.scala
  chiselFrontend/src/main/scala/chisel3/core/Bits.scala
  chiselFrontend/src/main/scala/chisel3/core/Data.scala
  chiselFrontend/src/main/scala/chisel3/core/Reg.scala
  coreMacros/src/main/scala/chisel3/SourceInfoDoc.scala
  src/main/scala/chisel3/Driver.scala
  src/main/scala/chisel3/util/Valid.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/main/scala/chisel3/util/experimental/Inline.scala
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
Labels: Merge with merge commit

#1065 RawModule with no reset should be able to use withClock method.
  chiselFrontend/src/main/scala/chisel3/core/Module.scala
  chiselFrontend/src/main/scala/chisel3/core/MultiClock.scala
  chiselFrontend/src/main/scala/chisel3/core/RawModule.scala
  chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/Clock.scala
Labels: bug, code improvement
