Repository chipsalliance/chisel, pull requests merged in 2019-01, with the labels that each got.

#975 Add explicit Sonatype resolvers so SNAPSHOTs can be found remotely.
  build.sbt
Labels: feature request

#995 Support DontCare in Mux and cloneSupertype
  chiselFrontend/src/main/scala/chisel3/core/Data.scala
  chiselFrontend/src/main/scala/chisel3/core/Mux.scala
  src/test/scala/chiselTests/MuxSpec.scala
  src/test/scala/chiselTests/Vec.scala
Labels: bugfix

#943 RFC: Add Rocket Chip-style clonemodule as CloneAndGetIO to experimental
  chiselFrontend/src/main/scala/chisel3/core/Module.scala
  src/main/scala/chisel3/package.scala
  src/test/scala/chiselTests/CloneModuleSpec.scala
Labels: API Addition, DO NOT MERGE, Request For Comment
