Repository chipsalliance/chisel, pull requests merged in 2019-10, with the labels that each got.

#1194 Strip Object and Outer Class from desiredName
  chiselFrontend/src/main/scala/chisel3/Module.scala
  src/test/scala/chiselTests/DataPrint.scala
Labels: API Modification

#1210 Interval Data Type Support for Chisel
  chiselFrontend/src/main/scala/chisel3/Bits.scala
  chiselFrontend/src/main/scala/chisel3/Data.scala
  chiselFrontend/src/main/scala/chisel3/SIntFactory.scala
  chiselFrontend/src/main/scala/chisel3/UIntFactory.scala
  chiselFrontend/src/main/scala/chisel3/core/package.scala
  chiselFrontend/src/main/scala/chisel3/experimental/package.scala
  chiselFrontend/src/main/scala/chisel3/internal/MonoConnect.scala
  chiselFrontend/src/main/scala/chisel3/internal/firrtl/Converter.scala
  chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
  chiselFrontend/src/main/scala/chisel3/package.scala
  coreMacros/src/main/scala/chisel3/internal/RangeTransform.scala
  src/main/scala/chisel3/internal/firrtl/Emitter.scala
  src/test/scala/chiselTests/IntervalRangeSpec.scala
  src/test/scala/chiselTests/IntervalSpec.scala
  src/test/scala/chiselTests/RangeSpec.scala
  src/test/scala/chiselTests/ScalaIntervalSimulatorTest.scala
  src/test/scala/chiselTests/Util.scala
Labels: API Addition, API Modification, Squash and merge, release issue

#1175 Internal BoringUtils.bore Bug Fix
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: bugfix
