Repository chipsalliance/chisel, pull requests merged in 2020-06, with the labels that each got.

#1459 verilator_4_016 --> v4.016
  SETUP.md
Labels: Please Merge

#1073 Grouping Chisel API
  src/main/scala/chisel3/util/experimental/group.scala
  src/test/scala/chiselTests/experimental/GroupSpec.scala
Labels: Please Merge

#1425 Report Builder.error errors as exceptions outside hardware context
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/ImplicitConversionsSpec.scala
Labels: Please Merge, bugfix

#1476 Move LFSR16 to Compatibility Mode (Deprecated in 3.2)
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/LFSR.scala
  src/test/scala/chiselTests/LFSR16.scala
  src/test/scala/chiselTests/util/random/LFSRSpec.scala
Labels: API Modification

#1479 Have defaultVersions specify complete ModuleIDs.
  build.sbt
Labels: Please Merge

#1485 Memoize the hashcode of the ChiselCircuitAnnotation
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
Labels: Please Merge

#1439 Bump 'removed in 3.3' deprecations to 3.4
  core/src/main/scala/chisel3/core/package.scala
Labels: Please Merge

#785 Canonicalize construction of Decoupled with no payload
  src/main/scala/chisel3/util/Decoupled.scala
  src/test/scala/chiselTests/DecoupledSpec.scala
Labels: API Addition, Please Merge

#1493 Don't run FIRRTL in FlattenSpec's ChiselStage
  src/test/scala/chiselTests/InlineSpec.scala
Labels: Please Merge

#1495 Add .scala-steward.conf
  .scala-steward.conf
Labels: Please Merge

#1496 Fix TesterDriver.scala regression #1481
  src/main/scala/chisel3/testers/TesterDriver.scala
Labels: Please Merge, bugfix

#1483 This adds a mechanism for the unittests to be run with the TreadleBac…
  build.sbt
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/test/scala/chiselTests/AnalogIntegrationSpec.scala
  src/test/scala/chiselTests/AnalogSpec.scala
  src/test/scala/chiselTests/BlackBox.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/ExtModule.scala
  src/test/scala/chiselTests/MultiClockSpec.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
  src/test/scala/chiselTests/util/random/LFSRSpec.scala
  src/test/scala/examples/SimpleVendingMachine.scala
Labels: Request For Comment, feature request
