Repository chipsalliance/chisel, pull requests merged in 2020-07, with the labels that each got.

#1511 Update Development Meetings Info
  README.md
Labels: Please Merge

#1516 Add Treadle to CI builds
  .circleci/config.yml
Labels: Please Merge

#1520 Using TreadleTesterPhase now requires new
  src/main/scala/chisel3/testers/TesterDriver.scala
Labels: bugfix

#1525 update Select.get(IntermediateAnd)Leafs to work with records
  src/main/scala/chisel3/aop/Select.scala
Labels: Please Merge

#1524 Update build instructions in README
  README.md
Labels: Please Merge

#1515 Allow a counter to be instantiated using a Scala range
  src/main/scala/chisel3/util/Counter.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/Counter.scala
Labels: API Addition, Please Merge

#1480 Broken auto-clonetype on Scala 2.11.12
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: Please Merge, bugfix

#1534 Add emitSystemVerilog method to ChiselStage
  src/main/scala/chisel3/stage/ChiselStage.scala
Labels: Please Merge

#1518 Check whether signals escape their when scopes
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
  src/test/scala/chiselTests/CompileOptionsTest.scala
  src/test/scala/chiselTests/IllegalRefSpec.scala
Labels: Please Merge
