Repository chipsalliance/chisel, pull requests merged in 2020-09, with the labels that each got.

#1563 Better Building of FIRRTL From Source
  README.md
  build.sbt
  project/plugins.sbt
Labels: API Modification

#1583 Fix load memory from file to work with binary
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
Labels: Please Merge

#1580 Add new annotation for Chisel Circuit serialization
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselCli.scala
  src/main/scala/chisel3/stage/ChiselPhase.scala
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
  src/test/scala/chiselTests/stage/phases/AddSerializationAnnotationsSpec.scala
Labels: API Modification, Please Merge, bugfix

#1573 Documentation and minor plugin changes.
  build.sbt
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/plugin/package.scala
  docs/src/cookbooks/naming.md
  docs/src/explanations/naming.md
  plugin/src/main/resources/scalac-plugin.xml
  plugin/src/main/scala-2.12/chisel3/internal/plugin/ChiselPlugin.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
Labels: Please Merge

#1595 Support using switch without importing SwitchContext
  docs/src/wiki-deprecated/cookbook.md
  src/main/scala/chisel3/util/Conditional.scala
  src/test/scala/chiselTests/SwitchSpec.scala
Labels: Please Merge
