Repository chipsalliance/chisel, pull requests merged in 2020-03, with the labels that each got.

#1359 Cleanup aspects
  src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary
  src/main/scala/chisel3/aop/AspectLibrary.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/aop/inspecting/InspectingAspect.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
Labels: API Modification, Please Merge

#1361 Provide API to set concrete type of implicit reset
  chiselFrontend/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/ResetSpec.scala
Labels: Please Merge

#1360 Make implicit clock and reset final vals
  chiselFrontend/src/main/scala/chisel3/RawModule.scala
Labels: Please Merge

#1374 Dont wrap elaboration annotations
  chiselFrontend/src/main/scala/chisel3/internal/Error.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
Labels: Merge with merge commit, bugfix

#1380 Use innermost builder cause to trim stack trace
  chiselFrontend/src/main/scala/chisel3/internal/Error.scala
Labels: Please Merge, bugfix

#1383 Add NoChiselNamePrefix to ignore instances in @chiselName
  chiselFrontend/src/main/scala/chisel3/experimental/package.scala
  chiselFrontend/src/main/scala/chisel3/internal/Namer.scala
  coreMacros/src/main/scala/chisel3/internal/naming/NamingAnnotations.scala
  src/test/scala/chiselTests/NamingAnnotationTest.scala
Labels: Please Merge

#1377 Remove toNamed (and friends) deprecation.
  chiselFrontend/src/main/scala/chisel3/Module.scala
  chiselFrontend/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#1213 Deprecate Driver methods in favor of ChiselStage
  README.md
  src/main/scala/chisel3/Driver.scala
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: API Addition

#1387 Propagate user compile options for Chisel.Module
  src/main/scala/chisel3/compatibility.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
Labels: Please Merge, bugfix

#1384 No more compile internal
  build.sbt
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/Assert.scala
  core/src/main/scala/chisel3/Attach.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/BoolFactory.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/CompileOptions.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/ModuleAspect.scala
  core/src/main/scala/chisel3/MultiClock.scala
  core/src/main/scala/chisel3/Mux.scala
  core/src/main/scala/chisel3/Num.scala
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/SIntFactory.scala
  core/src/main/scala/chisel3/SeqUtils.scala
  core/src/main/scala/chisel3/StrongEnum.scala
  core/src/main/scala/chisel3/UIntFactory.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/aop/Aspect.scala
  core/src/main/scala/chisel3/core/package.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/Namer.scala
  core/src/main/scala/chisel3/internal/SourceInfo.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/package.scala
  macros/src/main/scala/chisel3/SourceInfoDoc.scala
  macros/src/main/scala/chisel3/internal/RangeTransform.scala
  macros/src/main/scala/chisel3/internal/RuntimeDeprecationTransform.scala
  macros/src/main/scala/chisel3/internal/naming/NamingAnnotations.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Labels: API Modification, code improvement

#1389 Bump to Scala 2.12.11
  .circleci/config.yml
  build.sbt
  build.sc
Labels: Please Merge

#1390 Add publishSettings to subprojects.
  build.sbt
Labels: Please Merge

#1367 Java API Documents Linking
  core/src/main/scala/chisel3/package.scala
  project/plugins.sbt
  src/main/scala/chisel3/util/Bitwise.scala
Labels: Please Merge

#1340 Update sbt-site to 1.3.3
  project/plugins.sbt
Labels: Please Merge

#1341 Update junit to 4.13
  build.sbt
  build.sc
Labels: Please Merge
