Repository chipsalliance/chisel, pull requests merged in 2020-08, with the labels that each got.

#1539 Update OneHot.scala
  src/main/scala/chisel3/util/OneHot.scala
Labels: Please Merge

#1546 Restore Counter.n API
  src/main/scala/chisel3/util/Counter.scala
  src/test/scala/chiselTests/Counter.scala
Labels: bugfix

#1538 Bug fix for manipulating submodules in aspects
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
Labels: Please Merge, bugfix

#1405 Switch to HowToSerialize for Emission
  src/main/scala/chisel3/Driver.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Convert.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/MuxSpec.scala
Labels: Please Merge

#1550 Deprecate Module.io and BlackBox.io
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/RawModule.scala
Labels: API Modification

#1527 Allow a counter to be manually reset
  src/main/scala/chisel3/util/Counter.scala
  src/test/scala/chiselTests/Counter.scala
Labels: API Addition, Please Merge

#1551 Deprecate support for Scala 2.11
  build.sbt
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#1553 Bump Scala to 2.12.12
  build.sbt
  build.sc
Labels: Please Merge

#1554 Move Treadle dependency to the tests
  build.sbt
  build.sc
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/test/scala/chisel3/testers/TestUtils.scala
  src/test/scala/chisel3/testers/TreadleBackend.scala
  src/test/scala/chiselTests/ChiselSpec.scala
Labels: API Modification

#1556 fix build release problem
  build.sc
Labels: Please Merge, bug

#1558 Remove use of PreservesAll, cleanup dependencies
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala
  src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala
  src/main/scala/chisel3/stage/phases/Checks.scala
  src/main/scala/chisel3/stage/phases/Convert.scala
  src/main/scala/chisel3/stage/phases/DriverCompatibility.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/chisel3/stage/phases/Emitter.scala
  src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
  src/main/scala/chisel3/stage/phases/MaybeFirrtlStage.scala
Labels: Please Merge

#1568 Relax plugin scalac phase order
  plugin/src/main/scala-2.12/chisel3/plugin/ChiselPlugin.scala
Labels: bugfix
