Repository chipsalliance/chisel, pull requests merged in 2020-04, with the labels that each got.

#1404 Use thread local storage for ChiselContext.
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Backport, Please Merge

#1402 expose typeEquivalent
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Squash and merge

#1408 Make Counter emit valid FIRRTL
  src/main/scala/chisel3/util/Counter.scala
Labels: Please Merge

#1414 Add tests for async reset regs of non-UInt types
  src/test/scala/chiselTests/AsyncResetSpec.scala
Labels: Please Merge

#1397 Mux1H: note results unspecified unless exactly one select signal is high
  src/main/scala/chisel3/util/Mux.scala
Labels: Please Merge
