Repository chipsalliance/chisel, pull requests merged in 2020-05, with the labels that each got.

#1420 README: add link to website source
  README.md
Labels: Please Merge

#1426 Fix Double Elaboration Backportably
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/phases/Emitter.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: bugfix

#1395 Update sbt-site to 1.4.0
  project/plugins.sbt
Labels: Backport, Please Merge

#1413 Update scalacheck-1-14 to 3.1.1.1
  build.sbt
  build.sc
Labels: Backport, Please Merge

#1415 Update sbt to 1.3.10
  project/build.properties
Labels: Backport, Please Merge

#1441 Scala steward+1432 - Update scalatest to 3.1.2
  build.sbt
  build.sc
Labels: Backport, Please Merge
