Repository chipsalliance/chisel, pull requests merged in 2020-12, with the labels that each got.

#1686 readme: simplify sbt snippet and update to the latest stable release
  README.md
Labels: Please Merge

#1688 Fix RegInit of Bundle lits
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
Labels: bugfix

#1670 (encore) Builder: use LazyLogging.logger.warn to print elaboration message
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
Labels: Please Merge

#1695 Make Maven show chisel3 as apache-2.0
  build.sbt
  build.sc
Labels: Please Merge, Squash and merge, release issue

#1690 Switch to using Github Actions CI
  .github/workflows/test.yml
  .mergify.yml
  build.sbt
  project/plugins.sbt
Labels: Please Merge

#1702 Remove CircleCI
  .circleci/config.yml
Labels: Please Merge

#1709 Automate publishing of SNAPSHOTS with sbt-ci-release (bp #1706)
  .github/workflows/test.yml
  build.sbt
  project/plugins.sbt
Labels: Backport

#1710 Automate publishing of SNAPSHOTS with sbt-ci-release (bp #1706)
  .github/workflows/test.yml
  build.sbt
  project/plugins.sbt
Labels: Backport
