Repository chipsalliance/chisel, pull requests merged in 2020-02, with the labels that each got.

#1285 Add method asBool to Clock.
  chiselFrontend/src/main/scala/chisel3/Clock.scala
  src/test/scala/chiselTests/Clock.scala
Labels: API Addition, feature request

#1318 Add Scaladoc about RegNext Unset/Inferred Widths
  chiselFrontend/src/main/scala/chisel3/Reg.scala
Labels: Please Merge

#1315 Emit FIRRTL andr, orr for Bits.{andR, orR}
  chiselFrontend/src/main/scala/chisel3/Bits.scala
  chiselFrontend/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/BitwiseOps.scala
Labels: API Modification

#1326 Printf: Add support for tabs, and give helpful error messages (#1323)
  chiselFrontend/src/main/scala/chisel3/Printf.scala
  src/test/scala/chiselTests/PrintableSpec.scala
Labels: Please Merge

#1136 Make Queue.irrevocable work properly in chisel3
  src/main/scala/chisel3/util/Decoupled.scala
  src/test/scala/chiselTests/QueueSpec.scala
Labels: bugfix

#1329 Clone child elements lazily in Vec
  chiselFrontend/src/main/scala/chisel3/Aggregate.scala
Labels: Please Merge

#1336 Fix := of Reset and AsyncReset to DontCare
  chiselFrontend/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/AsyncResetSpec.scala
  src/test/scala/chiselTests/ResetSpec.scala
Labels: Please Merge, bugfix

#1324 fix mill build
  .gitignore
  CommonBuild.sc
  build.sc
Labels: Squash and merge

#1345 Upcoming Events: Remove CCC, add Dev Meetings
  README.md
Labels: Please Merge

#1346 Patch fix #1109
  chiselFrontend/src/main/scala/chisel3/RawModule.scala
Labels: Please Merge, bugfix

#1365 Retain default version assignment
  build.sc
Labels: Please Merge
