Repository chipsalliance/chisel, pull requests merged in 2020-01, with the labels that each got.

#1275 Fixed problem creating Interval literals with full ranges
  chiselFrontend/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/IntervalSpec.scala
Labels: bugfix

#1303 Bugfix: Select.instances now works with blackboxes
  src/main/scala/chisel3/aop/Select.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: Please Merge

#1305 specifying type of targets field in ChiselStage
  src/main/scala/chisel3/stage/ChiselStage.scala
Labels: Please Merge

#1283 BitPat supports whitespace and underscores
  src/main/scala/chisel3/util/BitPat.scala
  src/test/scala/chiselTests/Decoder.scala
Labels: Backport, Squash and merge, bugfix

#1308 Change when/switch thunk type to Any
  chiselFrontend/src/main/scala/chisel3/When.scala
  src/main/scala/chisel3/util/Conditional.scala
Labels: Please Merge

#1284 Provides Double and BigDecimal methods to access literal values for FixedPoint and Interval
  chiselFrontend/src/main/scala/chisel3/Bits.scala
  chiselFrontend/src/main/scala/chisel3/Num.scala
  chiselFrontend/src/main/scala/chisel3/package.scala
  src/test/scala/chiselTests/FixedPointSpec.scala
  src/test/scala/chiselTests/IntervalSpec.scala
  src/test/scala/chiselTests/LiteralExtractorSpec.scala
Labels: API Addition, code improvement, usability

#1296 Remove redundancy code
  chiselFrontend/src/main/scala/chisel3/RawModule.scala
Labels: Please Merge

#1294 Fixed code example typo in comment
  chiselFrontend/src/main/scala/chisel3/Aggregate.scala
  chiselFrontend/src/main/scala/chisel3/Reg.scala
Labels: Please Merge
