Repository chipsalliance/chisel, pull requests merged in 2020-10, with the labels that each got.

#1601 Move more docs
  docs/src/explanations/annotations.md
  docs/src/explanations/blackboxes.md
  docs/src/explanations/bundles-and-vecs.md
Labels: Please Merge

#1612 Update junit to 4.13.1
  build.sbt
  build.sc
Labels: Please Merge

#1614 When prefixing with a data, eagly get local name
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/prefix.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
Labels: Please Merge

#1618 Provide user source locators in Builder.error errors
  core/src/main/scala/chisel3/internal/Error.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
Labels: Please Merge, bugfix

#1623 Enable Cat of Zero Element Vec
  core/src/main/scala/chisel3/SeqUtils.scala
  src/main/scala/chisel3/util/Cat.scala
  src/test/scala/chiselTests/util/CatSpec.scala
Labels: Please Merge

#1617 Change prefix stack to List[String]
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#1630 Make `-e` option work with ChiselStage methods
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: Please Merge, bugfix

#1613 Delete index.md
  docs/src/wiki-deprecated/index.md
Labels: Please Merge

#1611 Fixed broken link to type hierarchy diagram
  README.md
Labels: Please Merge

#1634 Added Force Name API
  docs/src/cookbooks/naming.md
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/test/scala/chiselTests/experimental/ForceNames.scala
Labels: API Addition, Please Merge

#1635 Bugfix - module name collision for injecting aspect
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
Labels: Please Merge, bugfix

#1640 Fix crosslinks in mdoc. Can't use md suffix
  docs/src/cookbooks/naming.md
  docs/src/explanations/blackboxes.md
  docs/src/explanations/bundles-and-vecs.md
  docs/src/explanations/naming.md
  docs/src/wiki-deprecated/chisel3-vs-chisel2.md
  docs/src/wiki-deprecated/cookbook.md
  docs/src/wiki-deprecated/data-types.md
  docs/src/wiki-deprecated/developers.md
  docs/src/wiki-deprecated/faqs.md
  docs/src/wiki-deprecated/memories.md
  docs/src/wiki-deprecated/reset.md
  docs/src/wiki-deprecated/supported-hardware.md
Labels: Please Merge

#1645 Fix bug where refs may not get set for Records
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
Labels: bugfix
