Repository chipsalliance/chisel, pull requests merged in 2021-09, with the labels that each got.

#2045 Instance/Definition (formerly Template)
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/IsInstantiable.scala
  core/src/main/scala/chisel3/experimental/hierarchy/IsLookupable.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
  core/src/main/scala/chisel3/experimental/hierarchy/package.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  docs/src/cookbooks/hierarchy.md
  macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
  src/test/scala/chiselTests/experimental/DataView.scala
  src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Annotations.scala
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Utils.scala
Labels: API Addition

#2091 Update sbt-mdoc to 2.2.23
  project/plugins.sbt
Labels: Please Merge

#2086 Update sbt-mima-plugin to 1.0.0
  project/plugins.sbt
Labels: Please Merge

#1950 Update scala-compiler, scala-library, ... to 2.12.14
  .github/workflows/test.yml
  build.sbt
  build.sc
Labels: Please Merge

#2121 Fix higher-kinded types for autoclonetype
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: bugfix, Please Merge

#2077 Signal Trace API
  core/src/main/scala/chisel3/experimental/Trace.scala
  src/test/scala/chiselTests/experimental/TraceSpec.scala
Labels: Please Merge

#2127 Update sbt-scalafix to 0.9.31
  project/plugins.sbt
Labels: Please Merge

#2132 Revert default scala version to 2.12 for 3.5 release.
  build.sbt
Labels: Please Merge

#2089 graduate new assert/assume/cover statements from experimental into the chisel3 namespace
  core/src/main/scala/chisel3/Assert.scala
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/experimental/verification/package.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/experimental/verification/package.scala
  src/main/scala/chisel3/testers/BasicTester.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: Please Merge

#2135 verification: fix off by one error in deprecation message
  src/main/scala/chisel3/experimental/verification/package.scala
Labels: Please Merge
