Repository chipsalliance/chisel, pull requests merged in 2021-01, with the labels that each got.

#1716 Update meeting url
  README.md
Labels: Please Merge

#1714 Make `toTarget` fail if called on a Literal (or would otherwise not serialize properly)
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/LiteralToTargetSpec.scala
Labels: Please Merge, bugfix

#1732 Farewell Scala 2.11
  .github/workflows/test.yml
  build.sbt
  build.sc
Labels: code improvement

#1744 remove 2.11 dedicated code.
  core/src/main/scala/chisel3/Aggregate.scala
Labels: Please Merge

#1745 Remove "val io" and rename MultiIOModule to Module
  build.sbt
  build.sc
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/core/package.scala
  core/src/main/scala/chisel3/package.scala
  docs/src/cookbooks/naming.md
  docs/src/explanations/naming.md
  docs/src/wiki-deprecated/cookbook.md
  docs/src/wiki-deprecated/modules.md
  docs/src/wiki-deprecated/ports.md
  docs/src/wiki-deprecated/reset.md
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/test/scala/chiselTests/AnalogIntegrationSpec.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
  src/test/scala/chiselTests/BlackBox.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/CloneModuleSpec.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
  src/test/scala/chiselTests/DataPrint.scala
  src/test/scala/chiselTests/Direction.scala
  src/test/scala/chiselTests/DriverSpec.scala
  src/test/scala/chiselTests/Module.scala
  src/test/scala/chiselTests/MultiIOModule.scala
  src/test/scala/chiselTests/NamingAnnotationTest.scala
  src/test/scala/chiselTests/QueueSpec.scala
  src/test/scala/chiselTests/ResetSpec.scala
  src/test/scala/chiselTests/StrongEnum.scala
  src/test/scala/chiselTests/Util.scala
  src/test/scala/chiselTests/experimental/ForceNames.scala
  src/test/scala/chiselTests/experimental/ProgrammaticPortsSpec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
  src/test/scala/chiselTests/util/CatSpec.scala
Labels: Merge with merge commit

#1756 Fix incorrect comment in ScalaDoc
  core/src/main/scala/chisel3/Reg.scala
Labels: Please Merge, release issue

#1755 Fix some typo and using foreach instead of map in BoringUtils
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
Labels: Please Merge
