Repository chipsalliance/chisel, pull requests merged in 2021-07, with the labels that each got.

#1992 have printf return BaseSim subclass so it can be named/annotated
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/experimental/verification/package.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/internal/firrtl/Emitter.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: DO NOT MERGE

#2015 Update docs on dontTouch as optimization barrier
  core/src/main/scala/chisel3/dontTouch.scala
Labels: Please Merge

#1966 Add `isOneOf` method to `ChiselEnum`
  core/src/main/scala/chisel3/StrongEnum.scala
  docs/src/explanations/chisel-enum.md
  src/test/scala/chiselTests/StrongEnum.scala
Labels: Please Merge

#2023 Fix chisel3 <> for Bundles that contain compatibility Bundles
  core/src/main/scala/chisel3/internal/BiConnect.scala
  src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
Labels: bugfix

#2018 Make it legal for concrete resets to drive abstract reset
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/ResetSpec.scala
Labels: bugfix

#2041 Fix CI.
  .github/workflows/test.yml
Labels: Please Merge

#2047 Update sbt-mdoc to 2.2.22
  project/plugins.sbt
Labels: Please Merge

#2046 Bundles can no longer be instantiated with bound hardware
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/BundleSpec.scala
Labels: API Modification
