Repository chipsalliance/chisel, pull requests merged in 2021-02, with the labels that each got.

#1766 Bump to Scala 2.12.13
  .github/workflows/test.yml
  build.sbt
  build.sc
  project/plugins.sbt
Labels: release issue

#1748 Update reported width from div/rem to match FIRRTL results
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
  src/test/scala/chiselTests/WidthSpec.scala
Labels: Please Merge, bugfix

#1767 Bump to Scala 2.12.13 (bp #1766)
  .github/workflows/test.yml
  build.sbt
  build.sc
  project/plugins.sbt
Labels: Backport, release issue

#1776 Add file line to source link from scaladoc
  build.sbt
Labels: Please Merge

#1740 Parametrized Mem- & SyncReadMem-based implementation of the Queue class
  src/main/scala/chisel3/util/Decoupled.scala
  src/test/scala/chiselTests/QueueSpec.scala
Labels: Please Merge

#1785 Make Data GC-able (bp #1624)
  .github/workflows/test.yml
  build.sbt
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  no-plugin-tests/src/test/scala/chisel3/testers/TestUtils.scala
  no-plugin-tests/src/test/scala/chiselTests/ChiselSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/InstanceNameSpec.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
Labels: Backport

#1771 Fix stack trace trimming across Driver/ChiselStage
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/internal/Error.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#1773 Dev/seldridge/issue 1763 3.4.x
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/internal/Error.scala
  src/main/scala/chisel3/Driver.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/ChiselTestUtilitiesSpec.scala
  src/test/scala/chiselTests/DriverSpec.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: Backport, Please Merge

#1789 Aggregate: fix typo
  core/src/main/scala/chisel3/Aggregate.scala
Labels: Please Merge, Squash and merge, code improvement, usability
