Repository chipsalliance/chisel, pull requests merged in 2021-10, with the labels that each got.

#2141 Fix typos in documentation
  docs/src/explanations/functional-abstraction.md
  docs/src/explanations/modules.md
Labels: Squash and merge

#2140 Update scalatest to 3.2.10
  build.sbt
  build.sc
Labels: Please Merge

#2139 Update sbt-ci-release to 1.5.9
  project/plugins.sbt
Labels: Please Merge

#2147 Remove workaround for fixed issue in mdoc crash blocks
  docs/src/explanations/dataview.md
Labels: Please Merge

#2149 Remove v3.4.0 version of autoNameRecursively
  core/src/main/scala/chisel3/internal/plugin/package.scala
Labels: API Modification

#2052 Remove all Bundle cloneTypes and chiselRuntimeDeprecate its use
  core/src/main/scala/chisel3/Aggregate.scala
  docs/src/explanations/bundles-and-vecs.md
  no-plugin-tests/src/test/scala/chiselTests/NoPluginBundleSpec.scala
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/main/scala/chisel3/util/Enum.scala
  src/main/scala/chisel3/util/Valid.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
  src/test/scala/chiselTests/BundleSpec.scala
  src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
  src/test/scala/chiselTests/CompileOptionsTest.scala
  src/test/scala/chiselTests/ComplexAssign.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: API Modification

#2124 Deprecate auto-application of empty argument lists to parameterless functions
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/Num.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/SeqUtils.scala
  core/src/main/scala/chisel3/StrongEnum.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/prefix.scala
  core/src/main/scala/chisel3/package.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/StrongEnum.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: Please Merge

#1140 Circular-shift (rotate) operations for UInt
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Please Merge
