Repository chipsalliance/chisel, pull requests merged in 2021-03, with the labels that each got.

#1781 Fix conversions between DecoupledIO and IrrevocableIO
  src/main/scala/chisel3/util/Decoupled.scala
Labels: Please Merge

#1795 Adding ChiselEnum Documentation Entry
  docs/src/explanations/chisel-enum.md
Labels: Please Merge

#1800 Add header for chisel-enum.md
  docs/src/explanations/chisel-enum.md
Labels: Please Merge

#1805 Import memory files inline for Verilog generation
  .gitignore
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
Labels: API Addition, Please Merge

#1811 allowReflectiveAutoCloneType must work outside of Builder context
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: bugfix

#1817 Fix incorrect usage of emitFirrtl in test
  src/test/scala/chiselTests/experimental/verification/VerificationSpec.scala
Labels: Please Merge

#1819 Add toString method to BitPat
  src/main/scala/chisel3/util/BitPat.scala
  src/test/scala/chiselTests/util/BitPatSpec.scala
Labels: Please Merge

#1826 Make plugin autoclonetype always on
  build.sbt
  plugin/src/main/scala-2.12/chisel3/internal/plugin/ChiselPlugin.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: Please Merge

#1794 CCC 2021 placeholder
  README.md
Labels: Please Merge

#1838 Provide useful message on Vec.apply require
  core/src/main/scala/chisel3/Aggregate.scala
Labels: Please Merge
