Repository chipsalliance/chisel, pull requests merged in 2021-12, with the labels that each got.

#2269 Remove unused imports for API removed from firrtl
  src/test/scala/chiselTests/BlackBoxImpl.scala
  src/test/scala/chiselTests/InlineSpec.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
  src/test/scala/chiselTests/TransitNameSpec.scala
Labels: Please Merge

#2249 Bugfix - definition name index skipping with D/I
  core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Please Merge

#2270 Update REAMDE instructions for building projects
  README.md
Labels: Please Merge

#2271 Require the chisel3 compiler plugin
  .github/workflows/test.yml
  README.md
  build.sbt
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  no-plugin-tests/src/test/scala/chisel3/testers/TestUtils.scala
  no-plugin-tests/src/test/scala/chiselTests/AutoClonetypeSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/AutoNestedCloneSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/BetterNamingTests.scala
  no-plugin-tests/src/test/scala/chiselTests/CatSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/ChiselSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/CustomBundle.scala
  no-plugin-tests/src/test/scala/chiselTests/InstanceNameSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/MissingCloneBindingExceptionSpec.scala
  no-plugin-tests/src/test/scala/chiselTests/NamingAnnotationTest.scala
  no-plugin-tests/src/test/scala/chiselTests/NoPluginBundleSpec.scala
  src/test/scala/chisel3/testers/TestUtils.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
  src/test/scala/chiselTests/AutoNestedCloneSpec.scala
Labels: API Modification

#2197 Add Data string accessor
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/StrongEnum.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/DataPrint.scala
Labels: Please Merge

#2290 [docs] Remove body from minimizing output bits recipe
  docs/src/cookbooks/cookbook.md
Labels: Please Merge

#2277 Implement DataViews for Seq and Tuple
  core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/package.scala
  docs/src/explanations/dataview.md
  src/main/scala/chisel3/experimental/conversions/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
  src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
  src/test/scala/chiselTests/experimental/Tuple.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: API Addition

#2293 [docs] Update versioning appendix to include 3.5
  docs/src/appendix/versioning.md
Labels: Please Merge

#2276 catch None.get in BitPat.apply(x: UInt): BitPat
  src/main/scala/chisel3/util/BitPat.scala
  src/test/scala/chiselTests/util/BitPatSpec.scala
Labels: Please Merge

#2248 Better MonoConnect error messages
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/ConnectSpec.scala
  src/test/scala/chiselTests/InvalidateAPISpec.scala
Labels: Please Merge

#2292 reduceTree() now operates on Seq
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/Vec.scala
Labels: Please Merge

#2301 Update os-lib to 0.8.0
  build.sbt
  build.sc
Labels: Please Merge

#2300 Update sbt to 1.5.6
  project/build.properties
Labels: Please Merge

#2274 Make stuff in IR.scala package private
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
Labels: Please Merge

#2284 deprecate getModulePorts
  core/src/main/scala/chisel3/package.scala
Labels: Please Merge

#2217 Refactor TruthTable to use Seq.
  integration-tests/src/test/scala/chiselTests/util/experimental/DecoderSpec.scala
  integration-tests/src/test/scala/chiselTests/util/experimental/minimizer/MinimizerSpec.scala
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/experimental/decode/EspressoMinimizer.scala
  src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
  src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
  src/main/scala/chisel3/util/experimental/decode/decoder.scala
  src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
Labels: Please Merge

#2303 Update sbt to 1.5.7
  project/build.properties
Labels: Please Merge

#2275 Add "Upgrading From Chisel 3.4 to 3.5"
  docs/src/appendix/appendix.md
  docs/src/appendix/upgrading-from-chisel-3-4.md
  docs/src/appendix/upgrading-from-scala-2-11.md
Labels: Please Merge

#2302 Restore Port to public API and deprecate
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/Module.scala
Labels: Please Merge

#2211 BitSet API
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/experimental/decode/decoder.scala
  src/test/scala/chiselTests/util/BitPatSpec.scala
  src/test/scala/chiselTests/util/BitSetSpec.scala
Labels: Please Merge

#2304 Improve exception message for aliased bundle fields
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/BundleSpec.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: code improvement, Please Merge

#2308 Revert "Make stuff in IR.scala package private (#2274)"
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
Labels: Please Merge

#2312 Better documentation for := and <>
  docs/src/explanations/connection-operators.md
  docs/src/explanations/explanations.md
  docs/src/explanations/interfaces-and-connections.md
  docs/src/images/chisel_01.png
Labels: Please Merge

#2317 Update README shield to include RCs
  README.md
Labels: Please Merge
