Repository chipsalliance/chisel, pull requests merged in 2021-04, with the labels that each got.

#1848 Fix Gitter chat room link
  README.md
Labels: Please Merge

#1850 Add documentation guide about memory initialization
  docs/src/appendix/experimental-features.md
  docs/src/explanations/memories.md
Labels: Please Merge

#1861 update CCC2021 info
  README.md
Labels: Please Merge

#1874 Fixing aspect injection context bug
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
Labels: Please Merge, bugfix

#1881 Cleanup some Cookbook Examples
  docs/src/cookbooks/cookbook.md
Labels: Please Merge

#1834 Introduce VecLiterals
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  docs/src/appendix/experimental-features.md
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: API Addition

#1886 Cookbook: clean up desiredName example
  docs/src/cookbooks/cookbook.md
Labels: Please Merge

#1887 Update sbt-scoverage to 1.7.0
  project/plugins.sbt
Labels: Please Merge

#1815 Update scopt to 4.0.1
  build.sbt
  build.sc
Labels: Please Merge

#1842 Update sbt-scalafix to 0.9.27
  project/plugins.sbt
Labels: Please Merge

#1870 Update sbt-mdoc to 2.2.20
  project/plugins.sbt
Labels: Please Merge

#1832 Update sbt-ci-release to 1.5.7
  project/plugins.sbt
Labels: Please Merge

#1891 verification: guard statements with module reset
  core/src/main/scala/chisel3/experimental/verification/package.scala
  src/test/scala/chiselTests/experimental/verification/VerificationSpec.scala
Labels: Please Merge

#1751 Scala 2.13
  .github/workflows/test.yml
  build.sbt
  core/src/main/scala-2.12/scala/collection/immutable/package.scala
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/Num.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  core/src/main/scala/chisel3/internal/Namer.scala
  core/src/main/scala/chisel3/package.scala
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselPlugin.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/MixedVec.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/ExtModule.scala
  src/test/scala/examples/VendingMachineUtils.scala
Labels: Please Merge

#1854 add helper function to convert chirrtl to firrtl.
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: Please Merge
