Repository chipsalliance/chisel, pull requests merged in 2022-08, with the labels that each got.

#2653 Remove Tuesday from Dev Meeting in README
  README.md
Labels: Please Merge

#2635 Remove remaining chiselNames
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/Decoupled.scala
Labels: Please Merge

#2655 Fix formatting issue in chisel-type-vs-scala-type.md
  docs/src/explanations/chisel-type-vs-scala-type.md
Labels: Please Merge

#2477 git-subtree add sifive/chisel-circt
  .github/workflows/test.yml
  src/main/scala/circt/Implicits.scala
  src/main/scala/circt/stage/Annotations.scala
  src/main/scala/circt/stage/CIRCTOptions.scala
  src/main/scala/circt/stage/CIRCTStage.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/package.scala
  src/main/scala/circt/stage/phases/AddDefaults.scala
  src/main/scala/circt/stage/phases/AddFIRRTLInputFile.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/main/scala/circt/stage/phases/Checks.scala
  src/main/scala/circt/stage/phases/MaybeSFC.scala
  src/test/scala/circtTests/stage/CIRCTStageSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Merge with merge commit

#2658 Replace some options with nullable vars
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#2665 stdlibL: fix folders in test source
  integration-tests/src/test/scala/chisel3/std/BarrelShifter.scala
Labels: Please Merge

#2671 Add ability to suppress enum cast warnings
  core/src/main/scala/chisel3/StrongEnum.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  docs/src/explanations/chisel-enum.md
  src/test/scala/chiselTests/StrongEnum.scala
Labels: Please Merge

#2673 Show equivalent warnings/errors only once
  core/src/main/scala/chisel3/internal/Error.scala
  src/test/scala/chiselTests/WarningSpec.scala
Labels: Please Merge

#2662 Add OpaqueType support to Records
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Please Merge

#2663 Printables for verification preconditions
  core/src/main/scala/chisel3/VerificationStatement.scala
  src/test/scala/chiselTests/Assert.scala
Labels: Please Merge

#2684 Update RecordSpec test
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Please Merge

#2669 Add recursive `Bundle` and generic `Data` equality (===)
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/DataEqualitySpec.scala
Labels: Please Merge

#2696 Provide a better error message for use of .toTarget on non-hardware value
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
Labels: Please Merge

#2701 Bugfix - OpaqueSlot replace invalid localName
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Please Merge

#2700 Eagerly throw error if certain annotations are used on non-hardware types
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/main/scala/chisel3/util/experimental/decode/decoder.scala
  src/test/scala/chiselTests/experimental/ForceNames.scala
Labels: Please Merge

#2704 Fix CloneTypes in RecordSpec
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Please Merge

#2714 Wires should have source location information in firrtl
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/WireSpec.scala
Labels: usability, Please Merge
