Repository chipsalliance/chisel, pull requests merged in 2022-02, with the labels that each got.

#2376 Improve error reporting
  core/src/main/scala/chisel3/experimental/hierarchy/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselCli.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#2306 Chisel plugin bundle elements handler
  build.sbt
  build.sc
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  plugin/README.md
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselPlugin.scala
  src/test/scala/chiselTests/BundleElementsSpec.scala
  src/test/scala/chiselTests/BundleSpec.scala
Labels: code improvement, release issue, Challenge Issue, Please Merge

#2333 Optional clock param for memory ports
  core/src/main/scala/chisel3/Mem.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/test/scala/chiselTests/MultiClockSpec.scala
Labels: Please Merge

#2385 Add Scala 2.13.8 to plugin cross-compilation
  build.sbt
Labels: release issue, Please Merge

#2389 Tweak new mem port clock warnings
  core/src/main/scala/chisel3/Mem.scala
Labels: release issue, Please Merge

#2390 Tweak Bundle._elementsImpl
  core/src/main/scala/chisel3/Aggregate.scala
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
Labels: Please Merge

#2396 Fix bundle elements performance regression
  core/src/main/scala/chisel3/Aggregate.scala
Labels: release issue

#2397 Fix variable-name typo
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#2372 Make Tuple2 Lookupable
  core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Please Merge

#2411 Migrate build.sbt to slash syntax
  build.sbt
Labels: Please Merge

#2387 Make truthtable being able to accept unknown input width.
  src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
  src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
Labels: Please Merge
