Repository chipsalliance/chisel, pull requests merged in 2022-04, with the labels that each got.

#2468 Prevent FIRRTL bulk connects on BlackBox Bundles.
  core/src/main/scala/chisel3/internal/BiConnect.scala
  src/test/scala/chiselTests/BulkConnectSpec.scala
Labels: Please Merge

#2472 Micro-optimize String building in _computeName
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#2476 Enhance views to [sometimes] support dynamic indexing and implement FlatIO
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Lookupable.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  docs/src/cookbooks/cookbook.md
  src/test/scala/chiselTests/experimental/DataView.scala
  src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
  src/test/scala/chiselTests/experimental/FlatIOSpec.scala
Labels: API Addition

#2471 Optimize memory use of naming prefixes
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Please Merge

#2485 Enable Clock Invalidation
  core/src/main/scala/chisel3/Clock.scala
  src/test/scala/chiselTests/InvalidateAPISpec.scala
Labels: Please Merge

#2490 Fix small typos in doc comment
  core/src/main/scala/chisel3/Bits.scala
Labels: Please Merge

#2484 verification: switch order of assert/assume and printf
  core/src/main/scala/chisel3/VerificationStatement.scala
Labels: bugfix, Please Merge

#2494 mem: allow creating memories without an implicit clock
  core/src/main/scala/chisel3/Mem.scala
  src/test/scala/chiselTests/Mem.scala
Labels: bugfix

#2478 Update sbt-mima-plugin to 1.1.0
  project/plugins.sbt
Labels: Please Merge

#2462 Update sbt-mdoc to 2.3.2
  project/plugins.sbt
Labels: Please Merge

#2452 Update sbt-api-mappings to 3.0.2
  project/plugins.sbt
Labels: Please Merge

#2498 add comments for LockingRRArbiter.lastGrant
  src/main/scala/chisel3/util/Arbiter.scala
Labels: Please Merge

#2318 Generate a balanced tree with reduceTree
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/ReduceTreeSpec.scala
Labels: Please Merge

#2501 fix plugin while building with mill.
  build.sc
Labels: Please Merge

#2506 Fix spurious warning from Bundle plugin
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
Labels: Please Merge

#2502 Update scalatest to 3.2.12
  build.sbt
  build.sc
Labels: Please Merge

#2511 remove experimental.verification package
  integration-tests/src/test/scala/chiselTest/MemFormalSpec.scala
  integration-tests/src/test/scala/chiselTests/util/experimental/minimizer/MinimizerSpec.scala
  src/main/scala/chisel3/experimental/verification/package.scala
  src/test/scala/chiselTests/VerificationSpec.scala
Labels: Please Merge
