Repository chipsalliance/chisel, pull requests merged in 2022-06, with the labels that each got.

#2528 Add formatted Printable interpolator `cf`
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/package.scala
  src/test/scala/chiselTests/PrintableSpec.scala
Labels: API Addition, Please Merge

#2555 Support VerificationStatement in the naming plugin
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
Labels: bugfix, Please Merge

#2534 Deprecate implicit .U() and .S() syntax for literal bit extracts
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/package.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Please Merge

#2562 Remove reflective naming
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselCli.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/BetterNamingTests.scala
  src/test/scala/chiselTests/InstanceNameSpec.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
  src/test/scala/chiselTests/naming/ReflectiveNamingSpec.scala
Labels: API Modification

#2566 Add single argument Bits.extract
  core/src/main/scala/chisel3/Bits.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Please Merge

#2571 Added migration for inferModuleReset
  core/src/main/scala/chisel3/CompileOptions.scala
  core/src/main/scala/chisel3/Module.scala
  src/test/scala/chiselTests/MigrateCompileOptionsSpec.scala
Labels: Please Merge

#2574 Add ProcessLogger to TesterDriver for less test noise
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/test/scala/chisel3/testers/TreadleBackend.scala
Labels: Please Merge

#2577 Micro-optimize and memoize BitPat.rawString
  src/main/scala/chisel3/util/BitPat.scala
Labels: Please Merge

#2582 [docs] Document partial register reset
  docs/src/appendix/experimental-features.md
  docs/src/cookbooks/cookbook.md
Labels: Documentation

#2585 Handle varargs constructor arguments in Bundle plugin
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: bugfix, Please Merge

#2586 Make readme friendlier to beginners
  README.md
Labels: Please Merge, Documentation

#2596 README: fix link to contributing.md
  README.md
Labels: Please Merge

#2601 Add DataMirror isIO, isReg, isWire
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/experimental/DataMirrorSpec.scala
Labels: Please Merge

#2607 Fix broken link in interfaces-and-connections.md
  docs/src/explanations/interfaces-and-connections.md
Labels: Please Merge

#2237 Update Issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Please Merge

#2609 Fixup for ISSUE_TEMPLATE: use kebab case and add metadata
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Please Merge
