Repository chipsalliance/chisel, pull requests merged in 2022-10, with the labels that each got.

#2707 Update toPrintable for Enums
  core/src/main/scala/chisel3/StrongEnum.scala
  src/test/scala/chiselTests/StrongEnum.scala
Labels: Please Merge

#2761 Make nested IsInstantiables with Data in them work
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: bugfix, Please Merge

#2765 Fix traceName module type to RawModule
  core/src/main/scala/chisel3/experimental/Trace.scala
Labels: Please Merge

#2772 Remove "don't touch" behavior from Trace API
  core/src/main/scala/chisel3/experimental/Trace.scala
  src/test/scala/chiselTests/experimental/TraceSpec.scala
Labels: Please Merge

#2781 Add opt-in AutoCloneType for Records
  core/src/main/scala/chisel3/Aggregate.scala
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/main/scala/chisel3/util/MixedVec.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: API Addition

#2801 Fix for <> to BlackBox.IO with Compatibility Bundles
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/BulkConnectSpec.scala
  src/test/scala/chiselTests/CompatibilityInteroperabilitySpec.scala
Labels: Please Merge
