Repository chipsalliance/chisel, pull requests merged in 2022-09, with the labels that each got.

#2721 Remove incorrect clock warning on Mem.read
  core/src/main/scala/chisel3/Mem.scala
  src/test/scala/chiselTests/MultiClockSpec.scala
Labels: Please Merge

#2723 Add source locators to ports
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/Module.scala
  src/test/scala/chiselTests/PortSpec.scala
Labels: code improvement

#2715 Add ChiselSubtypeOf for structural subtyping
  core/src/main/scala/chisel3/experimental/dataview/ChiselSubtypeOf.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Please Merge

#2741 Use new lazy serialization in FIRRTL
  src/main/scala/chisel3/internal/firrtl/Emitter.scala
Labels: Please Merge

#2694 Remove @chiselName and NoChiselNamePrefix
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Namer.scala
  macros/src/main/scala/chisel3/internal/naming/NamingAnnotations.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/compatibility.scala
  src/test/scala/chiselTests/NamedModuleTester.scala
  src/test/scala/chiselTests/NamingAnnotationTest.scala
Labels: Please Merge

#2731 Always show BlackBox parameters in alphabetical key order
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  src/test/scala/chiselTests/BlackBox.scala
Labels: usability, Please Merge

#2751 Error on S-interpolator usage for assert, assume and printf
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  docs/src/explanations/printing.md
  src/test/scala/chiselTests/IntervalSpec.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: Please Merge

#2752 Cookbooks: use more mdoc power, fix issues
  docs/src/cookbooks/cookbook.md
Labels: Please Merge
