Repository chipsalliance/chisel, pull requests merged in 2023-12, with the labels that each got.

#3673 Fix spelling error in Layers documentation layers.md
  docs/src/explanations/layers.md
Labels: Documentation

#3676 Make Property an Element.
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/properties/Property.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Internal

#3675 dontTouch should default to leaf marking rather than aggregate marking to match current behavior
  core/src/main/scala/chisel3/dontTouch.scala
  src/test/scala/chiselTests/DontTouchSpec.scala
Labels: Feature

#3680 don't Touch without options
  core/src/main/scala/chisel3/dontTouch.scala
  src/test/scala/chiselTests/DontTouchSpec.scala
Labels: No Release Notes

#3685 Define typeEquivalent specially for Property.
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Bugfix

#3686 [docs] Fix release ordering and make RC count as latest
  project/Releases.scala
  project/Version.scala
Labels: Documentation

#3458 Switch to firtool-resolver
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  build.sbt
  build.sc
  common.sc
  project/FirtoolVersion.scala
  project/plugins.sbt
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/main/scala/circt/stage/phases/ScribeInterop.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: API Modification

#3670 [docs] update firtool version
  SETUP.md
Labels: Documentation

#3691 dontTouch: Skip probe and properties.
  core/src/main/scala/chisel3/dontTouch.scala
  src/test/scala/chiselTests/DontTouchSpec.scala
Labels: Bugfix

#3692 fix up path issue in build.sc
  build.sc
Labels: Internal

#3694 [docs] Add Firtool versions table to Versioning page
  .github/workflows/test.yml
  build.sbt
  docs/src/appendix/versioning.md
  project/FirtoolVersionsTable.scala
Labels: Documentation

#3695 Fix publish
  .github/workflows/ci.yml
Labels: Internal

#3696 Bump firtool-resolver to 1.1.0
  build.sbt
Labels: Dependency Update

#3697 [docs] Fix links from ScalaDoc to source code
  build.sbt
Labels: Documentation

#3701 [CI] Fix flaky CI and remove VerilogMdocModifier from API docs
  .github/workflows/test.yml
  build.sbt
Labels: Internal
