Repository chipsalliance/chisel, pull requests merged in 2023-09, with the labels that each got.

#3518 Map Properties now support Properties as the key
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3516 make PropertyType public, add Path factory method
  core/src/main/scala/chisel3/properties/Path.scala
  core/src/main/scala/chisel3/properties/Property.scala
  project/Boilerplate.scala
Labels: Feature

#3517 firrtl: Emit under 3.2.0 (not released) to cover property features.
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Backend Code Generation

#3522 Add `AnyRef` type and rework `PropertyType.getPropertyType`
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Object.scala
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  project/Boilerplate.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3524 [website] Fix link from Warnings to Cookbook
  docs/src/cookbooks/cookbook.md
  docs/src/explanations/warnings.md
  website/Makefile
Labels: Documentation

#3445 Implement FIRRTL type alias mechanism for Bundles
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/experimental/HasTypeAlias.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  docs/src/cookbooks/naming.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/test/scala/chiselTests/TypeAliasSpec.scala
Labels: Feature

#3525 Fix HasTypeAlias cookbook typos
  docs/src/cookbooks/naming.md
Labels: Documentation

#3527 Add support for Scala 2.13.12 to the compiler plugin
  build.sbt
Labels: Dependency Update

#3531 Bump to Scala 2.13.12
  .github/workflows/build-scala-cli-template/chisel-template.scala
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  build.sbt
  build.sc
Labels: Dependency Update

#3504 Implement auto typeName generation for Records
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/experimental/HasAutoTypename.scala
  docs/src/cookbooks/naming.md
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselUtils.scala
  src/test/scala/chiselTests/experimental/AutoTypenameSpec.scala
Labels: Feature

#3536 Improve error messages involving views
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Bugfix

#3538 Make FlatIO work (as IO) for non-Record Data
  core/src/main/scala/chisel3/experimental/package.scala
  src/test/scala/chiselTests/experimental/FlatIOSpec.scala
Labels: Feature

#3539 MixedVec subclasses immutable.IndexedSeq
  integration-tests/src/test/scala/chiselTest/MixedVecIntegrationSpec.scala
  src/main/scala/chisel3/util/MixedVec.scala
  src/test/scala/chiselTests/MixedVecSpec.scala
Labels: API Modification

#3540 Add unit test demonstrating BoringUtils.tap with D/I
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Documentation

#3544 [Binder] Corrent `chirrtl.memoryport` position
  binder/src/main/scala/PanamaCIRCT.scala
  binder/src/main/scala/PanamaCIRCTConverter.scala
  common.sc
Labels: Bugfix

#3547 Changed Array to Seq in MuxLookup explantation
  docs/src/explanations/muxes-and-input-selection.md
Labels: Documentation

#3553 Fix DataMirror.internal.chiselTypeClone to preserve Scala type
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Bugfix

#3558 Partial fix for probe and Decoupled interaction + demo of workaround
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#3559 Bump emitted FIRRTL to 3.3.0
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: No Release Notes

#3533 Fix 'Malformed class name' errors in typeName and related implementations
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/experimental/HasAutoTypename.scala
  core/src/main/scala/chisel3/util/Naming.scala
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/main/scala/chisel3/util/Valid.scala
Labels: Bugfix

#3541 Add optional group API
  core/src/main/scala/chisel3/Group.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/util/GroupSpec.scala
Labels: Feature
