Repository chipsalliance/chisel, pull requests merged in 2023-10, with the labels that each got.

#3560 Fix and test probe of ChiselEnum.
  core/src/main/scala/chisel3/ChiselEnum.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Bugfix

#3568 [docs] Switch API docs hosting from javadoc.io to sonatype
  website/docs/src/main/tut/api/chisel/5.0/index.md
  website/docs/src/main/tut/api/chisel/6.0/index.md
  website/docs/src/main/tut/api/chisel/latest/index.md
  website/docs/src/main/tut/api/chisel3/3.5/index.md
  website/docs/src/main/tut/api/chisel3/3.6/index.md
Labels: Documentation

#2891 Enrich ShiftRegister with SyncReadMem-based implementation.
  integration-tests/src/test/scala/chiselTest/ShiftRegisterMemSpec.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/util/Reg.scala
  src/test/scala/chiselTests/util/RegSpec.scala
Labels: Feature

#3545 Add DedupGroupAnnotation phase
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/chiselTests/DedupSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature

#3520 Implement Verilog output stream `PanamaCIRCTConverter`
  .github/workflows/install-jextract/action.yml
  .github/workflows/test.yml
  binder/jextract-headers.h
  binder/src/main/scala/PanamaCIRCT.scala
  binder/src/main/scala/PanamaCIRCTConverter.scala
  binder/src/test/scala/BinderSpec.scala
  build.sc
  common.sc
  core/src/main/scala/chisel3/internal/CIRCTConverter.scala
Labels: Please Merge, Internal

#3512 Fix BoringUtils.bore can not bore from a Probe
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Bugfix, Please Merge

#3050 Add Nix Flake
  flake.lock
  flake.nix
  nix/espresso.nix
  overlay.nix
Labels: Internal

#3563 Fix Decodetable
  src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala
  src/test/scala/chiselTests/util/experimental/DecoderTableSpec.scala
Labels: Bugfix, Please Merge

#3566 Support probe-define in monoconnects
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  docs/src/explanations/connectable.md
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Feature

#3585 [cd] Switch CD to use circt/update-circt Action
  .github/workflows/cd-circt.yml
  .github/workflows/cd-circt/commit-message.md
  .github/workflows/cd-circt/pr-body.md
  .github/workflows/cd-circt/pr-title.md
Labels: No Release Notes

#3586 [ci] Bump install-circt to v1.1.1
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: No Release Notes

#3581 Add new target API to get a target relative to a specific BaseModule.
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chisel3/internal/NameCollisionSpec.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
  src/test/scala/chiselTests/experimental/DataViewTargetSpec.scala
Labels: Feature

#3590 Don't add DedupGroupAnnotation to intrinsics
  src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
  src/test/scala/chiselTests/DedupSpec.scala
Labels: Bugfix

#3592 Support wire-of-probe.
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Feature

#3588 [ci] Switch to upstream circt/update-staging-branch
  .github/workflows/ci-circt-nightly.yml
Labels: No Release Notes

#3595 move panama codegen to txt files
  binder/includeConstants.txt
  binder/includeFunctions.txt
  binder/includeStructs.txt
  binder/includeTypedefs.txt
  binder/includeUnions.txt
  binder/includeVars.txt
  binder/linkLibraries.txt
  common.sc
Labels: Internal

#3575 Added disallowIOCreation as a public API
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/MultiClock.scala
  src/main/scala/chisel3/FixedIOModule.scala
  src/test/scala/chiselTests/FixedIOModuleSpec.scala
Labels: Feature

#3597 use flake input to provide circt source
  flake.lock
  flake.nix
  overlay.nix
Labels: Internal

#3599 Add llvm-lit into nix devShell
  flake.nix
  nix/llvm-lit.nix
  overlay.nix
Labels: Internal, No Release Notes

#3600 Bugfix: foo and foo_ names cause incorrect prefix calculation
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chisel3/internal/NamespaceSpec.scala
Labels: Bugfix

#3604 Don't add DedupGroupAnnotation to classes.
  src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
  src/test/scala/chiselTests/DedupSpec.scala
Labels: Bugfix

#3605 remove clock and cond from probe force/release API
  core/src/main/scala/chisel3/probe/package.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/chiselTests/interface/TappedInterfaceSpec.scala
Labels: API Modification

#3601 Updated Path property target type serialization.
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Bugfix

#3610 Additional checks in probe packagae
  core/src/main/scala/chisel3/probe/Probe.scala
  core/src/main/scala/chisel3/probe/ProbeValue.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Backend Code Generation

#3611 set sample_element's probeInfo for Vecs
  core/src/main/scala/chisel3/probe/package.scala
Labels: Bugfix
