Repository chipsalliance/chisel, pull requests merged in 2023-11, with the labels that each got.

#3612 Alignment: Don't require a Connectable base, split.
  core/src/main/scala/chisel3/connectable/Alignment.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
Labels: Internal

#3614 Add type specifier on AddDedupGroupAnno phase optionalPrerequisites
  src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
Labels: Internal

#3615 Add type ascription to implicits from instantiable
  macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
Labels: Bugfix

#3623 Support instanceName on HasId without a component by using localName.
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
Labels: Feature

#3624 Add source locators to all subclasses of BaseModule
  build.sbt
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/internal/SourceInfoFileResolver.scala
  core/src/main/scala/chisel3/internal/SourceInfoMacro.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselUtils.scala
  plugin/src/main/scala/chisel3/internal/sourceinfo/SourceInfoFileResolver.scala
  src/test/scala/chiselTests/IntrinsicModule.scala
  src/test/scala/chiselTests/SourceLocatorSpec.scala
  src/test/scala/chiselTests/util/circt/ClockGate.scala
  src/test/scala/chiselTests/util/circt/IsXSpec.scala
  src/test/scala/chiselTests/util/circt/PlusArgsTestSpec.scala
  src/test/scala/chiselTests/util/circt/PlusArgsValueSpec.scala
  src/test/scala/chiselTests/util/circt/SizeOfSpec.scala
  src/test/scala/chiselTests/util/circt/Synthesis.scala
Labels: Feature

#3627 Remove Map and Tuple property types.
  build.sbt
  build.sc
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  project/Boilerplate.sc
  project/Boilerplate.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: API Modification

#3619 Add SparseVec
  integration-tests/src/test/scala/chiselTest/util/SparseVecSpec.scala
  src/main/scala/chisel3/util/SparseVec.scala
Labels: Feature

#3631 [binder] Update API `FIRRTLDirection` for CIRCT 1.60.0
  binder/includeConstants.txt
  binder/src/main/scala/PanamaCIRCT.scala
  binder/src/main/scala/PanamaCIRCTConverter.scala
Labels: No Release Notes

#3632 Rename "groups" to "layers"
  core/src/main/scala/chisel3/Group.scala
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  docs/src/explanations/layers.md
  docs/src/explanations/optional-groups.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/LayerSpec.scala
  website/docs/src/main/resources/microsite/data/menu.yml
Labels: API Modification

#3634 [circt] Remove deprecated dedup option
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: No Release Notes

#3635 Enable checkConnect for Property types in MonoConnect.
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
Labels: Bugfix

#3628 Support Instance for Definitions of Classes.
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Object.scala
  core/src/main/scala/chisel3/properties/Property.scala
  src/test/scala/chiselTests/properties/ClassSpec.scala
  src/test/scala/chiselTests/properties/ObjectSpec.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3637 Don't emit nodes when calling .asBool on a Bool
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/LTLSpec.scala
  src/test/scala/chiselTests/UIntOps.scala
  src/test/scala/chiselTests/VerificationSpec.scala
Labels: Backend Code Generation

#3645 [ci] Record published version in step summary
  .github/workflows/ci.yml
Labels: Documentation

#3650 [website] Add robots.txt
  website/static/robots.txt
Labels: Documentation

#3653 [website] Docusaurus set trailingSlash to false
  docs/src/appendix/appendix.md
  docs/src/cookbooks/cookbooks.md
  docs/src/developers/developers.md
  docs/src/explanations/explanations.md
  docs/src/resources/resources.md
  website/docusaurus.config.js
Labels: Documentation

#3651 [website] Enable Algolia-powered search
  website/docusaurus.config.js
Labels: Documentation

#3613 DataMirror.isFullyAligned: add method to check data is all aligned.
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature, Please Merge

#3656 [website] docs/introduction => docs/index, add redirects
  docs/src/index.md
  website/Makefile
  website/docusaurus.config.js
  website/src/pages/index.js
Labels: Documentation

#3657 [website] More redirects
  website/docusaurus.config.js
Labels: Documentation

#3660 [docs] Update README after 5.1.0 release
  README.md
Labels: Documentation

#3661 [website] Generate links to ScalaDoc for API page
  build.sbt
  project/Contributors.scala
  project/Releases.scala
  project/Version.scala
  project/plugins.sbt
  website/Makefile
  website/src/pages/api.md
Labels: Documentation

#3665 [website] Self-host latest [stable] API docs
  .gitignore
  build.sbt
  project/Releases.scala
  website/.gitignore
  website/Makefile
  website/docusaurus.config.js
  website/src/pages/api/chisel3/latest.js
Labels: Documentation
