Repository chipsalliance/chisel, pull requests merged in 2023-02, with the labels that each got.

#2965 [website] Stop publishing pre 3.5 API docs, clean up deploy flow
  .github/workflows/test.yml
  website/Makefile
  website/README.md
  website/docs/src/main/resources/microsite/data/menu.yml
  website/docs/src/main/tut/api/index.md
Labels: Please Merge

#2940 Make unittests that used BasicTester and TesterDriver to use MFC
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/chisel3/testers/TestUtils.scala
  src/test/scala/chiselTests/AsTypeOfTester.scala
  src/test/scala/chiselTests/Assert.scala
  src/test/scala/chiselTests/AsyncResetSpec.scala
  src/test/scala/chiselTests/BlackBox.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/ConnectSpec.scala
  src/test/scala/chiselTests/DataEqualitySpec.scala
  src/test/scala/chiselTests/DedupSpec.scala
  src/test/scala/chiselTests/FixedPointSpec.scala
  src/test/scala/chiselTests/IntervalSpec.scala
  src/test/scala/chiselTests/LiteralExtractorSpec.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
  src/test/scala/chiselTests/Mem.scala
  src/test/scala/chiselTests/MigrateCompileOptionsSpec.scala
  src/test/scala/chiselTests/Module.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/SourceLocatorSpec.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
  src/test/scala/chiselTests/experimental/DataViewIntegrationSpec.scala
  src/test/scala/chiselTests/experimental/TraceSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Utils.scala
  src/test/scala/chiselTests/util/BitSetSpec.scala
  src/test/scala/chiselTests/util/random/LFSRSpec.scala
Labels: release issue, Please Merge

#2968 Specify Bundle.elements ordering in API docs
  core/src/main/scala/chisel3/Aggregate.scala
Labels: Please Merge

#2969 Document that PriorityEncoder output for 0 is undefined
  src/main/scala/chisel3/util/OneHot.scala
Labels: Please Merge

#2974 Remove loadMemoryFromFile from Deprecated Roadmap, NFC
  ROADMAP.md
Labels: Please Merge

#2976 Remove unconditional log
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#2978 Bump default scala to 2.13.10
  build.sbt
  docs/src/explanations/printing.md
Labels: release issue

#2980 Move prefix and noprefix from internal to experimental
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/SeqUtils.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/connectable/package.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/experimental/prefix.scala
Labels: Please Merge, Skip chiseltest

#2977 Cleanup warnings 1
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/Error.scala
  macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
  src/test/scala/chiselTests/BetterNamingTests.scala
  src/test/scala/chiselTests/ComplexAssign.scala
  src/test/scala/chiselTests/Math.scala
  src/test/scala/chiselTests/MixedVecSpec.scala
  src/test/scala/chiselTests/QueueFlushSpec.scala
  src/test/scala/chiselTests/QueueSpec.scala
  src/test/scala/chiselTests/UIntOps.scala
  src/test/scala/chiselTests/Vec.scala
Labels: code improvement

#2999 Bump firtool to 1.30.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: release issue

#3000 Promote ChiselException to package chisel3
  core/src/main/scala/chisel3/Num.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/experimental/Attach.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/Error.scala
  core/src/main/scala/chisel3/package.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/InstanceNameSpec.scala
  src/test/scala/chiselTests/LiteralToTargetSpec.scala
  src/test/scala/chiselTests/MultiAssign.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/RawModuleSpec.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
Labels: release issue, Please Merge

#2996 [CIRCT] Remove CombinationalPath Anno Dropping
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#2981 Enable BoringUtils Tests with MFC
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Please Merge

#2979 Convert loadMemoryFromFile tests to use MFC
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
Labels: Please Merge

#3001 [circt] Stop dropping RunFirrtlTransformAnnotation
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#3002 Change WireInit from val to object for ScalaDoc
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/package.scala
Labels: Please Merge

#3003 Promote InstanceId to package chisel3
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/package.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
  src/test/scala/chiselTests/NamedModuleTester.scala
Labels: Please Merge

#3006 [circt] Remove reliance on some FIRRTL Phases
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#3007 Cleanup warnings 3
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/Namer.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  macros/src/main/scala/chisel3/internal/InstantiableMacro.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/util/Conditional.scala
  src/main/scala/chisel3/util/Counter.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/test/scala/chiselTests/AsTypeOfTester.scala
  src/test/scala/chiselTests/BlackBox.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/CompatibilitySpec.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
  src/test/scala/chiselTests/CustomBundle.scala
  src/test/scala/chiselTests/Decoder.scala
  src/test/scala/chiselTests/Direction.scala
  src/test/scala/chiselTests/ExtModule.scala
  src/test/scala/chiselTests/InlineSpec.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
  src/test/scala/chiselTests/MemorySearch.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/RecordSpec.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
  src/test/scala/chiselTests/stage/phases/EmitterSpec.scala
  src/test/scala/circtTests/stage/CIRCTStageSpec.scala
Labels: Please Merge

#3008 Deprecate chisel3.stage.ChiselStage
  docs/src/cookbooks/hierarchy.md
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/package.scala
Labels: Please Merge

#3011 Deprecate group API
  src/main/scala/chisel3/util/experimental/group.scala
Labels: Please Merge

#3014 Decouple {circt, chisel3}.stage.ChiselStage
  src/main/scala/circt/stage/Annotations.scala
  src/main/scala/circt/stage/CIRCTStage.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/test/scala/chiselTests/Printf.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#3015 Drop ImportDefinitionAnnotation in CIRCT Phase
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#3016 Pass ChiselCircuitAnnotation through CIRCT phase
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#3019 Copy chisel3.stage.ChiselStageSpec tests for CIRCT
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#3012 Improve Builder.forceName collision errors
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/package.scala
  src/test/scala/chisel3/internal/NameCollisionSpec.scala
Labels: Please Merge

#3018 Convert tests to circt.stage.ChiselStage
  src/main/scala/chisel3/compatibility.scala
  src/test/scala/chisel3/testers/TestUtils.scala
  src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
  src/test/scala/chiselTests/InvalidateAPISpec.scala
  src/test/scala/chiselTests/NewAnnotationsSpec.scala
  src/test/scala/chiselTests/WarningSpec.scala
  src/test/scala/chiselTests/experimental/SerializableModuleGeneratorSpec.scala
  src/test/scala/chiselTests/experimental/TraceSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
  src/test/scala/chiselTests/util/SizeOfSpec.scala
Labels: Please Merge

#3022 Deprecate NoRunFirrtlCompilerAnnotation
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
Labels: Please Merge

#3023 [circt] Remove CIRCTStage optional prereq on SFC
  src/main/scala/circt/stage/CIRCTStage.scala
Labels: Please Merge

#3025 Deprecate CIRCTStage (firtool wrapper)
  src/main/scala/circt/stage/CIRCTStage.scala
Labels: Please Merge

#3026 Add "--split-verilog" circt.*.ChiselStage option
  src/main/scala/circt/stage/Annotations.scala
  src/main/scala/circt/stage/CIRCTOptions.scala
  src/main/scala/circt/stage/CIRCTStage.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#3027 Remove SFC Dependencies in AnnotatingDiamondSpec
  src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
Labels: Please Merge

#3024 Remove a FIRRTL phase CIRCTStage "currentState"
  src/main/scala/circt/stage/CIRCTStage.scala
Labels: Please Merge

#3028 Deprecate Protobuf Emission
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
Labels: Please Merge

#3029 Fix bug in "--split-verilog" output
  src/main/scala/circt/stage/package.scala
  src/test/scala/chiselTests/BlackBoxImpl.scala
  src/test/scala/chiselTests/ExtModuleImpl.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
  src/test/scala/chiselTests/experimental/TraceSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#3021 Cleanup warnings final
  build.sbt
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#3032 Catch private default constructors for Bundles and Records
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/test/scala/chiselTests/AutoClonetypeSpec.scala
Labels: Please Merge

#3033 Print warning when extractor is too wide or narrow
  core/src/main/scala/chisel3/Bits.scala
  docs/src/cookbooks/cookbook.md
  src/test/scala/chiselTests/UIntOps.scala
Labels: Please Merge

#3039 Give a source line and caret for errors when possible
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselCli.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/circt/stage/CIRCTStage.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/test/resources/chisel3/sourceroot1/Foo
  src/test/resources/chisel3/sourceroot2/Foo
  src/test/scala/chiselTests/stage/ChiselMainSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#3041 Get rid of warnings in / doc build
  .github/workflows/test.yml
  build.sbt
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/connectable/Connectable.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/Trace.scala
  core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/IsInstantiable.scala
  core/src/main/scala/chisel3/experimental/hierarchy/package.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/package.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselPlugin.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/aop/injecting/InjectStatement.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselStage.scala
  src/main/scala/chisel3/stage/phases/AspectPhase.scala
  src/main/scala/chisel3/stage/phases/Checks.scala
  src/main/scala/chisel3/stage/phases/Convert.scala
  src/main/scala/chisel3/stage/phases/MaybeInjectingPhase.scala
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/Valid.scala
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
  src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala
  src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
  src/main/scala/chisel3/util/pla.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/main/scala/circt/stage/phases/Checks.scala
Labels: Please Merge, Documentation
