Repository chipsalliance/chisel, pull requests merged in 2023-07, with the labels that each got.

#3383 SRAM API: Add multiple-clocked port API
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/Mem.scala
Labels: Feature

#3403 [svsim] Don't redirect simulation stderr to a pipe
  svsim/src/main/scala/Simulation.scala
Labels: Bugfix

#3367 upgrade mill to 0.11.0
  .github/workflows/test.yml
  build.sc
  common.sc
Labels: Internal

#3409 Disable argument extensions when in devcontainer
  .devcontainer/Dockerfile
  firrtl/src/main/scala/firrtl/options/Shell.scala
Labels: Internal

#3413 Remove firrtl/regress, these old files are unused
  firrtl/regress/AddNot.fir
  firrtl/regress/FPU.fir
  firrtl/regress/HwachaSequencer.fir
  firrtl/regress/ICache.fir
  firrtl/regress/Ops.fir
  firrtl/regress/Rob.fir
  firrtl/regress/RocketCore.fir
Labels: Internal

#3415 Bump firtool to 1.45.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: Please Merge, Dependency Update

#3421 Update versioning.md for Chisel 5.0.0.
  docs/src/appendix/versioning.md
Labels: Documentation

#3419 Sanitize Record._elements
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Bugfix

#3402 Add a new `take` method on `Bits` that returns the requested number
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Feature

#3422 Bump firtool to 1.47.0 from 1.45.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
  src/test/scala/chiselTests/DedupSpec.scala
  src/test/scala/chiselTests/LoadMemoryFromFileSpec.scala
Labels: Dependency Update

#3428 Deprecate old BoringUtils API
  build.sbt
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
Labels: Deprecation

#3418 Extend constants in `probe.force` and `probe.forceInitial` methods.
  core/src/main/scala/chisel3/probe/package.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Bugfix, Please Merge

#3414 Add support for configurable warnings
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/experimental/SourceInfo.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  core/src/main/scala/chisel3/internal/Warning.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/package.scala
  docs/src/explanations/explanations.md
  docs/src/explanations/warnings.md
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/chisel3/testers/TestUtils.scala
  src/test/scala/chiselTests/ConstSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
  website/docs/src/main/resources/microsite/data/menu.yml
Labels: Feature

#3433 Remove SourceLineNoCol
  core/src/main/scala/chisel3/experimental/SourceInfo.scala
  core/src/main/scala/chisel3/internal/Error.scala
  core/src/main/scala/chisel3/internal/Warning.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Bugfix

#3434 Add FirtoolBinaryPath option
  src/main/scala/circt/stage/Annotations.scala
  src/main/scala/circt/stage/CIRCTOptions.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/package.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Feature

#3441 Remove intermediate wire creation from Boringutils Tap API
  core/src/main/scala/chisel3/Module.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix, Please Merge

#3429 Add a new BaseType type that Data inherits, and use it for ports.
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/simulator/package.scala
Labels: API Modification
