Repository chipsalliance/chisel, pull requests merged in 2023-03, with the labels that each got.

#3062 Move the Cat object to chisel3 package
  docs/src/cookbooks/verilog-vs-chisel.md
  integration-tests/src/test/scala/chiselTest/LFSRSpec.scala
  src/main/scala/chisel3/Cat.scala
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/util.scala
  src/test/scala/chiselTests/CatSpec.scala
Labels: code improvement, Please Merge

#3063 Disallow --target-dir in ChiselStage$
  firrtl/src/main/scala/firrtl/options/Shell.scala
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Please Merge

#3066 Use -std=c++11 for Verilator 5.0 support
  firrtl/src/main/scala/firrtl/util/BackendCompilationUtilities.scala
Labels: Please Merge

#3073 Fix broken cookbook link
  docs/src/cookbooks/cookbook.md
Labels: Please Merge

#3079 Bump CIRCT to 1.34.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: Please Merge

#3055 Removed innards and NotStrict for CompileOptions, and object Chisel
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/CompileOptions.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  docs/src/appendix/chisel3-vs-chisel2.md
  docs/src/explanations/unconnected-wires.md
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/main/scala/chisel3/util/MixedVec.scala
  src/test/scala/chiselTests/InvalidateAPISpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Labels: DO NOT MERGE

#3087 Release Chisel v5.0.0-M1
  build.sbt
Labels: Merge with merge commit

#3078 Simplify assertKnownWidth to Verilog test
  src/test/scala/chiselTests/ChiselSpec.scala
Labels: Please Merge

#3056 Remove compile options everywhere in Chisel internals.
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/CompileOptions.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/ModuleAspect.scala
  core/src/main/scala/chisel3/Mux.scala
  core/src/main/scala/chisel3/Num.scala
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/SeqUtils.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/hierarchy/DefinitionClone.scala
  core/src/main/scala/chisel3/experimental/hierarchy/InstanceClone.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala
  core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/package.scala
  macros/src/main/scala/chisel3/SourceInfoDoc.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/Cat.scala
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/Bitwise.scala
  src/main/scala/chisel3/util/Conditional.scala
  src/main/scala/chisel3/util/Decoupled.scala
  src/main/scala/chisel3/util/Reg.scala
  src/main/scala/chisel3/util/Valid.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
Labels: Please Merge

#3083 Add VSCode devcontainer config
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: Please Merge

#3101 Remove deprecated CIRCT Options
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Please Merge

#3102 [nfc] Remove two unused SFC annotations
  firrtl/src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
  firrtl/src/main/scala/firrtl/transforms/OptimizationAnnotations.scala
Labels: Please Merge

#3095 add curried MuxLookup.apply, deprecate old apply
  docs/src/explanations/muxes-and-input-selection.md
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/util/Mux.scala
  src/test/scala/chiselTests/MuxSpec.scala
Labels: Please Merge

#3113 Fix MuxLookup old API deprecation
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/util/Mux.scala
Labels: release issue

#3106 Remove reflectivelyFindIO, its unused
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/package.scala
Labels: Please Merge

#3037 Detect bound hardware when processing record elements
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Please Merge

#3091 Update README, fix link to roadmap.md
  README.md
Labels: Please Merge

#3119 Update README.md, fix scala version support badge
  README.md
Labels: Please Merge

#3120 More VSCode Devcontainer Improvements
  .devcontainer/Dockerfile
Labels: Please Merge

#3141 Use %[[]] format for ChsielAnnotations
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
  firrtl/src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
  firrtl/src/test/scala/firrtlTests/stage/phases/ChecksSpec.scala
  src/main/scala/chisel3/stage/phases/Convert.scala
  src/test/scala/chisel3/testers/TestUtils.scala
  src/test/scala/chiselTests/AnnotatingDiamondSpec.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/NewAnnotationsSpec.scala
  src/test/scala/chiselTests/stage/phases/ConvertSpec.scala
  src/test/scala/chiselTests/util/SizeOfSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
  src/test/scala/circtTests/stage/phases/AddImplicitOutputFileSpec.scala
Labels: Please Merge
