Repository chipsalliance/chisel, pull requests merged in 2023-06, with the labels that each got.

#3313 Don't emit implicit clock warnings for `SyncReadMem.readWrite` when explicit clocks are used
  core/src/main/scala/chisel3/Mem.scala
Labels: Bugfix

#3314 Convert Vec dynamic index with a literal to static index
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/VecToTargetSpec.scala
Labels: Performance

#3301 Support ref types on interfaces
  src/main/scala/chisel3/interface/Interface.scala
  src/test/scala/chiselTests/interface/InterfaceSpec.scala
Labels: Feature

#3321 Warn on incorrect widths for Vec dynamic indexing
  core/src/main/scala/chisel3/Aggregate.scala
  docs/src/cookbooks/cookbook.md
  src/test/scala/chiselTests/Vec.scala
Labels: Deprecation

#3327 Add Scala 2.13.11 and 2.12.18 to plugin cross versions
  build.sbt
Labels: Dependency Update

#3332 Bump to firtool 1.43.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: Dependency Update

#3334 Fix color emission to check for interactive terminal
  core/src/main/scala/chisel3/internal/Error.scala
Labels: Feature

#3300 Unify recursive Data traversals into DataMirror
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/main/scala/chisel3/aop/Select.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
Labels: Feature

#3341 Report Builder errors even when exception is thrown
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Bugfix

#3346 Bring ToC and Menu into alignment, some minor cleanup within docs
  docs/src/explanations/bundles-and-vecs.md
  docs/src/explanations/data-types.md
  docs/src/explanations/explanations.md
  docs/src/explanations/interfaces-and-connections.md
  docs/src/explanations/operators.md
  docs/src/explanations/width-inference.md
  website/docs/src/main/resources/microsite/data/menu.yml
Labels: Documentation

#3345 Remove references to interval types from the website docs
  docs/src/appendix/experimental-features.md
  docs/src/explanations/data-types.md
Labels: Documentation

#3339 Update sbt to 1.9.0
  project/build.properties
Labels: Internal

#3338 Update sbt-scalafix to 0.11.0
  project/plugins.sbt
Labels: Internal

#3349 Add support for Instantiate for BlackBox, ExtModule, and IntrinsicModule
  core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Labels: Feature

#3352 Add support for zero-width bit extraction
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Feature

#3326 Support linking ref types on interfaces
  src/test/scala/chiselTests/interface/Drivers.scala
  src/test/scala/chiselTests/interface/InterfaceSpec.scala
Labels: Bugfix, Please Merge

#3356 Update meeting time and versions in README
  README.md
Labels: Documentation

#3358 Bump to Scala 2.13.11
  .github/workflows/build-scala-cli-template/chisel-template.scala
  .github/workflows/test.yml
  build.sbt
  build.sc
  project/plugins.sbt
Labels: Dependency Update

#3337 Add basic linear temporal logic assertions
  src/main/scala/chisel3/ltl/LTL.scala
  src/main/scala/chisel3/util/circt/LTLIntrinsics.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Feature

#3228 Implement a SyncReadMem wrapper with explicit read, write, and read/write ports
  docs/src/explanations/memories.md
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/Mem.scala
Labels: Feature

#3360 Make devcontainer point to CIRCT top-of-tree instead of latest release
  .devcontainer/Dockerfile
  .gitignore
Labels: Internal

#3303 Add tests for interfaces with reference ports
  src/test/scala/chiselTests/interface/TappedInterfaceSpec.scala
Labels: Please Merge, Internal

#3368 Bump firtool from 1.43.0 -> 1.44.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: Dependency Update

#3370 README.md: Fix link to gitter badge
  README.md
Labels: Documentation

#3369 Add test demonstrating a ref to an aggregate member
  src/test/scala/chiselTests/interface/InterfaceSpec.scala
Labels: Internal

#3371 Fix BuildInfo in 3.6.x
  build.sc
Labels: Internal

#3344 Make it possible to illegalize .asUInt on OpaqueTypes
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/experimental/OpaqueType.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/Direction.scala
  src/test/scala/chiselTests/MixedVecSpec.scala
  src/test/scala/chiselTests/RecordSpec.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/experimental/OpaqueTypeSpec.scala
Labels: Feature

#3373 Split out MixedVecSpec integration tests
  integration-tests/src/test/scala/chiselTest/MixedVecIntegrationSpec.scala
  integration-tests/src/test/scala/chiselTest/VecIntegrationSpec.scala
  src/test/scala/chiselTests/MixedVecSpec.scala
Labels: Internal

#3376 [CI] Bump OSS CAD tools build to 2023-06-21 release
  .github/workflows/setup-oss-cad-suite/action.yml
Labels: Dependency Update

#3372 Add MuxCell intrinsics
  src/main/scala/chisel3/util/circt/Synthesis.scala
  src/test/scala/chiselTests/util/circt/Synthesis.scala
Labels: Feature

#3377 Add Chips Alliance to README
  README.md
Labels: Documentation

#3378 Un-ignore force tests now we have newer verilator in CI.
  src/test/scala/chiselTests/interface/TappedInterfaceSpec.scala
Labels: Internal

#3364 SRAM API: Add a parameter to initialize the memory
  src/main/scala/chisel3/util/SRAM.scala
Labels: Feature

#3382 Correctly set ProbeInfo to None for Aggregate types on a probe.read
  core/src/main/scala/chisel3/probe/package.scala
Labels: Bugfix, Please Merge

#3188 [codegen] Use FIRRTL 3.0.0 syntax (connect, invalidate, regreset, radix-encoded integer literals)
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/BulkConnectSpec.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
  src/test/scala/chiselTests/DecoupledSpec.scala
  src/test/scala/chiselTests/Direction.scala
  src/test/scala/chiselTests/ExtModule.scala
  src/test/scala/chiselTests/InstanceNameSpec.scala
  src/test/scala/chiselTests/InvalidateAPISpec.scala
  src/test/scala/chiselTests/LTLSpec.scala
  src/test/scala/chiselTests/LiteralToTargetSpec.scala
  src/test/scala/chiselTests/Mem.scala
  src/test/scala/chiselTests/MixedVecSpec.scala
  src/test/scala/chiselTests/MuxSpec.scala
  src/test/scala/chiselTests/PrintableSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/chiselTests/RecordSpec.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/experimental/DataView.scala
  src/test/scala/chiselTests/experimental/FlatIOSpec.scala
  src/test/scala/chiselTests/experimental/OpaqueTypeSpec.scala
  src/test/scala/chiselTests/experimental/Tuple.scala
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
  src/test/scala/chiselTests/util/PipeSpec.scala
  src/test/scala/chiselTests/util/circt/PlusArgsValueSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Backend Code Generation

#3374 [codegen] Emit literal identifiers for numeric ids
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
Labels: Backend Code Generation

#3384 Support bulk connection for const types
  firrtl/src/main/scala/firrtl/passes/CheckTypes.scala
  src/test/scala/chiselTests/ConstSpec.scala
Labels: Backend Code Generation

#3385 Add messages to require statements in Math
  src/main/scala/chisel3/util/Math.scala
Labels: Bugfix

#3389 Support literals and DontCare in DataView targets
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Feature

#3393 Avoid emitting 'const const' for const vecs of const elements
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/ConstSpec.scala
Labels: Please Merge, Backend Code Generation

#3392 Fix issue where reify would do the same lookup twice
  core/src/main/scala/chisel3/experimental/dataview/package.scala
Labels: Performance

#3395 Deprecate calling .viewAs on non-hardware
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Deprecation

#3398 Error when calling .viewAs on non-hardware
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: API Modification
