Repository chipsalliance/chisel, pull requests merged in 2023-08, with the labels that each got.

#3439 Optimize source locator escaping when emitting FIRRTL
  firrtl/src/main/scala/firrtl/ir/IR.scala
  src/test/scala/chiselTests/SourceLocatorSpec.scala
Labels: Performance

#3448 [docs] Fix chiseltest version in old compatible versions
  docs/src/appendix/versioning.md
Labels: Documentation

#3442 Move more Data methods to BaseType and base connection checks on BaseType.
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
Labels: Internal

#3450 Bump to firtool 1.48.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: Dependency Update

#3453 Add --dump-fir option to ChiselStage
  src/main/scala/circt/stage/Annotations.scala
  src/main/scala/circt/stage/CIRCTOptions.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/package.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature

#3452 [ci] Add "nightly" option to install-circt action
  .github/workflows/build-scala-cli-template/action.yml
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: No Release Notes

#3457 [ci] Change Scala-CLI Template Composite Action to Workflow
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/build-scala-cli-template/action.yml
  .github/workflows/scala-cli-template.yml
  .github/workflows/test.yml
Labels: Merge with merge commit, Please Merge, No Release Notes

#3459 [ci] Make test.yml a reusable workflow
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: No Release Notes

#3446 Add hook to invoke hardware generators at the end of elaboration.
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/RawModuleSpec.scala
Labels: Feature

#3461 [ci] Add skeleton of nightly CIRCT CI job
  .github/workflows/ci-circt-nightly.yml
Labels: No Release Notes

#3462 [ci] Fix broken all_tests_passed
  .github/workflows/ci.yml
Labels: No Release Notes

#3463 [ci] Change CIRCT version to exist in one place
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/ci.yml
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: No Release Notes

#3467 [ci] Use 'default' as version string for typical CIRCT version
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/ci.yml
  .github/workflows/install-circt/action.yml
Labels: Internal

#3460 [ci] Add CIRCT nightly CI
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: No Release Notes

#3425 Initial properties package and Property type.
  core/src/main/scala/chisel3/properties/Property.scala
  core/src/main/scala/chisel3/properties/package.scala
  docs/src/explanations/explanations.md
  docs/src/explanations/properties.md
  src/test/scala/chiselTests/properties/PropertySpec.scala
  website/docs/src/main/resources/microsite/data/menu.yml
Labels: Feature

#3443 Tests for RWTapping aggregates
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Please Merge, Internal

#3472 [ci] Move CIRCT version to JSON file
  .github/workflows/install-circt/action.yml
  etc/README.md
  etc/circt.json
Labels: No Release Notes

#3478 [ci] Remove caching of firtool
  .github/workflows/install-circt/action.yml
Labels: No Release Notes

#3436 update ChiselPlugin to name tuples
  core/src/main/scala/chisel3/internal/Builder.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
Labels: Backend Code Generation

#3470 Add support for Integer properties and conversion to FIRRTL.
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature

#3468 [cd] Add CD of CIRCT Releases
  .github/workflows/cd-circt.yml
  .github/workflows/cd-circt/commit-message.md
  .github/workflows/cd-circt/pr-body.md
  .github/workflows/cd-circt/pr-title.md
Labels: No Release Notes

#3481 Support connecting Properties.
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3482 Add support for Property literals, starting with existing int types.
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3491 Add support for sequences of Properties, including values.
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3489 Add support for Class and Object on top of Properties.
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Object.scala
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala/chiselTests/Module.scala
  src/test/scala/chiselTests/properties/ClassSpec.scala
  src/test/scala/chiselTests/properties/ObjectSpec.scala
Labels: Feature

#3496 Support Optionality of implicit clock and reset
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/MultiClock.scala
  src/test/scala/chiselTests/ModuleSpec.scala
  src/test/scala/chiselTests/MultiClockSpec.scala
Labels: Feature

#3485 BoringUtils: rwprobe from inside module, test (rw)taps of IO's.
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix, Please Merge

#3501 ProbeSpec: Add force/release simulator test.
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Please Merge, No Release Notes

#3503 Add Boolean Property type
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3466 Implement CIRCT converter
  .github/workflows/install-circt/action.yml
  .github/workflows/install-jextract/action.yml
  .github/workflows/test.yml
  binder/jextract-headers.h
  binder/src/main/scala/Convert.scala
  binder/src/main/scala/PanamaCIRCT.scala
  binder/src/main/scala/PanamaCIRCTConverter.scala
  binder/src/test/scala/BinderSpec.scala
  build.sc
  common.sc
  core/src/main/scala/chisel3/internal/CIRCTConverter.scala
Labels: Feature

#3497 Add Disable, a new API for disabling simulation constructs
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Disable.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala/chiselTests/DisableSpec.scala
Labels: Feature

#3498 Make LTL properties use Clock and Disable by default
  src/main/scala/chisel3/ltl/LTL.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: API Modification

#3499 Use Instantiate for LTL intrinsic instantiation
  src/main/scala/chisel3/ltl/LTL.scala
  src/main/scala/chisel3/util/circt/LTLIntrinsics.scala
Labels: Performance

#3505 Add Map properties
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Object.scala
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3510 Allow properties on ExtModule IO
  core/src/main/scala/chisel3/Module.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Bugfix

#3508 add Double property type
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3511 add Path property type
  core/src/main/scala/chisel3/properties/PathType.scala
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3500 add DedupGroupAnnotation
  core/src/main/scala/chisel3/Annotation.scala
  firrtl/src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/chiselTests/DedupSpec.scala
Labels: Feature

#3515 Aggregate literals now materialize const wires
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: Backend Code Generation

#3514 Property now extends Data, remove BaseType
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/OpaqueType.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Property.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala/chiselTests/properties/ClassSpec.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: API Modification

#3513 add tuple properties
  build.sbt
  build.sc
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  project/Boilerplate.sc
  project/Boilerplate.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature
