Repository chipsalliance/chisel, pull requests merged in 2023-01, with the labels that each got.

#2926 Update scalatest to 3.2.15
  build.sbt
  build.sc
Labels: Please Merge

#2907 Check for Vec subaccess in NamedComponent and throw a nicer error.
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/VecToTargetSpec.scala
Labels: Please Merge

#2924 Support generate structured decoder with DecodeTable
  docs/src/explanations/decoder.md
  src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala
  src/test/scala/chiselTests/util/experimental/DecoderTableSpec.scala
Labels: Please Merge

#2929 Promote ChiselEnum user APIs from experimental
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/experimental/EnumAnnotations.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  docs/src/cookbooks/cookbook.md
  docs/src/cookbooks/verilog-vs-chisel.md
  docs/src/explanations/chisel-enum.md
  src/test/scala/chiselTests/AsTypeOfTester.scala
  src/test/scala/chiselTests/BundleElementsSpec.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/DataEqualitySpec.scala
  src/test/scala/chiselTests/DataPrint.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
  src/test/scala/chiselTests/WarningSpec.scala
  src/test/scala/chiselTests/experimental/TraceSpec.scala
  src/test/scala/cookbook/FSM.scala
Labels: API Modification, Please Merge

#2933 [CI] Update CIRCT from 1.24.0 -> 1.26.0, accomodate tag name change.
  .github/workflows/install-circt/action.yml
Labels: Please Merge

#2935 TruthTable improvements: structural equality and delete sort
  src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
  src/test/scala/chiselTests/util/experimental/TruthTableSpec.scala
Labels: API Modification

#2932 Support zero-width integer literals.
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
  src/test/scala/chiselTests/WidthSpec.scala
Labels: API Addition

#2937 Deprecate public internals and fix warning suppression
  build.sbt
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/package.scala
  docs/src/explanations/annotations.md
Labels: Please Merge

#2944 Move SourceInfo to package experimental
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/Mux.scala
  core/src/main/scala/chisel3/Num.scala
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/SeqUtils.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/connectable/Connectable.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/connectable/package.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/experimental/Attach.scala
  core/src/main/scala/chisel3/experimental/SourceInfo.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/Error.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/SourceInfo.scala
  core/src/main/scala/chisel3/internal/SourceInfoMacro.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/package.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/compatibility.scala
  src/main/scala/chisel3/testers/BasicTester.scala
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/Bitwise.scala
  src/main/scala/chisel3/util/Cat.scala
  src/main/scala/chisel3/util/Conditional.scala
  src/main/scala/chisel3/util/Reg.scala
  src/test/scala/chiselTests/IntervalSpec.scala
  src/test/scala/chiselTests/Module.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Labels: Please Merge, Skip chiseltest

#2942 Bring the website (chisel5) in as git subtree
  .github/workflows/test.yml
  website/.gitignore
  website/.gitmodules
  website/.mergify.yml
  website/LICENSE
  website/Makefile
  website/README.md
  website/build.sbt
  website/docs/src/main/resources/json/README.md
  website/docs/src/main/resources/json/smem_read_write.json
  website/docs/src/main/resources/json/smem_rw.json
  website/docs/src/main/resources/microsite/data/menu.yml
  website/docs/src/main/resources/microsite/img/jumbotron_pattern.png
  website/docs/src/main/resources/microsite/img/jumbotron_pattern2x.png
  website/docs/src/main/resources/microsite/img/navbar_brand.png
  website/docs/src/main/resources/microsite/img/navbar_brand2x.png
  website/docs/src/main/resources/microsite/img/second_icon.png
  website/docs/src/main/resources/microsite/img/second_icon2x.png
  website/docs/src/main/resources/microsite/img/sidebar_brand.png
  website/docs/src/main/resources/microsite/img/sidebar_brand2x.png
  website/docs/src/main/resources/microsite/img/third_icon.png
  website/docs/src/main/resources/microsite/img/third_icon2x.png
  website/docs/src/main/resources/svg/Makefile
  website/docs/src/main/resources/svg/chisel-jumbotron.svg
  website/docs/src/main/resources/svg/chisel-tool-icon-inverted.svg
  website/docs/src/main/resources/svg/chisel-tool-icon.svg
  website/docs/src/main/resources/svg/chisel-tool.svg
  website/docs/src/main/resources/svg/firrtl-tech.svg
  website/docs/src/main/tut/api/chisel3/3.5/.index.md.swp
  website/docs/src/main/tut/api/chisel3/3.5/index.md
  website/docs/src/main/tut/api/chisel3/latest/.index.md.swp
  website/docs/src/main/tut/api/chisel3/latest/index.md
  website/docs/src/main/tut/api/index.md
  website/docs/src/main/tut/chisel3/index.md
  website/docs/src/main/tut/community.md
  website/docs/src/main/tut/doc/chisel-cheatsheet3.pdf/index.md
  website/project/Contributors.scala
  website/project/Version.scala
  website/project/build.properties
  website/project/plugins.sbt
  website/scripts/decrypt-keys.sh
  website/travis-deploy-key.enc
Labels: Merge with merge commit

#2960 Publish website to gh-pages branch on pushes to master (#2950)
  .github/workflows/test.yml
  README.md
  website/README.md
  website/build.sbt
Labels: Please Merge

#2955 Remove all references and usages of Treadle
  .github/workflows/test.yml
  README.md
  SETUP.md
  build.sbt
  build.sc
  docs/src/appendix/chisel3-vs-chisel2.md
  docs/src/appendix/experimental-features.md
  docs/src/developers/style.md
  docs/src/explanations/blackboxes.md
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
  src/test/scala/chisel3/testers/TreadleBackend.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/QueueFlushSpec.scala
Labels: release issue
