Repository chipsalliance/chisel, pull requests merged in 2023-05, with the labels that each got.

#3226 Bump firtool version to 1.40.0
  .github/workflows/install-circt/action.yml
  .github/workflows/test.yml
Labels: Dependency Update

#3221 Improve SyncReadMem.read, .readWrite
  core/src/main/scala/chisel3/Mem.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/test/scala/chiselTests/Mem.scala
Labels: Internal

#3240 Undo removal of address intermediate wire in `SyncReadMem.read`, `SyncReadMem.readWrite`
  core/src/main/scala/chisel3/Mem.scala
  src/test/scala/chiselTests/Mem.scala
Labels: No Release Notes

#3242 Add workflow to automatically update binary compatibility checks
  .github/workflows/enable-bincompat-checking.yml
Labels: Internal

#3247 Use Chisel Bot Token for automated PRs
  .github/workflows/enable-bincompat-checking.yml
Labels: No Release Notes

#3252 Add new workflow to fixup backports for release notes
  .github/workflows/backport-fixup.yml
Labels: Internal

#3255 Fix backport-fixup for labels with spaces
  .github/workflows/backport-fixup.yml
Labels: No Release Notes

#3256 Make release-notes.yml more robust to quotes
  .github/workflows/release-notes.yml
Labels: No Release Notes

#3181 Allow DataView of Reset <=> [UInt<1>, AsyncReset]
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Feature

#3234 Update sbt-ci-release to 1.5.12
  project/plugins.sbt
Labels: Dependency Update

#3145 Update sbt-mima-plugin to 1.1.2
  project/plugins.sbt
Labels: Dependency Update

#3235 [fix] typo fix: chosen port of arbiter is not onehot but UInt
  src/main/scala/chisel3/util/Arbiter.scala
Labels: Documentation

#3262 [bugfix] Fix BoringUtils up--down bug
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: No Release Notes

#3263 [bugfix] Fix naming module with Unit parameter
  core/src/main/scala/chisel3/naming/Identifier.scala
  src/test/scala/chiselTests/naming/IdentifierProposerSpec.scala
Labels: Bugfix

#3266 Update .scala-steward.conf
  .scala-steward.conf
Labels: Internal

#3264 Update scalacheck-1-14 to 3.2.11.0
  build.sbt
  build.sc
Labels: Dependency Update

#3238 [feature] Add properties to Interface
  src/main/scala/chisel3/interface/Interface.scala
  src/test/scala/chiselTests/interface/InterfaceSpec.scala
  src/test/scala/chiselTests/interface/ParametricInterfaceSpec.scala
Labels: Feature

#3267 Enable .viewAsSupertype to work on Records
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Feature

#3049 Update data-class to 0.2.6
  build.sbt
Labels: Dependency Update

#2962 Update sbt-mdoc to 2.3.7
  project/plugins.sbt
Labels: Dependency Update

#3169 Update upickle to 3.1.0
  build.sbt
  build.sc
Labels: Dependency Update

#3270 SemanticDB requires private fields of case class to use "val"
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
Labels: Internal

#3274 [docs] Update website for 5.0, 6.0 and fix links
  website/Makefile
  website/docs/src/main/resources/microsite/data/menu.yml
  website/docs/src/main/tut/api/chisel/5.0/index.md
  website/docs/src/main/tut/api/chisel/6.0/index.md
  website/docs/src/main/tut/api/chisel/latest/index.md
  website/docs/src/main/tut/api/chisel3/3.5/.index.md.swp
  website/docs/src/main/tut/api/chisel3/latest/.index.md.swp
  website/docs/src/main/tut/api/chisel3/latest/index.md
  website/docs/src/main/tut/api/index.md
Labels: Documentation

#3237 Create "tap" API for boring probe-type (non-synthesizable) ports
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  integration-tests/src/test/scala/chiselTest/util/experimental/TapSpec.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: API Modification

#3279 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Internal

#3276 Add Top-level parameterized reset type
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/ResetSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Labels: Feature

#3265 Update scalacheck-1-15 to 3.2.14.0
  build.sbt
Labels: Dependency Update

#3280 [codegen] Simpler FIRRTL Code for Reg w/o Reset
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/util/RegSpec.scala
Labels: Backend Code Generation

#3284 BoringUtils writable tap (rwTap) API
  core/src/main/scala/chisel3/RawModule.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: API Modification

#3285 Optimize BitPat equals, overlap, and cover
  src/main/scala/chisel3/util/BitPat.scala
  src/test/scala/chiselTests/util/BitSetSpec.scala
Labels: Performance

#3291 [CI] Update versions in CI Workflow
  .github/workflows/test.yml
Labels: Internal

#3295 Update roadmap.
  ROADMAP.md
Labels: Documentation

#3294 [bugfix] Don't return Data from BoringUtils APIs
  core/src/main/scala/chisel3/Module.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
Labels: No Release Notes

#3299 Update scalatest to 3.2.16
  build.sbt
Labels: Dependency Update

#3298 Update sbt to 1.8.3
  project/build.properties
Labels: Dependency Update

#3304 Fix README Sonatype Snapshots Link
  README.md
Labels: No Release Notes

#3307 Gate sys/personality.h include under define
  svsim/src/main/resources/simulation-driver.cpp
Labels: Internal

#3309 Make svsim shutdown gracefully when the test throws an exception
  svsim/src/main/scala/Simulation.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Bugfix

#3147 Update ChiselRunners to use svsim
  .devcontainer/devcontainer.json
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/PeekPokeAPI.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
  svsim/src/main/scala/Simulation.scala
  svsim/src/main/scala/verilator/Backend.scala
Labels: Internal

#3306 Allow out-of-package svsim backend implementations
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/Workspace.scala
  svsim/src/main/scala/vcs/Backend.scala
  svsim/src/main/scala/verilator/Backend.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Feature
