Repository chipsalliance/chisel, pull requests merged in 2024-11, with the labels that each got.

#4497 Implement Lookupable for Unit
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Feature

#4479 [Module] Add afterModuleBuilt hook
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/RawModuleSpec.scala
Labels: Feature

#4487 Add `withModulePrefix`
  core/src/main/scala-2/chisel3/experimental/hierarchy/Instantiate.scala
  core/src/main/scala/chisel3/MemImpl.scala
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  docs/src/explanations.md
  docs/src/explanations/moduleprefix.md
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/PrefixSpec.scala
Labels: Feature

#4500 fix: remove source locator for IO in FixedIOModule
  src/main/scala/chisel3/FixedIOModule.scala
Labels: Bugfix, Please Merge

#4492 [Scala3] Add cross build support to Mill
  build.sc
  common.sc
  panama.sc
  tests.sc
Labels: Internal, Scala 3

#4506 Wrap printfs in the Verification layerblock
  core/src/main/scala-2/chisel3/PrintfMacros.scala
  src/test/scala/chiselTests/Printf.scala
Labels: Backend Code Generation

#4505 Change default layers to use lowercase directories
  core/src/main/scala/chisel3/layers/Layers.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Backend Code Generation

#4501 Change link colors for aid in readability in dark mode.
  website/src/css/custom.css
Labels: Documentation

#4483 [Scala3] Scala2 compatibility changes
  core/src/main/scala-2/chisel3/Aggregate.scala
  core/src/main/scala-2/chisel3/Bits.scala
  core/src/main/scala-2/chisel3/Printf.scala
  core/src/main/scala-2/chisel3/VerificationStatement.scala
  core/src/main/scala-2/chisel3/experimental/dataview/ChiselSubtypeOf.scala
  core/src/main/scala-2/chisel3/experimental/dataview/InvertibleDataView.scala
  core/src/main/scala-2/chisel3/experimental/hierarchy/HierarchyPackage.scala
  core/src/main/scala-2/chisel3/experimental/hierarchy/Instantiate.scala
  core/src/main/scala-2/chisel3/internal/SourceInfoFileResolver.scala
  core/src/main/scala-2/chisel3/internal/SourceInfoMacro.scala
  core/src/main/scala/chisel3/AggregateImpl.scala
  core/src/main/scala/chisel3/BitsImpl.scala
  core/src/main/scala/chisel3/PrintfImpl.scala
  core/src/main/scala/chisel3/VerificationStatementImpl.scala
  core/src/main/scala/chisel3/experimental/Trace.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/package.scala
  plugin/src/main/scala/chisel3/internal/sourceinfo/SourceInfoFileResolver.scala
Labels: API Modification, Scala 3

#4507 Restore common scalacOptions to project chisel
  build.sc
Labels: Internal

#4508 Add new InlineAllInstances trait
  src/main/scala/chisel3/util/experimental/Inline.scala
  src/test/scala/chiselTests/InlineSpec.scala
Labels: Feature

#4511 fix: fix wrong mill source layout
  build.sc
Labels: Bugfix, Please Merge

#4513 Bump emitted FIRRTL to 4.1.0
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Backend Code Generation

#4519 Refactor Lookupable
  build.sbt
  build.sc
  core/src/main/scala/chisel3/experimental/hierarchy/core/IsInstantiable.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/experimental/hierarchy/package.scala
  docs/src/cookbooks/hierarchy.md
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Deprecation

#4494 feat: add CIRCTSRAMInterface
  src/main/scala/chisel3/util/experimental/CIRCTSRAMInterface.scala
  src/test/scala/chiselTests/experimental/CIRCTSRAMInterfaceSpec.scala
Labels: Feature, Please Merge

#4525 fix: fix while loop in ReverseImpl
  src/main/scala/chisel3/util/BitwiseImpl.scala
Labels: Bugfix, Please Merge

#4529 Update CD permissions for uploading release artifacts
  .github/workflows/release-notes.yml
  .github/workflows/scala-cli-example.yml
Labels: Internal

#4528 Rename localPrefixAppliesToSelf to localModulePrefixAppliesToSelf
  core/src/main/scala/chisel3/ModuleImpl.scala
  docs/src/explanations/moduleprefix.md
  src/test/scala/chiselTests/ModulePrefixSpec.scala
Labels: No Release Notes

#4532 Add APIs to omit module prefix separator
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  docs/src/explanations/moduleprefix.md
  src/test/scala/chiselTests/ModulePrefixSpec.scala
Labels: Feature

#4535 fix: fix mask granularity in CIRCTSRAMInterface
  src/main/scala/chisel3/util/experimental/CIRCTSRAMInterface.scala
  src/test/scala/chiselTests/experimental/CIRCTSRAMInterfaceSpec.scala
Labels: Bugfix, Please Merge

#4533 [CI] Run tests in parallel
  .github/workflows/test.yml
Labels: Please Merge, Internal
