Repository chipsalliance/chisel, pull requests merged in 2024-08, with the labels that each got.

#4226 Bundle elements ordering fix
  core/src/main/scala/chisel3/Aggregate.scala
  plugin/src/main/scala/chisel3/internal/plugin/BundleComponent.scala
  src/test/scala/chiselTests/BundleElementsSpec.scala
Labels: API Modification

#4326 Add common layers to Chisel
  src/main/scala/chisel3/layers/Layers.scala
  src/main/scala/chisel3/layers/package.scala
Labels: Feature

#4327 Add skipIfAlreadyInBlock arg to layer.block
  core/src/main/scala/chisel3/Layer.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Feature

#4329 [binder] Support generic intrinsic emission
  lit/tests/Converter/Circuit.sc
  lit/tests/Converter/Debug.sc
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: Please Merge, No Release Notes

#4321 Represent SRAM Mask as Data
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Please Merge, Internal

#4330 [cd] Guard cd-circt PR on llvm-firtool publish to Maven
  .github/scripts/check-maven-for-llvm-firtool-version.sh
  .github/workflows/cd-circt.yml
Labels: Internal

#4331 Improve the error message for mismatched types in Mux
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/MuxSpec.scala
Labels: Documentation

#4333 Move common layers into core/
  core/src/main/scala/chisel3/layers/Layers.scala
  core/src/main/scala/chisel3/layers/package.scala
  src/main/scala/chisel3/layers/Layers.scala
Labels: No Release Notes

#4300 Layers: Add support for inline convention.
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  docs/src/explanations/layers.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chisel3/TypeEquivalenceSpec.scala
  src/test/scala/chiselTests/LayerSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
  src/test/scala/chiselTests/simulator/EphemeraSimulatorSpec.scala
  src/test/scala/chiselTests/simulator/LayerControlSpec.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
  src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: API Modification

#4337 Support BoringUtils.bore on OpaqueType wrapping a Property.
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Bugfix

#4341 Visit layerblocks in aop.Select methods
  src/main/scala/chisel3/aop/Select.scala
Labels: Bugfix

#4346 Add skipIfLayersEnabled param to layer.block
  core/src/main/scala/chisel3/Layer.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Feature

#4323 Add layer specification to LTL, verification ops
  core/src/main/scala/chisel3/VerificationStatement.scala
  src/main/scala/chisel3/ltl/LTL.scala
  src/test/scala/chiselTests/DataEqualitySpec.scala
  src/test/scala/chiselTests/LTLSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: API Modification

#4348 Add layer.elideBlocks API
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Feature

#4349 Make layer.addLayer API public
  core/src/main/scala/chisel3/Layer.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Feature

#4347 Add Property expression for list concatenation.
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#4352 Add support for circt.OutputDirAnnotation.
  src/main/scala/circt/OutputDirAnnotation.scala
  src/test/scala/circtTests/OutputDirAnnotationSpec.scala
Labels: Feature

#4350 Add default layers that are always emitted
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/layers/package.scala
  docs/src/explanations/layers.md
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Backend Code Generation

#4356 Add test, docs of layer reparenting, NFC
  docs/src/explanations/layers.md
  src/test/scala/chiselTests/LayerSpec.scala
Labels: No Release Notes

#4358 Make '--module' support arguments
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala
  src/test/scala/circtTests/stage/ChiselMainSpec.scala
Labels: Feature

#4359 Fix Arg.name and earlyLocalName for probes
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Bugfix

#4205 Fix ActualDirection calculation from SpecifiedDirection
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/Direction.scala
Labels: Bugfix

#4362 Add DataMirror API for currentInstancePorts.
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature

#4363 Add experimental Select APIs for current instances in a BaseModule.
  src/main/scala/chisel3/aop/Select.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: Feature

#4364 Add `Path.apply()` to support `HasTarget`
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#4365 [website] Update docusaurus 3.1.1 => 3.5.2
  website/package.json
Labels: Documentation

#4298 Add property support to SRAMInterface-based SRAM
  core/src/main/scala/chisel3/properties/Path.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: API Modification

#4368 Change Path to emit relative targets
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: API Modification

#4369 Add utility for pretty Verilog emission in mdoc
  docs-target/src/main/scala/chisel3/docs/package.scala
  docs/src/appendix/experimental-features.md
  docs/src/cookbooks/cookbook.md
  docs/src/cookbooks/dataview.md
  docs/src/cookbooks/hierarchy.md
  docs/src/cookbooks/naming.md
  docs/src/explanations/bundles-and-vecs.md
  docs/src/explanations/chisel-enum.md
  docs/src/explanations/chisel-type-vs-scala-type.md
  docs/src/explanations/connectable.md
  docs/src/explanations/connection-operators.md
  docs/src/explanations/dataview.md
  docs/src/explanations/interfaces-and-connections.md
  docs/src/explanations/layers.md
  docs/src/explanations/naming.md
  docs/src/explanations/polymorphism-and-parameterization.md
  docs/src/explanations/ports.md
  docs/src/explanations/warnings.md
Labels: Documentation

#4370 make SRAM description value optional in SRAMInterface
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: API Modification

#4371 Add -default-layer-specialization=enable to Scala CLI example
  .github/workflows/build-scala-cli-example/chisel-example.scala
Labels: No Release Notes

#4378 [simulator] Switch ChiselSim to use new Layer ABI
  src/main/scala/chisel3/simulator/LayerControl.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chiselTests/simulator/LayerControlSpec.scala
Labels: Dependency Update
