Repository chipsalliance/chisel, pull requests merged in 2024-10, with the labels that each got.

#4432 Enable -Xsource:3 on the `docs` project.
  build.sbt
  docs/src/cookbooks/dataview.md
  docs/src/explanations/dataview.md
  docs/src/explanations/intrinsics.md
  docs/src/explanations/layers.md
Labels: Documentation

#4436 Add SourceLocator for Sequence
  src/main/scala/chisel3/ltl/LTL.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Feature

#4435 fix: wrap all intrinsics in layerblocks
  src/main/scala/chisel3/ltl/LTL.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Bugfix

#4438 Switch publishing to use Mill
  .github/workflows/build-scala-cli-example.yml
  .github/workflows/ci.yml
  build.sc
Labels: Please Merge, Internal

#4439 chore: Updating JDK-related docs for macOS Homebrew
  docs/src/installation.md
Labels: Documentation

#4442 Save/restore when+layer stack w/D/I, fix crashes.
  core/src/main/scala/chisel3/ModuleImpl.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Bugfix

#4445 Make it legal to extract zero bits from a zero-width UInt
  core/src/main/scala/chisel3/BitsImpl.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Bugfix

#4451 Fix Boring.rwTap on instance ports
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#4453 BoringUtilsTapSpec: remove debugging print
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Internal

#4443 Introduce Blocks, track, use for improved scope checking and boring
  core/src/main/scala/chisel3/DataImpl.scala
  core/src/main/scala/chisel3/Intrinsic.scala
  core/src/main/scala/chisel3/MemImpl.scala
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/probe/PackageImpl.scala
  core/src/main/scala/chisel3/probe/ProbeValueBase.scala
  core/src/main/scala/chisel3/properties/Class.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/choice/ModuleChoiceImpl.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
  src/test/scala/chiselTests/WhenSpec.scala
Labels: Internal

#4449 [Scala3] Refactor Printf and VerificationStatement macros
  core/src/main/scala-2/chisel3/PrintfMacros.scala
  core/src/main/scala-2/chisel3/VerificationStatementMacros.scala
  core/src/main/scala/chisel3/Printf.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
Labels: API Modification, Scala 3

#4455 Support creation of `Path`s from `HasTarget`s
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#4456 Block: close earlier, ArraySeq builder and store result, drop unused owner field
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Class.scala
Labels: Performance

#4454 Fix addAttribute and add AttributesAnnotationSpec
  src/main/scala/chisel3/util/AttributeAnnotation.scala
  src/test/scala/chiselTests/util/AttributeAnnotationSpec.scala
Labels: Bugfix, Please Merge

#4458 Fix Select.attachedTo
  src/main/scala/chisel3/aop/Select.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: Bugfix

#4434 Layers: color check all not any and don't consider enabled layers.
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/probe/PackageImpl.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Bugfix

#4437 switch SRAMDescription to Class
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Feature

#4462 [mill] Copy scalacOptions over to mill, add instructions to CONTRIBUTING
  CONTRIBUTING.md
  build.sc
  common.sc
  src/test/scala/chiselTests/ChiselEnum.scala
  svsim/src/main/scala/vcs/Backend.scala
  tests.sc
Labels: Internal

#4431 [Scala3] Add core -Xsource:3 for Scala3 cross compilation support
  build.sbt
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/BitsImpl.scala
  core/src/main/scala/chisel3/DataImpl.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Width.scala
  core/src/main/scala/chisel3/connectable/Alignment.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/HasTypeAlias.scala
  core/src/main/scala/chisel3/experimental/Trace.scala
  core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Property.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
Labels: API Modification, Scala 3

#4466 [CI] Use Mill for testing
  .github/workflows/test.yml
  build.sc
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Internal

#4468 [Scala3] [Mill] Add Xsource:3 to core in Mill to match SBT
  build.sc
Labels: API Modification, Scala 3

#4470 Have `HasTarget` paths be `IsMemberPath`
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Backend Code Generation

#4471 Fix missing string interpolators, add -Xlint:missing-interpolator
  build.sc
  core/src/main/scala/chisel3/AggregateImpl.scala
  core/src/main/scala/chisel3/connectable/Connection.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/util/experimental/decode/QMCMinimizer.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Bugfix

#4475 Elide metadata by default, add --include-util-metadata
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: API Modification

#4477 add additionalAnnotations for SerializableModuleElaborator
  src/main/scala/chisel3/experimental/util/SerializableModuleElaborator.scala
Labels: Feature

#4478 Add Probes to .toString Data methods
  core/src/main/scala/chisel3/DataImpl.scala
  src/test/scala/chisel3/TypeEquivalenceSpec.scala
  src/test/scala/chiselTests/DataPrint.scala
  src/test/scala/chiselTests/LayerSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Bugfix

#4481 Implement Lookupable for HasTarget (used by SRAM)
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/package.scala
  src/test/scala/chiselTests/experimental/hierarchy/Annotations.scala
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Feature

#4484 Allow BoringUtils to use existing port in a closed module
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Feature
