Repository chipsalliance/chisel, pull requests merged in 2024-03, with the labels that each got.

#3872 [docs] Update links to point to chipsalliance/chisel-template
  README.md
  docs/src/appendix/upgrading-from-scala-2-11.md
  docs/src/explanations/blackboxes.md
  docs/src/resources.md
Labels: Documentation

#3890 Get ChiselSim working with CIRCT 1.66+
  src/main/scala/chisel3/simulator/package.scala
Labels: Bugfix

#3895 Fix ChiselStage and Builder handling of logging
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  docs/src/cookbooks/cookbook.md
  docs/src/explanations/warnings.md
  firrtl/src/main/scala/logger/Logger.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/Shell.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Bugfix

#3893 [chiselsim] Better fix for CIRCT 1.66- and 1.66+
  src/main/scala/chisel3/simulator/package.scala
Labels: No Release Notes

#3901 Make logger annotations unserializable
  firrtl/src/main/scala/logger/LoggerAnnotations.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Bugfix

#3902 [binder] Specify the new attribute `layers` for `firrtl.instance`
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: Please Merge, Internal, Panama

#3905 Support serializing large (> 2 GiB) annotation files
  firrtl/src/main/scala/firrtl/annotations/JsonProtocol.scala
  firrtl/src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  firrtl/src/test/scala/firrtl/JsonProtocolSpec.scala
Labels: Bugfix

#3904 [binder] Add OM example as a test case
  circtpanamabinding/includeFunctions.txt
  lit/tests/Property/DocExample.sc
  lit/tests/Property/Good.sc
  lit/utility/src/package.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  panamalib/src/PanamaCIRCT.scala
  panamaom/src/PanamaCIRCTOM.scala
Labels: Please Merge, Internal, Panama

#3825 Add ifElseFatal intrinsics; use it for chisel3.assert emission
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
Labels: Backend Code Generation

#3908 Allow BoringUtils.bore to work on probes
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#3909 [CI] Drop GPG action as we aren't using its result.
  .github/workflows/ci.yml
Labels: No Release Notes

#3912 Add a label "chisel3_builtin" to ifElseFatal intrinsic
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala
  src/test/scala/chiselTests/VerificationSpec.scala
Labels: Backend Code Generation

#3916 Revert move to intrinsic for assert due to performance impact
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
Labels: Backend Code Generation

#3917 Rename Scala CLI template to example
  .github/workflows/build-scala-cli-example.yml
  .github/workflows/build-scala-cli-example/chisel-example.scala
  .github/workflows/scala-cli-example.yml
  .github/workflows/scala-cli-template.yml
  .github/workflows/test.yml
  docs/src/installation.md
Labels: Documentation

#3924 remove outdated jextract in nix overlay
  overlay.nix
Labels: Please Merge, Internal

#3921 toBigInt should round identically for Double and BigDecimal
  core/src/main/scala/chisel3/Num.scala
  src/test/scala/chiselTests/LiteralExtractorSpec.scala
Labels: Bugfix

#3928 Fix Data.findFirstTypeMismatch to check all elements of Bundles
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/reflect/CheckTypeEquivalenceSpec.scala
Labels: Bugfix

#3937 Add DeletedPath for targets that no longer exist.
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3940 Some fixes related to OM
  panamaconverter/src/PanamaCIRCTConverter.scala
  panamalib/src/PanamaCIRCT.scala
  panamaom/src/PanamaCIRCTOM.scala
Labels: Please Merge, Internal, Panama

#3935 Fix integration test for PanamaProperty
  lit/tests/Property/Good.sc
Labels: Please Merge, Internal, Panama

#3945 Remove circt.Intrinsic annotation.
  src/main/scala/chisel3/util/circt/ClockGate.scala
  src/main/scala/chisel3/util/circt/IsX.scala
  src/main/scala/chisel3/util/circt/LTLIntrinsics.scala
  src/main/scala/chisel3/util/circt/PlusArgsTest.scala
  src/main/scala/chisel3/util/circt/PlusArgsValue.scala
  src/main/scala/chisel3/util/circt/Synthesis.scala
  src/main/scala/circt/Intrinisic.scala
Labels: API Modification

#3943 Fix incorrect width for negative `SInt` literals
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: Bugfix, Please Merge, Panama

#3947 Add PORT option to `make serve` in website/ subdir.
  website/Makefile
Labels: Please Merge, Internal

#3948 [website] Bump Docusaurus to 3.1.1 and fix broken anchors
  docs/src/appendix/experimental-features.md
  docs/src/cookbooks/cookbook.md
  docs/src/explanations/connectable.md
  docs/src/explanations/memories.md
  docs/src/explanations/warnings.md
  docs/src/resources/faqs.md
  website/docusaurus.config.js
  website/package.json
Labels: Documentation

#3946 Recognize OM evaluator reference value
  circtpanamabinding/includeFunctions.txt
  panamalib/src/PanamaCIRCT.scala
  panamaom/src/PanamaCIRCTOM.scala
Labels: Please Merge, Internal, Panama

#3952 Make firtool options for `elaborateGeneratedModule` in `workspace` parametric
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Labels: Feature

#3958 Specify `desiredName` as `defname` for `extmodule`
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: Please Merge, Internal, Panama
