Repository chipsalliance/chisel, pull requests merged in 2024-05, with the labels that each got.

#4036 Add private Module API and internal DataMirror API for moduleIOs.
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature

#4037 [LTL] Added overloadings for AssertProperty
  src/main/scala/chisel3/ltl/LTL.scala
Labels: Feature

#4039 Update DataMirrorSpec.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: No Release Notes

#4044 Add Scala 2.13.14 to cross-build
  build.sbt
Labels: Dependency Update

#4050 Add 2.12.19 to cross-build
  build.sbt
Labels: Dependency Update

#4049 Bump to Scala 2.13.14
  .github/workflows/build-scala-cli-example/chisel-example.scala
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  build.sbt
  build.sc
  project/plugins.sbt
Labels: Dependency Update

#4054 Register Emit dialect for MLIR context
  circtpanamabinding/includeFunctions.txt
  circtpanamabinding/jextract-headers.h
  circtpanamabinding/linkLibraries.txt
  panamalib/src/PanamaCIRCT.scala
Labels: Please Merge, No Release Notes

#4056 OM evaluator instantiate method returns Option
  lit/tests/Property/DocExample.sc
  lit/tests/Property/Good.sc
  panamaom/src/PanamaCIRCTOM.scala
Labels: Please Merge, No Release Notes

#4059 Deprecate AssertPropertyLike.createIntrinsic
  src/main/scala/chisel3/ltl/LTL.scala
Labels: Deprecation

#4061 [LTL] Fix verif_* -- these are statements not expressions, no ret value.
  src/main/scala/chisel3/util/circt/LTLIntrinsics.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Bugfix

#4062 [LTL] Send generated FIRRTL through to SV to ensure this works.
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Internal

#4060 IntrinsicModule: deprecate in favor of intrinsic expressions.
  build.sbt
  core/src/main/scala/chisel3/experimental/IntrinsicModule.scala
  docs/src/explanations/intrinsics.md
Labels: Deprecation

#4063 Bump dependencies and delete moultingyaml
  build.sbt
  build.sc
Labels: Dependency Update

#4064 checkTypeEquivalence now considers ProbeInfo
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/probe/package.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chisel3/TypeEquivalenceSpec.scala
Labels: API Modification, Please Merge

#4065 Remove input probes in tests
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Internal

#4035 [Formal] Expose Btor2 target
  firrtl/src/main/scala/firrtl/Emitter.scala
  src/main/scala/circt/stage/Annotations.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature

#4071 Fix literal handling for views of empty Aggregates
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Bugfix

#4076 Add modulePorts and fullModulePorts in DataMirror for Instance
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature

#4078 Remove line contents from assertion messages
  core/src/main/scala/chisel3/VerificationStatement.scala
  src/test/scala/chiselTests/Assert.scala
  src/test/scala/chiselTests/VerificationSpec.scala
Labels: Backend Code Generation

#4067 Add .toRelativeTargetToHierarchy
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Hierarchy.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/package.scala
  firrtl/src/main/scala/firrtl/annotations/Target.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
Labels: Feature

#4080 Materialize wires for .ref of Aggregate views
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Bugfix

#4087 [SVSim] Fixed non-firing AssertProperty in SVSim
  src/test/scala/chiselTests/LTLSpec.scala
  svsim/src/main/scala/verilator/Backend.scala
Labels: Bugfix

#4082 Fix widths for literal values in Bundle literals
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: Bugfix

#4084 BoringUtils: Fix tapAndRead to return same type even when not boring.
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#4093 Make it a warning to have too-wide literal values in Bundle Literals
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/internal/Warning.scala
  docs/src/explanations/warnings.md
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: Deprecation

#4083 Fix boring tap of non-passive source from parent.
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#4097 Don't warn when 0.U used as value for 0-bit BundleLit field
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
Labels: Bugfix

#4100 Fix 0 width signals chiselsim
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chiselTests/simulator/OptionalIOModule.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Labels: Bugfix

#4107 Support views of ports in ChiselSim
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Labels: Bugfix

#4105 FixedIO__Modules with various kinds of probe ports
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/FixedIOModuleSpec.scala
Labels: Bugfix

#4116 Bump versions of Github actions to versions using Node 20
  .github/workflows/backport-fixup.yml
  .github/workflows/build-scala-cli-example.yml
  .github/workflows/ci.yml
  .github/workflows/enable-bincompat-checking.yml
  .github/workflows/install-espresso/action.yml
  .github/workflows/install-jextract/action.yml
  .github/workflows/release-notes.yml
  .github/workflows/require-label.yml
  .github/workflows/scala-cli-example.yml
  .github/workflows/setup-oss-cad-suite/action.yml
  .github/workflows/test.yml
Labels: Internal

#4121 Fix svsim with gcc14
  svsim/src/main/resources/simulation-driver.cpp
Labels: Bugfix

#4119 Add and use Mill wrapper script
  .github/workflows/test.yml
  .mill-version
  CONTRIBUTING.md
  benchmark/src/main/scala/chisel3/benchmark/Benchmark.scala
  mill
Labels: Internal
