Repository chipsalliance/chisel, pull requests merged in 2024-12, with the labels that each got.

#4542 The linked PDF at UCB is now behind a login wall. So dropping it.
  docs/src/explanations/interfaces-and-connections.md
Labels: Documentation

#4540 Remove do-apply pattern from Definition and Instance
  core/src/main/scala/chisel3/experimental/SerializableModuleGenerator.scala
  core/src/main/scala/chisel3/experimental/hierarchy/InstantiateImpl.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Labels: API Modification

#4545 Fix auto generated DedupGroups to be sensitive to module prefix
  core/src/main/scala/chisel3/ModuleImpl.scala
  src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
  src/test/scala/chiselTests/ModulePrefixSpec.scala
Labels: Bugfix

#3410 Add FileCheck for unit testing
  .github/workflows/install-filecheck/action.yml
  .github/workflows/test.yml
  SETUP.md
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/DecoupledSpec.scala
Labels: Internal

#4547 [test] Convert LayerSpec to use FileCheck, NFC
  src/test/scala/chiselTests/LayerSpec.scala
Labels: No Release Notes

#4543 fix: evaluate target lazily in Path
  core/src/main/scala/chisel3/properties/Path.scala
  src/test/scala/chiselTests/ToTargetSpec.scala
Labels: Bugfix

#4544 feat: add SRAMBlackBox
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala-2/chisel3/util/SRAM.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Feature, Please Merge

#4551 Fix potential name collision caused by LTL properties
  src/main/scala-2/chisel3/util/circt/LTLIntrinsics.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Bugfix

#4556 fix up wrong build path for panama
  panama.sc
Labels: No Release Notes

#4558 add type safe API to access OM
  panamaom/src/PanamaCIRCTOM.scala
Labels: No Release Notes

#4562 [docs] Document inline layers
  docs/src/explanations/layers.md
Labels: No Release Notes

#4563 [docs] Document layer coloring
  docs/src/explanations/layers.md
Labels: No Release Notes

#4564 Escape special characters in Property String literals
  core/src/main/scala/chisel3/properties/Property.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Bugfix

#4569 Dev/biancolin/fix module choice under di
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  src/test/scala/chiselTests/ModuleChoiceSpec.scala
Labels: Bugfix

#4577 Fix BoringUtils input probe creation
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Bugfix

#4583 Move to FileCheck
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/FixedIOModuleSpec.scala
  src/test/scala/chiselTests/InlineSpec.scala
  src/test/scala/chiselTests/IntrinsicSpec.scala
  src/test/scala/chiselTests/ModuleChoiceSpec.scala
  src/test/scala/chiselTests/ModulePrefixSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/chiselTests/PublicModuleSpec.scala
  src/test/scala/chiselTests/RawModuleSpec.scala
  src/test/scala/chiselTests/experimental/FlatIOSpec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
  src/test/scala/chiselTests/properties/ClassSpec.scala
  src/test/scala/chiselTests/properties/ObjectSpec.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: No Release Notes
