Repository chipsalliance/chisel, pull requests merged in 2024-01, with the labels that each got.

#3704 Fix the `--mlir-print-ir-after-all` option.
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Bugfix, Please Merge

#3702 Bump firtool resolver to 1.2.0
  build.sbt
  build.sc
Labels: Dependency Update

#3700 Share the globalNamespace in the DynamicContext used for Definition.
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Performance

#3683 Add ModuleChoice and Groups
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/choice/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  docs/src/explanations/instchoice.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala/chisel3/choice/ModuleChoice.scala
  src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
  src/test/scala/chiselTests/ModuleChoiceSpec.scala
Labels: Feature

#3713 bump and update nix to use upstreamed packages
  build.sc
  flake.lock
  flake.nix
  nix/espresso.nix
  nix/llvm-lit.nix
  overlay.nix
Labels: Internal

#3719 Bump firtool-resolver to 1.3.0
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/test.yml
  build.sbt
  build.sc
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Dependency Update

#3721 Fix AsyncReset in binder
  binder/src/main/scala/PanamaCIRCTConverter.scala
Labels: Internal

#2886 Add Instance.suggestName
  core/src/main/scala/chisel3/experimental/hierarchy/ModuleClone.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Feature

#3722 [CI] Fix CI flakiness with --server=false
  project/FirtoolVersionsTable.scala
Labels: Internal

#3726 Fix using Definitions as arguments to Definitions
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
Labels: Bugfix

#3727 Promote FlatIO to package chisel3
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/experimental/package.scala
  docs/src/cookbooks/cookbook.md
  src/main/scala/chisel3/FixedIOModule.scala
  src/main/scala/chisel3/interface/Interface.scala
  src/main/scala/chisel3/util/circt/PlusArgsValue.scala
  src/test/scala/chiselTests/ExtModule.scala
  src/test/scala/chiselTests/experimental/FlatIOSpec.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: API Modification

#3728 make SRAM targets accessible from SRAMInterface
  core/src/main/scala/chisel3/package.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Feature

#3733 Delete many old deprecated APIs
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Const.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/IO.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/SourceInfo.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/probe/Probe.scala
  core/src/main/scala/chisel3/probe/package.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/main/scala/chisel3/Driver.scala
  src/main/scala/chisel3/util/MixedVec.scala
  src/main/scala/chisel3/util/Mux.scala
Labels: API Modification

#3734 Bump SBT to 1.9.8 and update Ubuntu runners
  .github/workflows/backport-fixup.yml
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/cd-circt.yml
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/enable-bincompat-checking.yml
  .github/workflows/release-notes.yml
  .github/workflows/require-label.yml
  .github/workflows/scala-cli-template.yml
  .github/workflows/test.yml
  project/build.properties
Labels: Internal

#3736 Clean up Bindings deprecations
  core/src/main/scala/chisel3/internal/Binding.scala
Labels: API Modification

#3738 [CI] Make SBT version handling logic more robust
  build.sbt
  project/FirtoolVersionsTable.scala
  project/Releases.scala
  project/plugins.sbt
Labels: Documentation

#3654 Preserve probe-ness and const-ness in Output() and friends.
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/Direction.scala
Labels: Bugfix

#3745 [docs] Minor updates to README and SETUP for Chisel 6
  README.md
  SETUP.md
  build.sbt
  project/Releases.scala
Labels: Documentation

#3747 Support === on empty Aggregates
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/DataEqualitySpec.scala
Labels: Bugfix

#3751 Enhance release notes automation
  .github/workflows/config/release-notes.json
  .github/workflows/release-notes.yml
Labels: Internal

#3753 Support checking isVisible with reflect.DataMirror
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature, Please Merge

#3752 Shift right produce at least 1 width result
  core/src/main/scala/chisel3/Width.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Please Merge, Internal

#3596 a Pure LLVM Lit test framework
  build.sc
  common.sc
  flake.nix
  lit/tests/CompilerPlugin/WithCompilerPlugin.sc
  lit/tests/CompilerPlugin/WithoutCompilerPlugin.sc
  lit/tests/lit.cfg.py
  lit/tests/lit.site.cfg.py.in
  lit/utility/src/package.scala
  nix/scala-cli.nix
  nix/sources.json
  overlay.nix
  tests.sc
Labels: Internal

#3755 [website] Make links more obvious
  website/src/css/custom.css
Labels: Documentation

#3754 Refactor panama binding and converter framwork
  binder/src/test/scala/BinderSpec.scala
  build.sc
  circtpanamabinding/includeConstants.txt
  circtpanamabinding/includeFunctions.txt
  circtpanamabinding/includeStructs.txt
  circtpanamabinding/includeTypedefs.txt
  circtpanamabinding/includeUnions.txt
  circtpanamabinding/includeVars.txt
  circtpanamabinding/jextract-headers.h
  circtpanamabinding/linkLibraries.txt
  common.sc
  core/src/main/scala/chisel3/internal/CIRCTConverter.scala
  core/src/main/scala/chisel3/internal/CIRCTOM.scala
  core/src/main/scala/chisel3/internal/CIRCTPassManager.scala
  lit/tests/CompilerPlugin/WithCompilerPlugin.sc
  lit/tests/CompilerPlugin/WithoutCompilerPlugin.sc
  lit/tests/SomkeTest.sc
  lit/utility/src/package.scala
  panamaconverter/src/Convert.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  panamaconverter/src/PanamaCIRCTPassManager.scala
  panamalib/src/PanamaCIRCT.scala
  panamaom/src/PanamaCIRCTOM.scala
  tests.sc
Labels: API Modification

#3757 Update Scala CLI Template
  .github/workflows/build-scala-cli-template.yml
  .github/workflows/build-scala-cli-template/chisel-template.scala
Labels: Internal

#3756 [website] Write new Installation doc
  docs/src/appendix.md
  docs/src/cookbooks.md
  docs/src/developers.md
  docs/src/explanations.md
  docs/src/index.md
  docs/src/installation.md
  docs/src/resources.md
  website/Makefile
  website/docusaurus.config.js
  website/sidebars.js
  website/src/pages/index.js
Labels: Documentation

#3763 Setup main for Chisel 7
  .github/PULL_REQUEST_TEMPLATE.md
  .github/configs/mergify_config.yml
  .mergify.yml
  project/previous-versions.txt
Labels: No Release Notes

#3762 Homebrew sbt for MacOS
  docs/src/installation.md
Labels: Documentation

#3764 [docs] Remove SETUP.md in favor of website Installation page
  README.md
  SETUP.md
Labels: Documentation

#3765 Add DataMirror.getLayerColor
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature

#3766 Add OM test, support iterating fields of a OM object
  circtpanamabinding/includeFunctions.txt
  flake.lock
  lit/tests/OMTest.sc
  lit/tests/SmokeTest.sc
  lit/utility/src/package.scala
  panamalib/src/PanamaCIRCT.scala
  panamaom/src/PanamaCIRCTOM.scala
Labels: Internal, Panama

#3714 Provide ImplicitClock and ImplicitReset
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/MultiClock.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/package.scala
  docs/src/cookbooks/cookbook.md
  src/test/scala/chiselTests/Clock.scala
  src/test/scala/chiselTests/ClockSpec.scala
  src/test/scala/chiselTests/ResetSpec.scala
Labels: Feature

#3770 [CI] Configure Mergify to use chiselbot as bot account
  .github/mergify/gen-config.sc
  .mergify.yml
Labels: No Release Notes

#3774 [docs] Make Quickstart instructions more clear
  docs/src/installation.md
Labels: Documentation

#3775 Fix `Reg()` to properly handle clocks as rvalues
  core/src/main/scala/chisel3/Reg.scala
  src/test/scala/chiselTests/ClockSpec.scala
Labels: Bugfix

#3785 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#3782 Support isLit for Property types.
  core/src/main/scala/chisel3/properties/Property.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3783 Support isProperty query in DataMirror.
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Feature

#3784 Support Property in BoringUtils.
  core/src/main/scala/chisel3/RawModule.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Feature

#3781 [docs] Generate ToC for Cookbooks
  docs/src/cookbooks/cookbook.md
  docs/src/cookbooks/dataview.md
  docs/src/cookbooks/hierarchy.md
  docs/src/cookbooks/naming.md
  docs/src/cookbooks/serialization.md
  website/src/css/custom.css
Labels: Documentation

#3793 [CI] Configure Mergify to use chiselbot more
  .github/mergify/gen-config.sc
  .mergify.yml
Labels: No Release Notes

#3792 Add a new DynamicObject.apply method to create Class instances.
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Object.scala
  src/test/scala/chiselTests/properties/ObjectSpec.scala
Labels: Feature

#3799 Allow modules to globally enable layers
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
  firrtl/src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
  src/main/scala/chisel3/aop/injecting/InjectingPhase.scala
  src/test/scala/chiselTests/LayerSpec.scala
  src/test/scala/circtTests/stage/phases/AddImplicitOutputFileSpec.scala
Labels: Feature

#3803 Bump to FIRRTL 4.0.0
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/ExtModuleTests.scala
  src/test/scala/chiselTests/LayerSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Backend Code Generation
