Repository chipsalliance/chisel, pull requests merged in 2024-07, with the labels that each got.

#4232 Add ChiselStage.emitCHIRRTLFile
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature

#4219 Emit FIRRTL bulk connects even for "input" wires
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/BulkConnectSpec.scala
Labels: Bugfix

#4200 Fix width of ChiselEnum values in emitted FIRRTL
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/circt/stage/Shell.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: API Modification

#4237 [LTL] Deprecate disable intrinsic
  build.sbt
  src/main/scala/chisel3/ltl/LTL.scala
Labels: Deprecation

#4238 Share ChildBinding objects between siblings
  core/src/main/scala/chisel3/Aggregate.scala
Labels: Performance

#4168 Preserve literals across .asTypeOf
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Clock.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/warnings.md
  src/test/scala/chiselTests/AsTypeOfTester.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/ChiselEnum.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
  src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
Labels: API Modification

#4243 Make requireTypeEquivalent public and add context message
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  src/test/scala/chisel3/TypeEquivalenceSpec.scala
Labels: Feature

#4248 Use :<>= in VecInit methods instead of := or <>
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/Vec.scala
Labels: Bugfix

#4256 Fix import path in docstring
  src/main/scala/chisel3/ltl/LTL.scala
Labels: Documentation

#4255 Add map method for Valid
  src/main/scala/chisel3/util/Valid.scala
  src/test/scala/chiselTests/ValidSpec.scala
Labels: Feature

#4249 SourceInfo: simplify the common case for makeMessage, print it differently
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/experimental/SourceInfo.scala
  core/src/main/scala/chisel3/experimental/dataview/DataView.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/main/scala/chisel3/simulator/PeekPokeAPI.scala
  src/test/scala/chiselTests/SourceLocatorSpec.scala
  src/test/scala/chiselTests/WhenSpec.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Labels: API Modification

#4252 Remove autoSeedVar, use Boolean to distinguish suggested or autoSeed
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Performance

#4253 Move circuitVar from HasId to BaseModule
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Performance

#4251 Micro-optimize Direction
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
Labels: API Modification

#4254 Optimize Record._elements to not duplicate VectorMap if possible
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/RecordSpec.scala
Labels: Performance

#4260 Fix .toString for dynamic indexing
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala/chiselTests/DataPrint.scala
Labels: Bugfix

#4269 Add more information when probe types don't match
  core/src/main/scala/chisel3/probe/package.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Feature

#4259 Share Node objects between siblings
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/properties/Object.scala
Labels: Performance

#4271 Optimize .readOnly to only create views when necessary
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/ReadOnlySpec.scala
Labels: Performance

#4268 Specialize Index for literal indices with LitIndex
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/DataPrint.scala
  src/test/scala/chiselTests/Vec.scala
Labels: Performance

#4275 Fix emitted FIRRTL for dynamic index of size 0 Vec
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/Vec.scala
Labels: No Release Notes

#4135 Update upickle to 3.3.1
  build.sbt
  build.sc
Labels: Dependency Update

#4283 Add AffectsChiselName
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
Labels: Feature

#4284 Properly handle OpaqueTypes in SRAM mask
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Bugfix

#4295 [firrtl] Emit commas for smem/cmem
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
Labels: No Release Notes

#4294 Update versioning.md - typo
  docs/src/appendix/versioning.md
Labels: Please Merge, No Release Notes

#4287 Update chiseltest uses version to 6.0 in documentation
  README.md
Labels: Documentation

#4301 Emit Layers when using D/I
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Bugfix

#4302 Cleanup LayerSpec tests, NFC
  src/test/scala/chiselTests/LayerSpec.scala
Labels: No Release Notes

#4303 Use Region for Layer Blocks
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
Labels: No Release Notes

#4304 Create layer blocks on demand
  core/src/main/scala/chisel3/Layer.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: API Modification

#4306 Remove annotations from ChiselSpec methods
  integration-tests/src/test/scala/chiselTest/LFSRSpec.scala
  src/test/scala/chiselTests/AnalogIntegrationSpec.scala
  src/test/scala/chiselTests/AnalogSpec.scala
  src/test/scala/chiselTests/BlackBox.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/ExtModule.scala
  src/test/scala/chiselTests/MultiClockSpec.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
  src/test/scala/examples/SimpleVendingMachine.scala
Labels: No Release Notes

#4307 [simulator] Enable all layers for simulation
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/Workspace.scala
  svsim/src/main/scala/vcs/Backend.scala
  svsim/src/main/scala/verilator/Backend.scala
Labels: API Modification

#4309 Remove unnecessary overrides of lref and ref in Property
  core/src/main/scala/chisel3/properties/Property.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Bugfix

#4308 Handle define on views of Probes
  core/src/main/scala/chisel3/probe/package.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Bugfix

#4315 Run CD (firtool) more frequently
  .github/workflows/cd-circt.yml
Labels: No Release Notes

#4312 [simulator] Add LayerControl infra
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/LayerControl.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/simulator/EphemeraSimulatorSpec.scala
  src/test/scala/chiselTests/simulator/LayerControlSpec.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/Workspace.scala
Labels: No Release Notes

#4317 Fix svsim DPI function template
  svsim/src/main/scala/Workspace.scala
Labels: Bugfix

#4322 Add --remap-layers to ChiselStage
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/probe/Probe.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Checks.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/circt/stage/Shell.scala
  src/test/scala/chiselTests/stage/ChiselAnnotationsSpec.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature
