Repository chipsalliance/chisel, pull requests merged in 2024-09, with the labels that each got.

#4381 Remove Path from SRAMDescription as it isn't fully functional
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: No Release Notes

#4383 [mill] Enhance Mill flow to download jextract and circt-full
  .github/workflows/install-jextract/action.yml
  .github/workflows/test.yml
  build.sc
  common.sc
  flake.nix
Labels: Internal

#4384 [mill] Get unit testing working
  build.sc
  firrtl/src/test/scala/firrtlTests/FileUtilsSpec.scala
  tests.sc
Labels: Internal

#4023 Add Attribute annotation back to chisel in-tree firrtl
  firrtl/src/main/scala/firrtl/AttributeAnnotation.scala
  firrtl/src/test/scala/firrtlTests/annotationTests/AttributeAnnotationSpec.scala
  src/main/scala/chisel3/util/AttributeAnnotation.scala
Labels: Feature

#4391 Improve error messages for empty Mux1H and PriorityMux
  core/src/main/scala/chisel3/SeqUtils.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/util/PriorityMuxSpec.scala
Labels: Bugfix

#4395 Select.collectDeep and related: search into layers and whens
  src/main/scala/chisel3/aop/Select.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: Bugfix

#4399 Flush staged commands before/after enter/exit regions.
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#4407 Module: reset layerStack
  core/src/main/scala/chisel3/ModuleImpl.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Bugfix

#4409 feat: implement SerializableModuleElaborator
  src/main/scala/chisel3/experimental/util/SerializableModuleElaborator.scala
  src/test/scala/chiselTests/experimental/SerializableModuleElaboratorSpec.scala
Labels: Feature, Please Merge

#4410 Add Scala 2.13.15 to compiler plugin cross-build
  build.sbt
Labels: Dependency Update

#4414 Bump to Scala 2.13.15
  .github/workflows/build-scala-cli-example/chisel-example.scala
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  build.sbt
  build.sc
Labels: Dependency Update

#4415 Deprecate all Injecting Aspect Code
  build.sbt
  core/src/main/scala/chisel3/ModuleAspect.scala
  src/main/scala/chisel3/aop/injecting/InjectStatement.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/aop/injecting/InjectingPhase.scala
  src/main/scala/chisel3/stage/phases/MaybeInjectingPhase.scala
Labels: API Modification

#4417 Remove Injecting Aspects
  build.sbt
  core/src/main/scala/chisel3/ModuleAspect.scala
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/aop/injecting/InjectStatement.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/aop/injecting/InjectingPhase.scala
  src/main/scala/chisel3/stage/phases/Convert.scala
  src/main/scala/chisel3/stage/phases/Emitter.scala
  src/main/scala/chisel3/stage/phases/MaybeInjectingPhase.scala
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/main/scala/chisel3/verilog.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/chiselTests/aop/InjectionSpec.scala
  src/test/scala/chiselTests/aop/SelectSpec.scala
Labels: API Modification

#4420 Deprecate more Aspect parts
  build.sbt
  core/src/main/scala/chisel3/aop/Aspect.scala
  src/main/scala/chisel3/aop/AspectLibrary.scala
  src/main/scala/chisel3/aop/inspecting/InspectingAspect.scala
  src/main/scala/chisel3/stage/phases/AspectPhase.scala
  src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
Labels: Deprecation

#4419 Add documentation for CIRCT Converter
  CONTRIBUTING.md
Labels: No Release Notes

#4422 [mill] Add ScalafmtModule to all tests
  build.sc
  firrtl/src/test/scala/firrtlTests/FileUtilsSpec.scala
Labels: No Release Notes

#4424 Remove aspects
  build.sbt
  core/src/main/scala/chisel3/aop/Aspect.scala
  src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary
  src/main/scala/chisel3/aop/AspectLibrary.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/aop/inspecting/InspectingAspect.scala
  src/main/scala/chisel3/stage/phases/AspectPhase.scala
  src/main/scala/chisel3/stage/phases/MaybeAspectPhase.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/chiselTests/ChiselSpec.scala
Labels: API Modification

#4430 Add svsim -Xsource:3 for Scala3 cross compilation support
  build.sbt
Labels: API Modification
