Repository chipsalliance/chisel, pull requests merged in 2024-06, with the labels that each got.

#4131 Update sbt-buildinfo to 0.12.0
  project/plugins.sbt
Labels: Internal

#4142 Don't ... top of stack trace if it isn't actually trimmed
  core/src/main/scala/chisel3/internal/Error.scala
  src/test/scala/circtTests/stage/ChiselStageSpec.scala
Labels: Feature

#4120 [LTL] Add support for new sequence and property ops
  src/main/scala/chisel3/ltl/LTL.scala
  src/main/scala/chisel3/util/circt/LTLIntrinsics.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Feature

#4144 PeekPokeAPI: include source location on failed expect() calls.
  core/src/main/scala/chisel3/internal/Error.scala
  src/main/scala/chisel3/simulator/PeekPokeAPI.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Labels: Feature

#4148 Preserve literals across .asUInt
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/BundleLiteralSpec.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
  src/test/scala/chiselTests/VecLiteralSpec.scala
Labels: Feature

#4151 Preserve literal value across .asSInt and .zext
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Feature

#4147 Suppress exception throwing in Data.toString
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/DataPrint.scala
Labels: Bugfix

#4156 Preserve UInt and SInt literals across .pad
  core/src/main/scala/chisel3/Bits.scala
  src/test/scala/chiselTests/ProbeSpec.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Feature

#4161 Add a test for issue 4159
  src/test/scala/chiselTests/ChiselEnum.scala
Labels: Documentation

#4167 [5.x] Remove website CI/CD
  .github/workflows/test.yml
Labels: Documentation

#4160 Add more exhaustive tests for .asTypeOf
  src/test/scala/chiselTests/AsTypeOfTester.scala
Labels: Documentation

#4171 Bump nix flake
  flake.lock
Labels: Please Merge, No Release Notes

#4175 Error when calling define targeting a child of a probe
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/probe/package.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Bugfix

#4178 make TruthTable in DecodeTable lazy
  src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala
Labels: Please Merge, Performance

#4181 Support XMRs to Analog in D/I
  core/src/main/scala/chisel3/experimental/Analog.scala
  src/test/scala/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Bugfix

#4177 Make "deprecated public" binding APIs private
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/Intrinsic.scala
  core/src/main/scala/chisel3/Mem.scala
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/Reg.scala
  core/src/main/scala/chisel3/connectable/Alignment.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/experimental/OpaqueType.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/probe/ProbeValue.scala
  core/src/main/scala/chisel3/probe/package.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Object.scala
  core/src/main/scala/chisel3/properties/Property.scala
  core/src/main/scala/chisel3/reflect/DataMirror.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/main/scala/chisel3/choice/ModuleChoice.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
Labels: API Modification

#4186 Distinguish identity views from single-target views
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chisel3/experimental/dataview/ReifySpec.scala
  src/test/scala/chiselTests/BulkConnectSpec.scala
Labels: Bugfix

#4184 Rework When IR to be Region-based
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/internal/CIRCTConverter.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/main/scala/chisel3/aop/Select.scala
Labels: No Release Notes

#4188 Add Region to Chisel IR
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
Labels: No Release Notes

#4191 Remove ConnectInit
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: No Release Notes

#4192 Merge two conditional due to same body
  plugin/src/main/scala/chisel3/internal/plugin/ChiselComponent.scala
Labels: Internal

#4190 Add support for marking things as readOnly
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  core/src/main/scala/chisel3/internal/BiConnect.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/probe/package.scala
  core/src/main/scala/chisel3/properties/Property.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala/chisel3/experimental/dataview/ReifySpec.scala
  src/test/scala/chiselTests/ReadOnlySpec.scala
Labels: Feature

#4195 Initialize scala.util.control.NonFatal in Builder
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: Bugfix

#4198 Mark return value of .asTypeOf as "deprecated read-only"
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/Warning.scala
  docs/src/explanations/warnings.md
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
Labels: Deprecation

#4213 [3.6.x] Modernize Release Flow
  .github/workflows/backport-fixup.yml
  .github/workflows/build-scala-cli-example/action.yml
  .github/workflows/enable-bincompat-checking.yml
  .github/workflows/install-espresso/action.yml
  .github/workflows/release-notes.yml
  .github/workflows/scala-cli-example.yml
  .github/workflows/setup-oss-cad-suite/action.yml
  .github/workflows/test.yml
  build.sbt
  project/previous-versions.txt
Labels: Internal

#4210 Update mill-main to 0.11.8
  .mill-version
Labels: Internal

#4211 Update scalatest to 3.2.19
  build.sbt
  build.sc
Labels: Internal

#4212 Update scalacheck-1-18 to 3.2.19.0
  build.sbt
  build.sc
Labels: Internal

#4220 Fix BoringUtils for identity views
  core/src/main/scala/chisel3/RawModule.scala
  src/test/scala/chiselTests/BoringUtilsTapSpec.scala
Labels: Bugfix

#4216 make FixedIOBaseModule.io public
  src/main/scala/chisel3/FixedIOModule.scala
  src/test/scala/chiselTests/FixedIOModuleSpec.scala
Labels: Bugfix

#4222 Name the targets of identity views
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/Vec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
Labels: Bugfix

#4227 Elide else skip in FIRRTL for whens with no otherwise
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  src/test/scala/chiselTests/WhenSpec.scala
Labels: No Release Notes

#4228 Make isView safe outside of Builder context
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Bugfix
