Repository chipsalliance/chisel, pull requests merged in 2024-02, with the labels that each got.

#3805 Add SoC-Now to community projects.
  website/src/pages/community.md
Labels: Documentation

#3804 Report source locator in when scoping error messages
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  src/test/scala/chiselTests/WhenSpec.scala
Labels: Bugfix

#3813 Add Public trait to create public FIRRTL modules
  core/src/main/scala/chisel3/Public.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/package.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
  firrtl/src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
  src/main/scala/chisel3/aop/injecting/InjectingPhase.scala
  src/test/scala/chiselTests/PublicModuleSpec.scala
  src/test/scala/circtTests/stage/phases/AddImplicitOutputFileSpec.scala
Labels: Feature

#3814 Remove Makefile
  Makefile
Labels: Internal

#3815 [docs] Minor updates to developer docs
  docs/src/developers.md
  docs/src/developers/sbt-subproject.md
  docs/src/developers/scaladoc.md
Labels: Documentation

#3817 Revert "Shift right produce at least 1 bit width result (#3752)"
  core/src/main/scala/chisel3/Width.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: No Release Notes

#3818 Fix visibility for views
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  src/test/scala/chiselTests/reflect/DataMirrorSpec.scala
Labels: Bugfix

#3826 Make `SRAMInterface` parameters publicly available
  src/main/scala/chisel3/util/SRAM.scala
Labels: Feature

#3829 [svsim] Better error message when verilator not on PATH
  svsim/src/main/scala/verilator/Backend.scala
Labels: Bugfix

#3824 Change the width of static shift right
  core/src/main/scala/chisel3/Bits.scala
  core/src/main/scala/chisel3/Width.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: API Modification

#3830 Remove extra bit from `SRAMInterface` address width
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/Mem.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Bugfix

#3841 Static shift right width change part 2
  core/src/main/scala/chisel3/Bits.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: No Release Notes

#3810 Add Property expressions, starting with addition.
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3844 Add Property expression for integer multiplication.
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3802 Add format strings to assert and assume
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: Backend Code Generation

#3846 Add Property expression for integer shift right.
  core/src/main/scala/chisel3/properties/Property.scala
  docs/src/explanations/properties.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  src/test/scala/chiselTests/properties/PropertySpec.scala
Labels: Feature

#3852 de-bump to sbt 1.9.7
  docs/src/installation.md
  project/build.properties
Labels: Dependency Update

#3857 Relax legality of defines, align with FIRRTL spec
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/internal/package.scala
  core/src/main/scala/chisel3/probe/package.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Bugfix

#3855 Bump to firtool-resolver 2.0.0
  build.sbt
  build.sc
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/main/scala/circt/stage/phases/ScribeInterop.scala
Labels: API Modification

#3856 Add DataProduct for Iterables and primitive types
  core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Feature

#3858 [docs] Improve firtool versioning table
  build.sbt
  docs/src/appendix/versioning.md
  project/FirtoolVersionsTable.scala
Labels: Documentation

#3868 [ci] Update `jextract` download URL
  .github/workflows/install-jextract/action.yml
Labels: Please Merge, Internal

#3869 Fix tests to avoid inferred width ports on public modules.
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/SIntOps.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: API Modification

#3871 [website] Update chisel-template repo link to chipsalliance
  build.sbt
Labels: Documentation

#3870 [docs] Add initial ChiselTest migration doc
  build.sbt
  docs/src/appendix/migrating-from-chiseltest.md
  docs/src/installation.md
Labels: Documentation

#3875 [docs] Fix ChiselTest migration doc
  .github/workflows/test.yml
  docs/src/appendix/migrating-from-chiseltest.md
Labels: Documentation

#3877 Add getClassType API to Definition[T <: Class].
  core/src/main/scala/chisel3/properties/Class.scala
  src/test/scala/chiselTests/properties/ClassSpec.scala
Labels: Feature

#3878 Assume: Use plain FIRRTL assume + format string instead of printf + assume.
  core/src/main/scala/chisel3/VerificationStatement.scala
  src/test/scala/chiselTests/VerificationSpec.scala
Labels: Backend Code Generation

#3881 Add `suggestName` method to `HasTarget`
  core/src/main/scala/chisel3/package.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Feature

#3876 Use c++14 to pass the verilator check
  svsim/src/main/scala/verilator/Backend.scala
Labels: Dependency Update

#3880 Add explanation for Class and Object, with examples.
  docs/src/explanations/properties.md
Labels: Documentation

#3886 Print the optional Printable passed to stop ops
  core/src/main/scala/chisel3/VerificationStatement.scala
  src/test/scala/chiselTests/Stop.scala
Labels: Feature
