Repository chipsalliance/chisel, pull requests merged in 2024-04, with the labels that each got.

#3956 Removed FixedPoint reference in muxes-and-input-selection.md
  docs/src/explanations/muxes-and-input-selection.md
Labels: Documentation

#3955 Make SRAMs directly emit FIRRTL memories
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/RawModule.scala
  core/src/main/scala/chisel3/SramTarget.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/internal/Binding.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/main/scala/chisel3/aop/Select.scala
  src/main/scala/chisel3/util/SRAM.scala
  src/test/scala/chiselTests/Mem.scala
  src/test/scala/chiselTests/util/SRAMSpec.scala
Labels: Backend Code Generation

#3960 Add a new BoringUtils.drive API for boring to drive a sink.
  core/src/main/scala/chisel3/RawModule.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Feature

#3964 Support literals in DataView
  core/src/main/scala/chisel3/Aggregate.scala
  core/src/main/scala/chisel3/Element.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala/chiselTests/experimental/DataView.scala
Labels: Bugfix

#3968 Add requireIsAnnotatable for better errors when annotating literals
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/package.scala
  core/src/main/scala/chisel3/package.scala
  src/main/scala/chisel3/util/experimental/decode/decoder.scala
  src/test/scala/chiselTests/DontTouchSpec.scala
Labels: Feature

#3976 Update firtool emission option for verification flavors
  circtpanamabinding/includeConstants.txt
  circtpanamabinding/includeFunctions.txt
  panamalib/src/FirtoolOptions.scala
  panamalib/src/PanamaCIRCT.scala
  panamalib/src/PanamaFirtoolOption.scala
Labels: Please Merge, Internal, No Release Notes, Panama

#3979 Fix === for abstract Reset types
  core/src/main/scala/chisel3/Data.scala
  src/test/scala/chiselTests/DataEqualitySpec.scala
Labels: Bugfix

#3984 Add layers for colored probe types or enablelayer
  core/src/main/scala/chisel3/Layer.scala
  core/src/main/scala/chisel3/probe/Probe.scala
  src/test/scala/chiselTests/LayerSpec.scala
  src/test/scala/chiselTests/ProbeSpec.scala
Labels: Bugfix

#3985 [svsim] Expose further verilator options for trace file name and simulation speed optimization
  src/main/scala/chisel3/simulator/package.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/Simulation.scala
  svsim/src/main/scala/Workspace.scala
  svsim/src/main/scala/vcs/Backend.scala
  svsim/src/main/scala/verilator/Backend.scala
Labels: API Modification

#3978 Add extension points on Data for customizing Connectable behavior.
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/connectable/package.scala
  src/test/scala/chiselTests/ConnectableSpec.scala
Labels: Feature

#3988 Optimize BitPat factory from UInt literals
  src/main/scala/chisel3/util/BitPat.scala
  src/test/scala/chiselTests/util/BitPatSpec.scala
Labels: Performance

#3987 Add reference benchmarking flow
  .github/workflows/test.yml
  benchmark/src/main/scala/chisel3/benchmark/Benchmark.scala
  build.sc
Labels: Internal

#3993 Optimize truth table merge
  src/main/scala/chisel3/util/BitPat.scala
  src/main/scala/chisel3/util/experimental/decode/TruthTable.scala
  src/test/scala/chisel3/util/BitPatSpec.scala
  src/test/scala/chisel3/util/experimental/decode/TruthTableSpec.scala
  src/test/scala/chiselTests/util/BitPatSpec.scala
Labels: Merge with merge commit, Performance

#3992 Check format with mill
  .github/workflows/test.yml
  CONTRIBUTING.md
  benchmark/src/main/scala/chisel3/benchmark/Benchmark.scala
  build.sc
  common.sc
  lit/utility/src/package.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  panamaconverter/src/PanamaCIRCTPassManager.scala
  panamalib/src/PanamaCIRCT.scala
  panamalib/src/PanamaFirtoolOption.scala
  panamaom/src/PanamaCIRCTOM.scala
  tests.sc
Labels: Internal

#3936 Add integration test for PanamaCIRCT to firrtl converter
  flake.lock
  flake.nix
  lit/tests/Converter/Circuit.sc
  lit/tests/Converter/Debug.sc
  lit/tests/Converter/Module.sc
  overlay.nix
Labels: Please Merge, Internal, Panama

#3998 In BoringUtils.drive, don't bore into the final module for inputs.
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Bugfix

#3986 Add support for generic intrinsic expressions and statements.
  core/src/main/scala/chisel3/Intrinsic.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  docs/src/explanations/intrinsics.md
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  firrtl/src/test/scala/firrtlTests/SerializerSpec.scala
  src/test/scala/chiselTests/IntrinsicSpec.scala
Labels: Feature

#4008 Provide require message for negative widths
  core/src/main/scala/chisel3/Width.scala
  src/test/scala/chiselTests/UIntOps.scala
Labels: Bugfix

#4005 [ci] Stop copying body over to backports in backport-fixup
  .github/workflows/backport-fixup.yml
Labels: Internal

#4000 Use intrinsic expressions for most intrinsics
  src/main/scala/chisel3/util/circt/ClockGate.scala
  src/main/scala/chisel3/util/circt/IsX.scala
  src/main/scala/chisel3/util/circt/PlusArgsTest.scala
  src/main/scala/chisel3/util/circt/PlusArgsValue.scala
  src/main/scala/chisel3/util/circt/SizeOf.scala
  src/main/scala/chisel3/util/circt/Synthesis.scala
  src/test/scala/chiselTests/util/circt/ClockGate.scala
  src/test/scala/chiselTests/util/circt/IsXSpec.scala
  src/test/scala/chiselTests/util/circt/PlusArgsTestSpec.scala
  src/test/scala/chiselTests/util/circt/PlusArgsValueSpec.scala
  src/test/scala/chiselTests/util/circt/SizeOfSpec.scala
  src/test/scala/chiselTests/util/circt/Synthesis.scala
Labels: Backend Code Generation

#4011 HasBeenReset: use intrinsic expression
  core/src/main/scala/chisel3/Disable.scala
  core/src/main/scala/chisel3/Module.scala
  src/test/scala/chiselTests/DisableSpec.scala
  src/test/scala/chiselTests/LTLSpec.scala
Labels: Backend Code Generation

#4013 Add Tywaves project to community projects page
  website/src/pages/community.md
Labels: Documentation

#4003 make SerializableModuleGenerator work with D/I
  core/src/main/scala/chisel3/experimental/SerializableModuleGenerator.scala
  src/test/scala/chiselTests/experimental/SerializableModuleGeneratorSpec.scala
Labels: Feature, Please Merge

#4001 Add ifElseFatal intrinsics; use it for chisel3.assert emission
  core/src/main/scala/chisel3/BlackBox.scala
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/VerificationStatement.scala
  core/src/main/scala/chisel3/experimental/VerificationIntrinsics.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  src/test/scala/chiselTests/VerificationSpec.scala
  src/test/scala/chiselTests/naming/NamePluginSpec.scala
  src/test/scala/chiselTests/naming/PrefixSpec.scala
Labels: Backend Code Generation

#4018 Fix Nested Instantiate
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/BuilderContextCache.scala
  src/main/scala/chisel3/aop/injecting/InjectingAspect.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Labels: Bugfix, Please Merge

#4020 Add Instanitate.definition to get Definition from cache.
  core/src/main/scala/chisel3/experimental/hierarchy/Instantiate.scala
  src/test/scala/chiselTests/experimental/hierarchy/InstantiateSpec.scala
Labels: Feature, Please Merge

#4029 Fix Typo in ExtractFromVecSizeZero warning message
  core/src/main/scala/chisel3/Aggregate.scala
  src/test/scala/chiselTests/stage/WarningConfigurationSpec.scala
Labels: Bugfix

#4028 Subdivide OM primitive values into Scala types
  panamaom/src/PanamaCIRCTOM.scala
Labels: Please Merge, Internal
