Repository chipsalliance/chisel, pull requests merged in 2025-09, with the labels that each got.

#5012 Fix construction of PseudoModules to have correct parent
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/test/scala-2/chiselTests/aop/SelectSpec.scala
Labels: Bugfix

#5017 [svsim] Update c++ CFLAGS for verilator from c++14 to c++17
  svsim/src/main/scala/verilator/Backend.scala
Labels: Bugfix

#5018 [core] Add Temporal inline layer, trait
  core/src/main/scala/chisel3/layers/Layers.scala
  core/src/main/scala/chisel3/layers/package.scala
  src/test/scala-2/chiselTests/LayerSpec.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
Labels: Feature

#5020 [docs] Update layer docs for temporal layer, NFC
  docs/src/explanations/layers.md
Labels: Documentation

#5024 [chiselsim] Drop Temporal layers for Verilator Cli
  src/main/scala/chisel3/simulator/scalatest/Cli.scala
  src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala
  src/test/scala-2/chiselTests/simulator/scalatest/HasCliOptionsSpec.scala
Labels: Feature

#5027 [doc] Document temporal layers and ChiselSim
  docs/src/explanations/layers.md
  docs/src/explanations/testing.md
Labels: Documentation

#5030 Overload Stage methods to use Seq[Annotation]
  firrtl/src/main/scala/firrtl/options/Stage.scala
Labels: Bugfix

#5029 Fix binary compatibility for HasCliOptions.CliOption
  src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala
Labels: No Release Notes

#5028 Restore binary compatibility checking
  .github/workflows/enable-bincompat-checking.yml
  .github/workflows/test.yml
  build.mill
  etc/previous-versions.txt
  release.mill
Labels: Internal

#5033 Rename private[chisel3] SourceInfo$Intf to SourceInfoIntf
  core/src/main/scala-2/chisel3/experimental/SourceInfoIntf.scala
  core/src/main/scala-3/chisel3/experimental/SourceInfoIntf.scala
  core/src/main/scala/chisel3/experimental/SourceInfo.scala
Labels: Bugfix

#5037 [test] Make ChiselSim log test robust to Verilator
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: No Release Notes
