Repository chipsalliance/chisel, pull requests merged in 2025-07, with the labels that each got.

#4967 Bump os-lib to 0.10.7
  build.mill
Labels: Dependency Update

#4970 [chiselsim] Use allowlist for compilation includes
  src/main/scala/chisel3/simulator/package.scala
Labels: Feature

#4947 [Scala3] Add Bundle plugin
  core/src/main/scala-2/chisel3/SelectableCompat.scala
  core/src/main/scala-3/chisel3/BundleSelect.scala
  core/src/main/scala/chisel3/Aggregate.scala
  plugin/src/main/resources-3/plugin.properties
  plugin/src/main/scala-3/chisel3/internal/plugin/BundlePhase.scala
  plugin/src/main/scala-3/chisel3/internal/plugin/NamingPhase.scala
  plugin/src/main/scala-3/chisel3/internal/plugin/PluginHelpers.scala
  plugin/src/main/scala-3/chisel3/internal/plugin/Plugins.scala
Labels: Scala 3

#4975 [scalatest] More conservative testdir mangling
  src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
  src/test/scala-2/chiselTests/testing/scalatest/TestingDirectorySpec.scala
Labels: Bugfix

#4981 [test] Test after randomization in SimulatorSpec
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
Labels: No Release Notes

#4985 Bump to Mill 1.0.1
  .mill-version
  build.mill
Labels: Internal

#4976 Publish snapshots
  .github/scripts/publish.sh
  .github/workflows/ci.yml
  build.mill
  plugin/package.mill
  release.mill
Labels: Internal
