Repository chipsalliance/chisel, pull requests merged in 2025-01, with the labels that each got.

#4584 CIRCT converter: rename `portSyms` to `portSymbols`
  lit/tests/Property/Good.sc
  lit/tests/SmokeTest.sc
  panamaconverter/src/PanamaCIRCTConverter.scala
Labels: No Release Notes

#4587 Split up Decoupled.scala into multiple files, NFC
  src/main/scala/chisel3/util/Decoupled.scala
  src/main/scala/chisel3/util/Irrevocable.scala
  src/main/scala/chisel3/util/Queue.scala
  src/main/scala/chisel3/util/ReadyValidIO.scala
Labels: No Release Notes

#4586 Error rather than throw on scope violations
  core/src/main/scala/chisel3/BitsImpl.scala
  core/src/main/scala/chisel3/ChiselEnumImpl.scala
  core/src/main/scala/chisel3/DataImpl.scala
  core/src/main/scala/chisel3/MemImpl.scala
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/When.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/MonoConnect.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/properties/Class.scala
  core/src/main/scala/chisel3/properties/Property.scala
  panamaconverter/src/PanamaCIRCTConverter.scala
  src/test/scala/chiselTests/WhenSpec.scala
Labels: API Modification

#4572 Add input seq length check to Mux1H and PriorityMux
  src/main/scala/chisel3/util/MuxImpl.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/util/PriorityMuxSpec.scala
Labels: API Modification

#4588 [nfc] Break Pipe code out of Valid.scala
  src/main/scala/chisel3/util/Pipe.scala
  src/main/scala/chisel3/util/Valid.scala
Labels: No Release Notes

#4591 [scala3] Fix Scala3 difference in Probe API
  core/src/main/scala-3/chisel3/probe/Probe.scala
Labels: No Release Notes

#4594 fix typo in SourceInfoTransform.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Labels: Documentation

#4601 [website] Add a blog section and an initial blog post
  website/blog/2025/01-07-restarting-the-blog/index.md
  website/blog/authors.yml
  website/blog/tags.yml
  website/docusaurus.config.js
Labels: No Release Notes

#4602 Support boring on original Module after .toInstance call
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/test/scala/chiselTests/BoringUtilsSpec.scala
Labels: Bugfix

#4605 [docs] Add Cookbook entry for Verilog case equality (IsX)
  docs/src/cookbooks/cookbook.md
Labels: Documentation

#4606 Fixes `sendBits()`'s handling of signed numbers in `svsim` (backport #4599)
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/test/resources/SIntTest.sv
  svsim/src/test/scala/BackendSpec.scala
  svsim/src/test/scala/Resources.scala
Labels: Bugfix, Backport

#4609 Aggregate PriorityMux and Mux1H Seq size errors
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
  src/main/scala-2/chisel3/util/Mux.scala
  src/main/scala-3/chisel3/util/Mux.scala
  src/main/scala/chisel3/util/MuxImpl.scala
  src/test/scala/chiselTests/OneHotMuxSpec.scala
  src/test/scala/chiselTests/util/PriorityMuxSpec.scala
Labels: API Modification

#4613 update documentation for lit test
  docs/src/developers/lit-test.md
Labels: Please Merge, No Release Notes

#4614 [svsim] Fix initial ordering issue
  svsim/src/main/scala/Workspace.scala
  svsim/src/test/resources/Initial.sv
  svsim/src/test/scala/BackendSpec.scala
  svsim/src/test/scala/Resources.scala
Labels: Bugfix

#4624 Replace ??? with UnlocatableSourceInfo
  core/src/main/scala-3/chisel3/experimental/SourceInfo.scala
Labels: Internal

#4625 [docs] Fix pipe rendering in markdown table
  docs/src/explanations/operators.md
Labels: Documentation

#4616 Migrate to mill 0.12.5 and refactor mill scripts
  .github/workflows/ci.yml
  .github/workflows/test.yml
  .mill-jvm-opts
  .mill-version
  benchmark/package.mill
  build.mill
  build.sc
  circtpanamabinding/package.mill
  core/package.mill
  firrtl/package.mill
  flake.lock
  integration-tests/package.mill
  lit/package.mill
  lit/utility/package.mill
  macros/package.mill
  mill
  overlay.nix
  panama.sc
  panamaconverter/package.mill
  panamalib/package.mill
  panamaom/package.mill
  plugin/package.mill
  release.mill
  stdlib/package.mill
  svsim/package.mill
Labels: Please Merge, Dependency Update

#4633 Fix typo in #4632: correct JVM version
  .github/workflows/ci.yml
Labels: Please Merge, Internal

#4639 [scala3] Remove names from context parameters
  core/src/main/scala-3/chisel3/Aggregate.scala
  core/src/main/scala-3/chisel3/Bits.scala
  core/src/main/scala-3/chisel3/ChiselEnum.scala
  core/src/main/scala-3/chisel3/Clock.scala
  core/src/main/scala-3/chisel3/Data.scala
  core/src/main/scala-3/chisel3/Disable.scala
  core/src/main/scala-3/chisel3/Mem.scala
  core/src/main/scala-3/chisel3/Mux.scala
  core/src/main/scala-3/chisel3/Printf.scala
  core/src/main/scala-3/chisel3/PrintfMacros.scala
  core/src/main/scala-3/chisel3/VerificationStatementMacros.scala
  core/src/main/scala-3/chisel3/probe/Probe.scala
  core/src/main/scala-3/chisel3/probe/ProbeValue.scala
  core/src/main/scala-3/chisel3/probe/package.scala
  src/main/scala-3/chisel3/choice/ModuleChoice.scala
  src/main/scala-3/chisel3/util/BitPat.scala
  src/main/scala-3/chisel3/util/Bitwise.scala
  src/main/scala-3/chisel3/util/Cat.scala
  src/main/scala-3/chisel3/util/Mux.scala
  src/main/scala-3/chisel3/util/Reg.scala
Labels: API Modification

#4635 Add FormalTest marker
  core/src/main/scala/chisel3/FormalTest.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  firrtl/src/main/scala/firrtl/ir/IR.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/chiselTests/RawModuleSpec.scala
Labels: Feature

#4640 [mill] Guard scalaReflect under not Scala 3 in macros
  macros/package.mill
Labels: Internal

#4623 [core] Add layer block that returns colored wire
  core/src/main/scala/chisel3/Layer.scala
  src/test/scala/chiselTests/LayerSpec.scala
Labels: Feature

#4648 Fix chisel-plugin artifact publishing
  .github/workflows/ci.yml
  CONTRIBUTING.md
  plugin/package.mill
Labels: Internal

#4642 Add UnitTest marker and test discovery utility
  src/main/scala/chisel3/UnitTest.scala
  src/main/scala/chisel3/UnitTestMain.scala
  src/test/scala/chiselTests/ChiselSpec.scala
  src/test/scala/chiselTests/UnitTestMainSpec.scala
Labels: Feature

#4646 update DPI function call examples in chisel3.util.circt.dpi
  src/main/scala/chisel3/util/circt/DPI.scala
Labels: Documentation

#4649 Add -release:8 to scalacOptions
  build.mill
  core/package.mill
  firrtl/package.mill
  integration-tests/package.mill
  macros/package.mill
  plugin/package.mill
  stdlib/package.mill
  svsim/package.mill
Labels: Internal

#4647 Remove unused Builder methods
  core/src/main/scala/chisel3/internal/Builder.scala
Labels: No Release Notes

#4651 [svsim] Initialize ports to zero
  svsim/src/main/scala/Workspace.scala
Labels: Bugfix

#4653 Bump firtool-resolver to 2.0.1
  build.mill
Labels: Dependency Update

#4650 [ci] Speed up tests with testForkGrouping
  build.mill
  integration-tests/package.mill
Labels: Internal

#4654 Update mergify config generator and config
  .github/PULL_REQUEST_TEMPLATE.md
  .github/mergify/gen-config.sc
  .mergify.yml
Labels: Internal
