Repository chipsalliance/chisel, pull requests merged in 2025-06, with the labels that each got.

#4950 Add Lookupable for ActualDirection
  core/src/main/scala/chisel3/Data.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/Examples.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/InstanceSpec.scala
Labels: Feature

#4952 Make TestChoice.Globs.globs private
  src/main/scala/chisel3/experimental/inlinetest/InlineTest.scala
Labels: No Release Notes

#4953 Add OverrideSerializationClass for custom annotation serialization
  firrtl/src/main/scala/firrtl/annotations/JsonProtocol.scala
  firrtl/src/test/scala/firrtl/JsonProtocolSpec.scala
  firrtl/src/test/scala/firrtlTests/annotationTests/JsonProtocolSpec.scala
Labels: Feature

#4957 [docs] Fix BlackBoxRealAdd port widths
  docs/src/explanations/blackboxes.md
Labels: Documentation

#4961 Update Mill to 0.12.14
  .mill-version
  build.mill
  circtpanamabinding/package.mill
  docs/package.mill
  mill
  release.mill
Labels: Internal
