Repository chipsalliance/chisel, pull requests merged in 2025-05, with the labels that each got.

#4914 [blog] Add blog post about Latch Up 2025
  website/blog/2025/05-05-latch-up/index.md
  website/blog/authors.yml
  website/blog/tags.yml
Labels: Documentation

#4917 Improve error for bad connections with null module name
  core/src/main/scala/chisel3/Data.scala
  src/test/scala-2/chiselTests/ConnectableSpec.scala
Labels: Bugfix

#4922 fix: queue depth parameter name
  docs/src/developers/style.md
Labels: Documentation

#4923 [chiselsim] Set +incdir on all primary sources
  src/main/scala/chisel3/simulator/Simulator.scala
Labels: Internal

#4927 [testing] Mangle more directories
  src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
Labels: Bugfix

#4928 [testing] Mangle even more directories
  src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
Labels: Bugfix

#4931 [svsim/ChiselSim] Discover the project's root directory in a sandboxed build
  src/main/scala/chisel3/testing/FileCheck.scala
  src/main/scala/chisel3/testing/HasTestingDirectory.scala
  src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
  src/test/scala-2/chiselTests/experimental/TraceSpec.scala
  src/test/scala-2/chiselTests/stage/WarningConfigurationSpec.scala
  svsim/src/main/scala/Simulation.scala
  svsim/src/main/scala/Workspace.scala
Labels: Bugfix

#4933 [core] Add Bool "implies" method
  core/src/main/scala-2/chisel3/BitsIntf.scala
  src/test/scala-2/chiselTests/BoolSpec.scala
Labels: Feature

#4934 Add timing parameter support to Verilator backend
  svsim/src/main/scala/verilator/Backend.scala
Labels: Feature

#4911 [svsim] Trace options for the Verilator backend
  src/main/scala/chisel3/simulator/scalatest/Cli.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/Workspace.scala
  svsim/src/main/scala/verilator/Backend.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Feature

#4943 Fix naming plugin support for unapply
  plugin/src/main/scala-2/chisel3/internal/plugin/ChiselComponent.scala
  src/test/scala-2/chiselTests/naming/NamePluginSpec.scala
Labels: Bugfix
