Repository chipsalliance/chisel, pull requests merged in 2025-02, with the labels that each got.

#4660 Update CONTRIBUTING.md build and test instructions
  CONTRIBUTING.md
Labels: Documentation

#4657 Update mill-main to 0.12.7
  .mill-version
Labels: Internal

#4641 [internal] Use State.guard in ModuleImpl
  core/src/main/scala/chisel3/ModuleImpl.scala
Labels: No Release Notes

#4665 [chiselsim] Add Default (non-Ephemeral) Simulator
  src/main/scala-2/chisel3/simulator/DefaultSimulator.scala
  src/test/scala/chiselTests/simulator/DefaultSimulatorSpec.scala
Labels: Feature

#4667 Revert "Add publish flow for panama modules"
  .github/workflows/test.yml
  circtpanamabinding/package.mill
  panamaconverter/package.mill
  panamalib/package.mill
  panamaom/package.mill
  plugin/package.mill
Labels: Internal

#4670 Add publish flow for panama modules
  circtpanamabinding/package.mill
  panamaconverter/package.mill
  panamalib/package.mill
  panamaom/package.mill
  plugin/package.mill
Labels: Please Merge, Internal

#4669 [Chiselsim] Add WithTestingDirectory
  .gitignore
  build.mill
  build.sbt
  release.mill
  src/main/scala-2/chisel3/simulator/scalatest/WithTestingDirectory.scala
  src/test/scala/chiselTests/simulator/scalatest/WithTestingDirectorySpec.scala
Labels: Feature

#4672 Fix misoverrided publish version
  release.mill
Labels: Internal

#4674 [chiselsim] General cleanup
  src/main/scala-2/chisel3/simulator/DefaultSimulator.scala
  src/main/scala-2/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala-2/chisel3/simulator/Simulator.scala
  src/test/scala/chiselTests/simulator/DefaultSimulatorSpec.scala
  src/test/scala/chiselTests/simulator/EphemeralSimulatorSpec.scala
  src/test/scala/chiselTests/simulator/SimulatorSpec.scala
Labels: API Modification

#4677 [chiselsim] Remove test class name from directory
  src/main/scala-2/chisel3/simulator/DefaultSimulator.scala
  src/main/scala-2/chisel3/simulator/HasTestingDirectory.scala
  src/main/scala-2/chisel3/simulator/scalatest/WithTestingDirectory.scala
  src/test/scala/chiselTests/simulator/DefaultSimulatorSpec.scala
Labels: No Release Notes

#4679 [Scala3] Cross compile Simulator
  src/main/scala/chisel3/simulator/DefaultSimulator.scala
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/HasTestingDirectory.scala
  src/main/scala/chisel3/simulator/LayerControl.scala
  src/main/scala/chisel3/simulator/PeekPokeAPI.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/package.scala
  src/main/scala/chisel3/simulator/scalatest/WithTestingDirectory.scala
Labels: Internal

#4684 [firrtl] Add, use dramaticMessage
  firrtl/src/main/scala/firrtl/options/StageUtils.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
Labels: Feature

#4686 [chiselsim] Flatten out try/Try logic, NFC
  src/main/scala/chisel3/simulator/Simulator.scala
Labels: No Release Notes

#4685 [chiselsim] Add ChiselSim APIs
  src/main/scala/chisel3/simulator/package.scala
  src/main/scala/chisel3/simulator/scalatest/package.scala
Labels: Feature

#4688 Deterministic FibonacciLFSR reductions
  src/main/scala/chisel3/util/random/FibonacciLFSR.scala
Labels: Bugfix

#4683 Add ElaboratedCircuit and deprecate use of internal ir Circuit
  core/src/main/scala/chisel3/ElaboratedCircuit.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  docs/src/cookbooks/hierarchy.md
  docs/src/explanations/chisel-type-vs-scala-type.md
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/stage/phases/AddDedupGroupAnnotations.scala
  src/main/scala/chisel3/stage/phases/AddImplicitOutputAnnotationFile.scala
  src/main/scala/chisel3/stage/phases/AddImplicitOutputFile.scala
  src/main/scala/chisel3/stage/phases/AddSerializationAnnotations.scala
  src/main/scala/chisel3/stage/phases/Convert.scala
  src/main/scala/chisel3/stage/phases/Elaborate.scala
  src/main/scala/chisel3/stage/phases/Emitter.scala
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala-2/chisel3/stage/ChiselOptionsViewSpec.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
  src/test/scala-2/chiselTests/stage/phases/AddSerializationAnnotationsSpec.scala
  src/test/scala-2/chiselTests/stage/phases/ElaborateSpec.scala
  src/test/scala-2/circtTests/stage/ChiselStageSpec.scala
Labels: Deprecation

#4694 [chiselsim] Improve error behavior
  src/main/scala/chisel3/simulator/PeekPokeAPI.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/test/scala-2/chiselTests/simulator/DefaultSimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/EphemeralSimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/vcs/Backend.scala
  svsim/src/main/scala/verilator/Backend.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Bugfix

#4643 Add safer Chisel annotation API, deprecate old ones
  build.mill
  build.sbt
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/ChiselEnumImpl.scala
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/EnumAnnotations.scala
  core/src/main/scala/chisel3/experimental/Targetable.scala
  core/src/main/scala/chisel3/experimental/Trace.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/package.scala
  docs/src/cookbooks/hierarchy.md
  src/main/scala/chisel3/util/AttributeAnnotation.scala
  src/main/scala/chisel3/util/BlackBoxUtils.scala
  src/main/scala/chisel3/util/ExtModuleUtils.scala
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/main/scala/chisel3/util/experimental/Inline.scala
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
  src/main/scala/chisel3/util/experimental/decode/decoder.scala
  src/main/scala/circt/Convention.scala
  src/main/scala/circt/OutputDirAnnotation.scala
  src/test/scala-2/chiselTests/AnnotatingDiamondSpec.scala
  src/test/scala-2/chiselTests/BoringUtilsSpec.scala
  src/test/scala-2/chiselTests/ChiselEnum.scala
  src/test/scala-2/chiselTests/NewAnnotationsSpec.scala
  src/test/scala-2/chiselTests/experimental/DataViewTargetSpec.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/Annotations.scala
  src/test/scala-2/chiselTests/stage/phases/ConvertSpec.scala
  src/test/scala-2/chiselTests/util/SRAMSpec.scala
  src/test/scala-2/circtTests/stage/ChiselStageSpec.scala
Labels: Deprecation

#4698 Refine annotate and Targetable
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/experimental/Targetable.scala
  src/test/scala-2/chiselTests/NewAnnotationsSpec.scala
Labels: No Release Notes

#4629 Add simple API for generating testharnesses inline
  src/main/scala/chisel3/experimental/inlinetest/InlineTest.scala
  src/test/scala/chiselTests/experimental/InlineTestSpec.scala
Labels: Feature

#4702 [svsim] End Verilator simulation on $finish
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/main/scala/Workspace.scala
  svsim/src/test/resources/Finish.sv
  svsim/src/test/scala/BackendSpec.scala
  svsim/src/test/scala/Resources.scala
Labels: Bugfix

#4708 Dev/seldridge/switch to chisel settings
  src/main/scala/chisel3/simulator/ChiselSettings.scala
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
Labels: Feature

#4709 [svsim][chiselsim] Do not compile extract layery directories
  src/main/scala/chisel3/simulator/LayerControl.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/test/scala-2/chiselTests/ChiselSpec.scala
  src/test/scala-2/chiselTests/simulator/LayerControlSpec.scala
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/Workspace.scala
Labels: Bugfix

#4681 Add RequireProperty and EnsureProperty
  src/main/scala-2/chisel3/ltl/LTL.scala
  src/main/scala-2/chisel3/util/circt/LTLIntrinsics.scala
  src/test/scala-2/chiselTests/LTLSpec.scala
Labels: Feature

#4707 [ci] Add -oF to tests
  .github/workflows/test.yml
Labels: No Release Notes

#4715 [website] Host latest and snapshot Scala CLI examples
  .github/scripts/chisel-example.scala
  .github/scripts/generate-scala-cli-example.sh
  .github/workflows/build-scala-cli-example.yml
  website/.gitignore
  website/Makefile
Labels: Documentation

#4712 Re-land #4702
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/main/scala/Simulation.scala
  svsim/src/main/scala/Workspace.scala
  svsim/src/test/resources/Finish.sv
  svsim/src/test/scala/BackendSpec.scala
  svsim/src/test/scala/Resources.scala
Labels: Bugfix

#4699 [chiselsim] Add FIRRTL macro control
  src/main/scala/chisel3/simulator/ChiselSettings.scala
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4706 [Chiselsim] Replace Chiselspec w/ ChiselSim
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/stimulus/RunUntilFinished.scala
  src/main/scala/chisel3/simulator/stimulus/Stimulus.scala
  src/test/scala-2/chiselTests/Assert.scala
  src/test/scala-2/chiselTests/BoringUtilsSpec.scala
  src/test/scala-2/chiselTests/ProbeSpec.scala
Labels: Feature

#4718 [svsim] Wait after destroying simulator process
  svsim/src/main/scala/Simulation.scala
Labels: Bugfix

#4721 [test] Migrate QueueFlushSpec to ChiselSim
  integration-tests/src/test/scala-2/chiselTest/QueueFlushSpec.scala
Labels: No Release Notes

#4722 [chiselsim] Strip quotes, hash in Chiselsim directories
  src/main/scala/chisel3/simulator/scalatest/WithTestingDirectory.scala
Labels: Bugfix

#4717 Remove deprecated annotation APIs
  core/src/main/scala-2/chisel3/ChiselEnum.scala
  core/src/main/scala-3/chisel3/ChiselEnum.scala
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/ChiselEnumImpl.scala
  core/src/main/scala/chisel3/ModuleImpl.scala
  core/src/main/scala/chisel3/dontTouch.scala
  core/src/main/scala/chisel3/experimental/EnumAnnotations.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  core/src/main/scala/chisel3/internal/Builder.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  panamaconverter/src/Convert.scala
  src/main/scala/chisel3/stage/ChiselAnnotations.scala
  src/main/scala/chisel3/stage/ChiselOptions.scala
  src/main/scala/chisel3/stage/package.scala
  src/main/scala/chisel3/util/AttributeAnnotation.scala
  src/main/scala/chisel3/util/BlackBoxUtils.scala
  src/main/scala/chisel3/util/ExtModuleUtils.scala
  src/main/scala/chisel3/util/experimental/BoringUtils.scala
  src/main/scala/chisel3/util/experimental/ForceNames.scala
  src/main/scala/chisel3/util/experimental/Inline.scala
  src/main/scala/chisel3/util/experimental/LoadMemoryTransform.scala
  src/main/scala/chisel3/util/experimental/decode/decoder.scala
  src/main/scala/circt/Convention.scala
  src/main/scala/circt/OutputDirAnnotation.scala
  src/test/scala-2/chisel3/stage/ChiselOptionsViewSpec.scala
  src/test/scala-2/chiselTests/ChiselEnum.scala
  src/test/scala-2/chiselTests/DedupSpec.scala
Labels: API Modification

#4644 Selective view renaming
  core/src/main/scala/chisel3/Annotation.scala
  core/src/main/scala/chisel3/experimental/dataview/package.scala
  core/src/main/scala/chisel3/experimental/hierarchy/core/Lookupable.scala
Labels: Performance

#4726 [svsim] Fix VCS run_simulation function
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/main/scala/Workspace.scala
Labels: No Release Notes

#4732 [test] Fix Vending Machine check
  src/test/scala-2/examples/VendingMachineGenerator.scala
Labels: No Release Notes

#4727 Support mdoc from Mill and remove SBT
  .github/workflows/build-scala-cli-example.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  README.md
  build.mill
  build.sbt
  core/package.mill
  docs/Contributors.mill
  docs/FirtoolVersionsTable.mill
  docs/Releases.mill
  docs/Version.mill
  docs/package.mill
  docs/src/explanations/chisel-enum.md
  docs/src/explanations/dataview.md
  project/Contributors.scala
  project/FirtoolVersion.scala
  project/FirtoolVersionsTable.scala
  project/Releases.scala
  project/Version.scala
  project/build.properties
  project/plugins.sbt
  release.mill
  website/Makefile
Labels: Internal

#4742 [testers] Deprecate everything the testers package
  src/main/scala/chisel3/testers/BasicTester.scala
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/test/scala-2/chiselTests/TesterDriverSpec.scala
Labels: Deprecation

#4746 [testers] Delete chisel3.testers
  src/main/scala/chisel3/testers/BasicTester.scala
  src/main/scala/chisel3/testers/TesterDriver.scala
  src/main/scala/chisel3/testers/package.scala
  src/test/scala-2/chisel3/testers/TestUtils.scala
  src/test/scala-2/chiselTests/TesterDriverSpec.scala
Labels: API Modification

#4750 [testing] Testing package w/ HasTestingDirectory
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/HasSimulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/main/scala/chisel3/simulator/scalatest/package.scala
  src/main/scala/chisel3/testing/HasTestingDirectory.scala
  src/main/scala/chisel3/testing/scalatest/WithTestingDirectory.scala
  src/test/scala-2/chiselTests/simulator/DefaultSimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/HasSimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
  src/test/scala-2/chiselTests/testing/scalatest/TestingDirectorySpec.scala
Labels: No Release Notes

#4749 [testing] Add FileCheck API
  src/main/scala/chisel3/testing/FileCheck.scala
  src/main/scala/chisel3/testing/scalatest/package.scala
  src/test/scala-2/chiselTests/testing/FileCheckSpec.scala
Labels: Feature

#4754 Mass deprecations, to be removed in Chisel 7
  firrtl/src/main/scala/firrtl/FileUtils.scala
  firrtl/src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
  firrtl/src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  firrtl/src/test/scala/firrtlTests/FileUtilsSpec.scala
  src/test/scala-2/chiselTests/Harness.scala
Labels: Deprecation

#4757 Remove devcontainer, it is out-of-date and unused
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: No Release Notes
