Repository chipsalliance/chisel, pull requests merged in 2025-03, with the labels that each got.

#4691 Bump to and cross-compile for Scala 2.13.16
  .github/scripts/chisel-example.scala
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  build.mill
Labels: Dependency Update

#4760 [docs] Add ChiselSim, FileCheck documentation
  docs/src/appendix/migrating-from-chiseltest.md
  docs/src/explanations/testing.md
Labels: Documentation

#4762 [test] Don't dump FIRRTL in WidthSpec method
  src/test/scala-2/chiselTests/WidthSpec.scala
Labels: No Release Notes

#4763 [simulator] Remove DefaultSimulator
  src/main/scala/chisel3/simulator/DefaultSimulator.scala
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/test/scala-2/chiselTests/simulator/DefaultSimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
  src/test/scala-2/chiselTests/testing/scalatest/TestingDirectorySpec.scala
Labels: No Release Notes

#4748 Add Serializer for ChiselIR
  core/src/main/scala/chisel3/ElaboratedCircuit.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/firrtl/Serializer.scala
  firrtl/src/main/scala/firrtl/ir/Serializer.scala
  src/main/scala/circt/stage/phases/CIRCT.scala
  src/test/scala-2/chiselTests/BlackBox.scala
  src/test/scala-2/chiselTests/Direction.scala
  src/test/scala-2/chiselTests/InstanceNameSpec.scala
  src/test/scala-2/chiselTests/LiteralToTargetSpec.scala
  src/test/scala-2/chiselTests/Mem.scala
  src/test/scala-2/chiselTests/WhenSpec.scala
Labels: Performance

#4764 Warn on <literal>.asUInt|.asSInt(_: Int)
  core/src/main/scala/chisel3/package.scala
  macros/src/main/scala/chisel3/internal/sourceinfo/SourceInfoTransform.scala
Labels: Deprecation

#4682 Add formal contracts
  core/src/main/scala-2/chisel3/FormalContractIntf.scala
  core/src/main/scala-3/chisel3/FormalContractIntf.scala
  core/src/main/scala/chisel3/FormalContract.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  core/src/main/scala/chisel3/internal/firrtl/Serializer.scala
  src/test/scala/chiselTests/FormalContractSpec.scala
Labels: Feature

#4581 Update commons-text to 1.13.0
  build.mill
Labels: Dependency Update

#4767 [svsim] Cleanup simulation-driver.cpp
  svsim/src/main/resources/simulation-driver.cpp
Labels: No Release Notes

#4769 [svsim] Avoid EndOfMessages Exception
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/main/scala/Workspace.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Bugfix

#4774 [testing] Add HasTestingDirectory subdir factory
  src/main/scala/chisel3/testing/HasTestingDirectory.scala
  src/test/scala-2/chiselTests/testing/HasTestingDirectorySpec.scala
Labels: Feature

#4773 [chiselsim] Allow command line options to be passed to ChiselSim tests
  src/main/scala/chisel3/simulator/scalatest/package.scala
  src/main/scala/chisel3/testing/scalatest/HasConfigMap.scala
  src/test/scala-2/chiselTests/testing/scalatest/HasConfigMapSpec.scala
Labels: Feature

#4776 [scalatest] Add HasCliSimulator
  src/main/scala/chisel3/testing/scalatest/HasClilSimulator.scala
Labels: Feature

#4759 Fix extmodule emission when instantiating an imported Definition multiple times
  core/src/main/scala/chisel3/experimental/hierarchy/core/Instance.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/SeparateElaborationSpec.scala
Labels: Bugfix

#4782 Change Data._fromUInt to protected
  core/src/main/scala/chisel3/AggregateImpl.scala
  core/src/main/scala/chisel3/BitsImpl.scala
  core/src/main/scala/chisel3/ChiselEnumImpl.scala
  core/src/main/scala/chisel3/ClockImpl.scala
  core/src/main/scala/chisel3/DataImpl.scala
  core/src/main/scala/chisel3/experimental/Analog.scala
  core/src/main/scala/chisel3/properties/Property.scala
  src/test/scala-2/chiselTests/RecordSpec.scala
Labels: Feature

#4783 Fix for #4780
  svsim/src/main/scala/Workspace.scala
Labels: Bugfix

#4779 [chiselsim] Add ControlAPI w/ Waveform Enable/Disable Support
  src/main/scala/chisel3/simulator/ControlAPI.scala
  src/main/scala/chisel3/simulator/package.scala
  src/main/scala/chisel3/simulator/scalatest/package.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4786 Fix SInt literals to reject too small of widths
  core/src/main/scala/chisel3/internal/firrtl/IR.scala
  src/test/scala-2/chiselTests/SIntOps.scala
Labels: Bugfix

#4789 Add resetType to inline test TestParameters
  src/main/scala/chisel3/experimental/inlinetest/InlineTest.scala
  src/test/scala/chiselTests/experimental/InlineTestSpec.scala
Labels: Feature

#4787 [svsim] Error if waves enabled in unsupported sim
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/main/scala/Workspace.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Bugfix

#4792 [svsim] Use SNPS-specific license in VCS
  src/main/scala/chisel3/simulator/HasSimulator.scala
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/vcs/Backend.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Bugfix

#4793 [svsim] Add coverage collection to VCS backend
  svsim/src/main/scala/vcs/Backend.scala
  svsim/src/test/scala/BackendSpec.scala
Labels: Feature

#4794 [chiselsim] Chisel/firtool Options on SimulatorAPI
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/main/scala/chisel3/simulator/package.scala
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
Labels: API Modification

#4798 Use commit hashes for actions not owned by Github
  .github/workflows/build-scala-cli-example.yml
  .github/workflows/cd-circt.yml
  .github/workflows/ci-circt-nightly.yml
  .github/workflows/ci.yml
  .github/workflows/enable-bincompat-checking.yml
  .github/workflows/release-notes.yml
  .github/workflows/scala-cli-example.yml
  .github/workflows/test.yml
Labels: No Release Notes

#4799 Replace autoNameRecursively with chisel3.withName
  core/src/main/scala/chisel3/Module.scala
  core/src/main/scala/chisel3/SeqUtils.scala
  core/src/main/scala/chisel3/internal/plugin/package.scala
  core/src/main/scala/chisel3/package.scala
  docs/src/explanations/naming.md
  plugin/src/main/scala-2/chisel3/internal/plugin/ChiselComponent.scala
  src/main/scala-2/chisel3/util/SRAM.scala
  src/test/scala-2/chiselTests/naming/NamePluginSpec.scala
Labels: API Modification

#4658 Update data-class to 0.2.7
  build.mill
Labels: Dependency Update

#4800 [testing] Fix testing dir date/time stability
  src/main/scala/chisel3/testing/HasTestingDirectory.scala
  src/test/scala-2/chiselTests/testing/HasTestingDirectorySpec.scala
Labels: Bugfix

#4801 [chiselsim] Add waves at time zero to settings
  src/main/scala/chisel3/simulator/ChiselSettings.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4802 [chiselsim] Rename ChiselSettings to Settings
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/Settings.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: No Release Notes

#4805 Provide custom error for Mem masked write wrong data type
  core/src/main/scala-2/chisel3/MemIntf.scala
  core/src/main/scala-3/chisel3/MemIntf.scala
  core/src/main/scala/chisel3/Mem.scala
  src/main/scala-2/chisel3/util/SRAM.scala
Labels: Feature

#4807 [chiselsim] HasCliOptions, EmitVcd for ChiselSim
  src/main/scala/chisel3/simulator/scalatest/package.scala
Labels: Feature

#4808 [chiselsim] Chisel/firtool update type classes
  src/main/scala/chisel3/simulator/OptionsModifications.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/main/scala/chisel3/simulator/scalatest/Cli.scala
  src/main/scala/chisel3/simulator/scalatest/HasCliOptions.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4811 Make SVSim directory clearing more robust
  svsim/src/main/scala/Workspace.scala
Labels: Bugfix

#4812 [svsim] Add Coverage Directory and Name to VCS Backend
  svsim/src/main/scala/vcs/Backend.scala
Labels: Feature

#4814 [chiselsim] Change chiselSettings to settings
  src/main/scala/chisel3/simulator/EphemeralSimulator.scala
  src/main/scala/chisel3/simulator/Simulator.scala
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/test/scala-2/chiselTests/simulator/SimulatorSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: API Modification

#4813 Enable inlining in Scalac options
  build.mill
Labels: Performance

#4815 [chiselsim] Add subdirectory to SimulatorAPI fns
  src/main/scala/chisel3/simulator/SimulatorAPI.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4816 Deprecate ChiselStage.convert, replace with elaborate
  core/src/main/scala/chisel3/experimental/hierarchy/core/Definition.scala
  docs/src/cookbooks/hierarchy.md
  docs/src/explanations/chisel-type-vs-scala-type.md
  integration-tests/src/test/scala-2/chiselTest/util/SparseVecSpec.scala
  src/main/scala/circt/stage/ChiselStage.scala
  src/test/scala-2/chisel3/experimental/dataview/ReifySpec.scala
  src/test/scala-2/chiselTests/CloneModuleSpec.scala
  src/test/scala-2/chiselTests/DataEqualitySpec.scala
  src/test/scala-2/chiselTests/LayerSpec.scala
  src/test/scala-2/chiselTests/ReadOnlySpec.scala
  src/test/scala-2/chiselTests/experimental/ExtensionMethods.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/DefinitionSpec.scala
  src/test/scala-2/chiselTests/experimental/hierarchy/InstantiateSpec.scala
  src/test/scala-2/circtTests/stage/ChiselStageSpec.scala
Labels: Deprecation

#4825 [chiselsim] Add RunUntilSuccess stimulus
  src/main/scala/chisel3/simulator/stimulus/RunUntilFinished.scala
  src/main/scala/chisel3/simulator/stimulus/RunUntilSuccess.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4820 Add support for printing hierarchical names in Verilog (%m)
  core/src/main/scala/chisel3/Printable.scala
  core/src/main/scala/chisel3/internal/firrtl/Converter.scala
  core/src/main/scala/chisel3/internal/firrtl/Serializer.scala
  core/src/main/scala/chisel3/package.scala
  docs/src/explanations/printing.md
  src/test/scala-2/chiselTests/PrintableSpec.scala
  src/test/scala-2/chiselTests/Printf.scala
Labels: Feature

#4827 [docs] Fix wrong argument docs in SRAM object
  src/main/scala-2/chisel3/util/SRAM.scala
Labels: Documentation

#4829 Fix UInt unary negation ScalaDoc
  core/src/main/scala-2/chisel3/BitsIntf.scala
  core/src/main/scala-3/chisel3/BitsIntf.scala
Labels: Deprecation

#4835 [chiselsim] Add randomization to settings
  src/main/scala/chisel3/simulator/Randomization.scala
  src/main/scala/chisel3/simulator/Settings.scala
  src/test/scala-2/chiselTests/RecordSpec.scala
  src/test/scala-2/chiselTests/simulator/scalatest/ChiselSimSpec.scala
Labels: Feature

#4840 Fix layer.enable applying to all later modules
  core/src/main/scala/chisel3/internal/Builder.scala
  src/test/scala-2/chiselTests/LayerSpec.scala
Labels: Bugfix

#4845 [svsim] Use -no_save instead of ASLR workarounds
  svsim/src/main/resources/simulation-driver.cpp
  svsim/src/main/scala/Backend.scala
  svsim/src/main/scala/vcs/Backend.scala
Labels: Bugfix

#4838 [test] Revert to original RecordSpec, NFC
  src/test/scala-2/chiselTests/RecordSpec.scala
Labels: No Release Notes
